#!/bin/bash
#
# This script will dump the contents of the MySQL database to files.
#

# - Include common libraries and settings ------------------------------------
source "libui"
source "mysql_info"

# - Prepare required variables -----------------------------------------------
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TMP_FOLDER=${TMPDIR-/tmp}
# ----------------------------------------------------------------------------

function dump_data ()
{
    echo -n "Dumping contents of $1:$2 ..."
    [ ! -d ${DIR}/$1 ] && mkdir ${DIR}/$1
    mysqldump${OPTS} -Q --skip-dump-date --add-drop-table $1 $2 >${DIR}/$1/$2.sql
    echo " done"
}

function dump_struc ()
{
    echo -n "Dumping structure of $1:$2 ..."
    [ ! -d ${DIR}/$1 ] && mkdir ${DIR}/$1
    mysqldump${OPTS} -Q --skip-dump-date --add-drop-table --no-data $1 $2 >${DIR}/$1/$2.sql
    echo " done"
}

# ------------------------------------------------------------------------------
# Application tables with no data
# ------------------------------------------------------------------------------
dump_struc zp_world locales_creature
dump_struc zp_world locales_gameobject
dump_struc zp_world locales_gossip_menu_option
dump_struc zp_world locales_item
dump_struc zp_world locales_npc_text
dump_struc zp_world locales_page_text
dump_struc zp_world locales_points_of_interest
dump_struc zp_world locales_quest

# ------------------------------------------------------------------------------
# Application tables containing required data
# ------------------------------------------------------------------------------
dump_data  zp_world areatrigger_involvedrelation
dump_data  zp_world areatrigger_tavern
dump_data  zp_world areatrigger_teleport
dump_data  zp_world battleground_events
dump_data  zp_world battleground_template
dump_data  zp_world battlemaster_entry
dump_data  zp_world command
dump_data  zp_world creature
dump_data  zp_world creature_addon
dump_data  zp_world creature_ai_scripts
dump_data  zp_world creature_ai_summons
dump_data  zp_world creature_ai_texts
dump_data  zp_world creature_battleground
dump_data  zp_world creature_equip_template
dump_data  zp_world creature_equip_template_raw
dump_data  zp_world creature_involvedrelation
dump_data  zp_world creature_linking_template
dump_data  zp_world creature_loot_template
dump_data  zp_world creature_model_info
dump_data  zp_world creature_movement
dump_data  zp_world creature_movement_scripts
dump_data  zp_world creature_movement_template
dump_data  zp_world creature_onkill_reputation
dump_data  zp_world creature_questrelation
dump_data  zp_world creature_template
dump_data  zp_world creature_template_addon
dump_data  zp_world db_script_string
dump_data  zp_world db_version
dump_data  zp_world disenchant_loot_template
dump_data  zp_world event_scripts
dump_data  zp_world exploration_basexp
dump_data  zp_world fishing_loot_template
dump_data  zp_world gameobject
dump_data  zp_world gameobject_battleground
dump_data  zp_world gameobject_involvedrelation
dump_data  zp_world gameobject_loot_template
dump_data  zp_world gameobject_questrelation
dump_data  zp_world gameobject_scripts
dump_data  zp_world gameobject_template
dump_data  zp_world game_event
dump_data  zp_world game_event_creature
dump_data  zp_world game_event_creature_data
dump_data  zp_world game_event_gameobject
dump_data  zp_world game_event_mail
dump_data  zp_world game_event_quest
dump_data  zp_world game_graveyard_zone
dump_data  zp_world game_tele
dump_data  zp_world game_weather
dump_data  zp_world gossip_menu
dump_data  zp_world gossip_menu_option
dump_data  zp_world gossip_scripts
dump_data  zp_world instance_template
dump_data  zp_world item_enchantment_template
dump_data  zp_world item_loot_template
dump_data  zp_world item_required_target
dump_data  zp_world item_template
dump_data  zp_world mail_loot_template
dump_data  zp_world mangos_string
dump_data  zp_world npc_gossip
dump_data  zp_world npc_text
dump_data  zp_world npc_trainer
dump_data  zp_world npc_trainer_template
dump_data  zp_world npc_vendor
dump_data  zp_world npc_vendor_template
dump_data  zp_world page_text
dump_data  zp_world petcreateinfo_spell
dump_data  zp_world pet_levelstats
dump_data  zp_world pet_name_generation
dump_data  zp_world pickpocketing_loot_template
dump_data  zp_world playercreateinfo
dump_data  zp_world playercreateinfo_action
dump_data  zp_world playercreateinfo_item
dump_data  zp_world playercreateinfo_spell
dump_data  zp_world player_classlevelstats
dump_data  zp_world player_levelstats
dump_data  zp_world player_xp_for_level
dump_data  zp_world points_of_interest
dump_data  zp_world pool_creature
dump_data  zp_world pool_creature_template
dump_data  zp_world pool_gameobject
dump_data  zp_world pool_gameobject_template
dump_data  zp_world pool_pool
dump_data  zp_world pool_template
dump_data  zp_world quest_end_scripts
dump_data  zp_world quest_start_scripts
dump_data  zp_world quest_template
dump_data  zp_world reference_loot_template
dump_data  zp_world reputation_reward_rate
dump_data  zp_world reputation_spillover_template
dump_data  zp_world reserved_name
dump_data  zp_world scripted_areatrigger
dump_data  zp_world scripted_event_id
dump_data  zp_world skill_fishing_base_level
dump_data  zp_world skinning_loot_template
dump_data  zp_world spell_affect
dump_data  zp_world spell_area
dump_data  zp_world spell_bonus_data
dump_data  zp_world spell_chain
dump_data  zp_world spell_elixir
dump_data  zp_world spell_facing
dump_data  zp_world spell_learn_spell
dump_data  zp_world spell_pet_auras
dump_data  zp_world spell_proc_event
dump_data  zp_world spell_proc_item_enchant
dump_data  zp_world spell_scripts
dump_data  zp_world spell_script_target
dump_data  zp_world spell_target_position
dump_data  zp_world spell_threat
dump_data  zp_world transports
dump_data  zp_world world_template
