#!/bin/bash
#
# This script will turn single-line INSERT statements in the SQL dumps
# into readable multi-line statements.

# Replace VALUES ( by VALUES\n(
find ./ -name '*.sql' -type f -exec perl -pi -e 's/VALUES \(/VALUES\n\(/g' {} \; -print

# Replace huge insert by multi-line inserts
find ./ -name '*.sql' -type f -exec perl -pi -e 's/\),\(/\),\n\(/g' {} \; -print
