#!/bin/bash
#
# This script will dump the contents of the MySQL database to files.
#

# - Include common libraries and settings ------------------------------------
source "../libui"
source "../mysql_info"

# - Prepare required variables -----------------------------------------------
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TMP_FOLDER=${TMPDIR-/tmp}
# ----------------------------------------------------------------------------

function dump_data ()
{
    echo -n "Dumping contents of $1:$2 ..."
    [ ! -d ${DIR}/$1 ] && mkdir ${DIR}/$1
    mysqldump${OPTS} -Q --skip-dump-date --add-drop-table $1 $2 >${DIR}/$1/$2.sql
    echo " done"
}

function dump_struc ()
{
    echo -n "Dumping structure of $1:$2 ..."
    [ ! -d ${DIR}/$1 ] && mkdir ${DIR}/$1
    mysqldump${OPTS} -Q --skip-dump-date --add-drop-table --no-data $1 $2 >${DIR}/$1/$2.sql
    echo " done"
}

# ------------------------------------------------------------------------------
# Application tables with no data
# ------------------------------------------------------------------------------
dump_struc mangos locales_creature
dump_struc mangos locales_gameobject
dump_struc mangos locales_gossip_menu_option
dump_struc mangos locales_item
dump_struc mangos locales_npc_text
dump_struc mangos locales_page_text
dump_struc mangos locales_points_of_interest
dump_struc mangos locales_quest

# ------------------------------------------------------------------------------
# Application tables containing required data
# ------------------------------------------------------------------------------
dump_data  mangos areatrigger_involvedrelation
dump_data  mangos areatrigger_tavern
dump_data  mangos areatrigger_teleport
dump_data  mangos battleground_events
dump_data  mangos battleground_template
dump_data  mangos battlemaster_entry
dump_data  mangos command
dump_data  mangos conditions
dump_data  mangos creature
dump_data  mangos creature_addon
dump_data  mangos creature_ai_scripts
dump_data  mangos creature_ai_summons
dump_data  mangos creature_ai_texts
dump_data  mangos creature_battleground
dump_data  mangos creature_equip_template
dump_data  mangos creature_equip_template_raw
dump_data  mangos creature_involvedrelation
dump_data  mangos creature_linking
dump_data  mangos creature_linking_template
dump_data  mangos creature_loot_template
dump_data  mangos creature_model_info
dump_data  mangos creature_movement
dump_data  mangos creature_movement_template
dump_data  mangos creature_onkill_reputation
dump_data  mangos creature_questrelation
dump_data  mangos creature_template
dump_data  mangos creature_template_addon
dump_data  mangos creature_template_spells
dump_data  mangos db_script_string
dump_data  mangos db_version
dump_data  mangos dbscripts_on_creature_movement
dump_data  mangos dbscripts_on_event
dump_data  mangos dbscripts_on_go_template_use
dump_data  mangos dbscripts_on_go_use
dump_data  mangos dbscripts_on_gossip
dump_data  mangos dbscripts_on_quest_end
dump_data  mangos dbscripts_on_quest_start
dump_data  mangos dbscripts_on_spell
dump_data  mangos disenchant_loot_template
dump_data  mangos exploration_basexp
dump_data  mangos fishing_loot_template
dump_data  mangos gameobject
dump_data  mangos gameobject_battleground
dump_data  mangos gameobject_involvedrelation
dump_data  mangos gameobject_loot_template
dump_data  mangos gameobject_questrelation
dump_data  mangos gameobject_scripts
dump_data  mangos gameobject_template
dump_data  mangos game_event
dump_data  mangos game_event_creature
dump_data  mangos game_event_creature_data
dump_data  mangos game_event_gameobject
dump_data  mangos game_event_mail
dump_data  mangos game_event_quest
dump_data  mangos game_graveyard_zone
dump_data  mangos game_tele
dump_data  mangos game_weather
dump_data  mangos gossip_menu
dump_data  mangos gossip_menu_option
dump_data  mangos instance_template
dump_data  mangos item_enchantment_template
dump_data  mangos item_loot_template
dump_data  mangos item_required_target
dump_data  mangos item_template
dump_data  mangos mail_loot_template
dump_data  mangos mangos_string
dump_data  mangos npc_gossip
dump_data  mangos npc_text
dump_data  mangos npc_trainer
dump_data  mangos npc_trainer_template
dump_data  mangos npc_vendor
dump_data  mangos npc_vendor_template
dump_data  mangos page_text
dump_data  mangos petcreateinfo_spell
dump_data  mangos pet_levelstats
dump_data  mangos pet_name_generation
dump_data  mangos pickpocketing_loot_template
dump_data  mangos playercreateinfo
dump_data  mangos playercreateinfo_action
dump_data  mangos playercreateinfo_item
dump_data  mangos playercreateinfo_spell
dump_data  mangos player_classlevelstats
dump_data  mangos player_levelstats
dump_data  mangos player_xp_for_level
dump_data  mangos points_of_interest
dump_data  mangos pool_creature
dump_data  mangos pool_creature_template
dump_data  mangos pool_gameobject
dump_data  mangos pool_gameobject_template
dump_data  mangos pool_pool
dump_data  mangos pool_template
dump_data  mangos quest_template
dump_data  mangos reference_loot_template
dump_data  mangos reputation_reward_rate
dump_data  mangos reputation_spillover_template
dump_data  mangos reserved_name
dump_data  mangos scripted_areatrigger
dump_data  mangos scripted_event_id
dump_data  mangos skill_fishing_base_level
dump_data  mangos skinning_loot_template
dump_data  mangos spell_affect
dump_data  mangos spell_area
dump_data  mangos spell_bonus_data
dump_data  mangos spell_chain
dump_data  mangos spell_elixir
dump_data  mangos spell_facing
dump_data  mangos spell_learn_spell
dump_data  mangos spell_pet_auras
dump_data  mangos spell_proc_event
dump_data  mangos spell_proc_item_enchant
dump_data  mangos spell_script_target
dump_data  mangos spell_target_position
dump_data  mangos spell_threat
dump_data  mangos transports
dump_data  mangos world_template
