-- ============================================================
-- locales_creature
-- ============================================================
UPDATE `locales_creature` SET `name_loc3`='Bluthornschmetterschwanz' WHERE `entry`=3254; -- Sunscale Lashtail
UPDATE `locales_creature` SET `name_loc3`='Bluthornkreischer' WHERE `entry`=3255; -- Sunscale Screecher
UPDATE `locales_creature` SET `name_loc3`='Bluthornsensenklaue' WHERE `entry`=3256; -- Sunscale Scytheclaw
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrer' WHERE `entry`=3690; -- Kar Stormsinger Riding Trainer
UPDATE `locales_creature` SET `name_loc3`='Randal Waidmann', `subname_loc3`='Reitlehrer' WHERE `entry`=4732; -- Randal Weidmann Riding Trainer
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrer' WHERE `entry`=4752; -- Kildar Riding Trainer
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrer' WHERE `entry`=4753; -- Jartsam Riding Trainer
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrer' WHERE `entry`=4772; -- Ultham Ironhorn Riding Trainer
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrerin' WHERE `entry`=4773; -- Velma Warnam Riding Trainer
UPDATE `locales_creature` SET `subname_loc3`='Roboschreiterpilot' WHERE `entry`=7954; -- Reitlehrer
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrerin' WHERE `entry`=7953; -- Xar'Ti Riding Trainer
UPDATE `locales_creature` SET `name_loc3`='Nessa Schattensang' WHERE `entry`=10118; -- Nessa Shadowsong
UPDATE `locales_creature` SET `name_loc3`='Vaelan' WHERE `entry`=10296; -- Vaelan
UPDATE `locales_creature` SET `name_loc3`='Spitzel der Schmetterschilde', `subname_loc3`='Schmetterschildlegion' WHERE `entry`=10299; -- Scarshield Infiltrator
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrer' WHERE `entry`=16280; -- Perascamin Riding Trainer
UPDATE `locales_creature` SET `name_loc3`='Weissager Nobundo' WHERE `entry`=17204; -- Farseer Nobundo
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrer' WHERE `entry`=20500; -- Olrokk Riding Trainer
UPDATE `locales_creature` SET `name_loc3`='Ilsa Trubelbräu', `subname_loc3`='Reitlehrerin' WHERE `entry`=20511; -- Ilsa TrubelbrÃ¤u Riding Trainer
UPDATE `locales_creature` SET `subname_loc3`='Reitlehrerin' WHERE `entry`=20914; -- Aalun Riding Trainer

-- Zeppelin Master in Durotar, Tirisfal and Gromgol
UPDATE `locales_creature` SET `subname_loc3`='Zeppelinmeister' WHERE `entry`=3149 OR `entry`=3150 OR `entry`=9564 OR `entry`=9566 OR `entry`=12137 OR `entry`=12136; 

-- ============================================================
-- locales_quest
-- ============================================================
-- ID 877 The Stagnant Oasis
Update `locales_quest` SET `Title_loc3`='Die brackige Oase', `Details_loc3`='Erdrisse wie jene, die Ihr bei den vergessenen Teichen gefunden habt, könnte es auch bei anderen Oasen im Brachland geben. Wenn es so ist, sind diese Risse vielleicht die Lebensquelle dieser Oasen.$B$BWir müssen das überprüfen.$B$BHier, nehmt diese Samen. Sie sind tot und unfruchtbar, aber bringt sie dennoch zur brackigen Oase im Südosten. Falls es dort einen Riss gibt, legt die Samen hinein und... wartet ab.', `Objectives_loc3`='Kehrt zu Tonga beim Wegekreuz zurück, nachdem Ihr die brackige Oase untersucht habt.', `RequestItemsText_loc3`='Wart Ihr in der brackigen Oase? Gab es dort einen Riss unterhalb des Gewässers?', `OfferRewardText_loc3`='Eure Entdeckungen sind erstaunlich! Die Samen, die ich Euch gab, waren vertrocknet und tot. Was immer auch unter diesen Oasen schlummert, kann aus dem Nichts Leben entstehen lassen!$B$BWir müssen das noch genauer studieren…', ObjectiveText1_loc3='Probiert die getrockneten Samenkörner aus.' WHERE `entry`=877;
-- ID 881 Echeyakee
Update `locales_quest` SET `Title_loc3`='Echeyakee', `Details_loc3`='Weißnebel, Echeyakee in der Sprache der Tauren, ist der König der Savannenkatzen. Er jagt mit solcher Verstohlenheit, dass man sagt, er sei wie ein dünner, weißer Nebel auf der Erde. Und er tötet so schnell, dass seine Beute weder Angst noch Schmerz verspürt.$B$BDie Tauren sagen, er sei sowohl Gnade als auch Tod.$B$BIhr werdet erfahren, ob das wahr ist, denn ich schicke Euch aus, um Echeyakee zu jagen. Sein Unterschlupf befindet sich nordöstlich des Wegekreuzes, zwischen den Knochen des riesigen Kodos.$B$BGeht jetzt. Blast dieses Horn, wenn Ihr seinen Unterschlupf erreicht. Blast das Horn und er wird kommen.', `Objectives_loc3`='Bringt Sergra Dunkeldorn beim Wegekreuz Echeyakees Balg.', `RequestItemsText_loc3`='Die große Katze ruft Euch, $N.', `OfferRewardText_loc3`='Ihr habt Echeyakee geschlagen und obwohl seine Tage als Jäger vorbei sind... ist sein Geist mit Euch. Er wird Euch die Kraft zeigen, die im Feingefühl liegt, und welche Ehre Gnade birgt.$B$BEuer Weg ist immer noch lang, $C. Hoffen wir, dass Ihr ihn gut beschreitet.', ObjectiveText1_loc3='' WHERE `entry`=881;
-- ID 903 Prowlers of the Barrens
Update `locales_quest` SET `Title_loc3`='Streuner des Brachlandes', `Details_loc3`='Es ist nun an der Zeit, etwas zu jagen, das sich wirklich wehrt. Die Streuner des Brachlandes sind von zäher Art. Zäh, erfinderisch, listig... und tödlich. Ihr findet sie zwischen den hohen Gräsern. Ihr werdet viele südwestlich des Wegekreuzes finden.$B$BSeid vorsichtig, wenn Ihr sie jagt, $N, oder Ihr werdet feststellen, dass Ihr nicht mehr Jäger, sondern Gejagter seid.', `Objectives_loc3`='Besorgt für Sergra Dunkeldorn beim Wegekreuz 7 Streunerklauen von den Savannenstreunern.', `RequestItemsText_loc3`='Wie läuft Eure Jagd, $N? Habt Ihr die Streuner gefunden?', `OfferRewardText_loc3`='Ah, ich sehe, Ihr wart damit beschäftigt, im Gras zu lauern und Streuner zu jagen. Glaubt Ihr, dass es an der Zeit ist, einem Champion unter ihnen gegenüberzutreten?' WHERE `entry`=903;
-- ID 3301 Mura Runetotem
Update `locales_quest` SET `Title_loc3`='Mura Runentotem', `Details_loc3`='Meine Klangefährtin, Mura Runentotem, ist nach Silberwald gereist, um unseren untoten Verbündeten zu helfen. Der Silberwald ist ein kranker Wald, ein sterbender Wald, und Muras Hoffnung war, ihm neues Leben zu bringen. Vielleicht kann dieses seltsame Leben, das wir im Brachland gefunden haben, ihr bei ihrer Arbeit im Silberwald helfen.$B$BBringt eine Probe der von Euch gesammelten Schalen zu Mura nach Silberwald. Sie hält sich in dem Grabmal auf. Mit etwas Glück vermittelt ihr das Studium der Schalen den Einblick, den sie benötigt, um diesen sterbenden Ort zu heilen.', `Objectives_loc3`='Sprecht mit Mura Runentotem in dem Grabmal.', `RequestItemsText_loc3`='Ich kann den Staub des Brachlandes an Euch riechen, $C. Ihr seid weit gereist.', `OfferRewardText_loc3`='Ah... was ist denn das? Diese Schale glüht von innen, als ob in ihr noch Leben pulsierte. Erstaunlich! Ich muss sie weiter untersuchen.$B$BDanke, $N, Wenn wir Glück haben, enthält diese Schale ein Geheimnis, das ich verwenden kann, um dem armen Land Silberwald zu helfen.', ObjectiveText1_loc3='' WHERE `entry`=3301;
-- q.4184
UPDATE `locales_quest` SET `Title_loc3`='Die wahren Meister', `Details_loc3`='Reist nach Sturmwind und tragt Solomons Hilfegesuch dem Hochlord Bolvar Fordragon vor.$B$BBolvar residiert in der Burg Sturmwind.', `Objectives_loc3`='Reist nach Sturmwind und tragt Solomons Hilfegesuch dem Hochlord Bolvar Fordragon vor.$B$BBolvar residiert in der Burg Sturmwind.' WHERE `entry`=4184;
-- ID 5041 Supplies for the Crossroads
Update `locales_quest` SET `Title_loc3`='Vorräte für das Wegekreuz', `Details_loc3`='Die Karawane, die angegriffen wurde, führte Vorräte mit sich, die wir dringend benötigen.$B$BIhr wart bisher tapfer genug, den Klingenmähnenstamm zu bekämpfen, und ich werde Euch bitten, es erneut zu tun. Dieses Mal wüsste ich aber gern, ob ich Euch bitten könnte, nach unseren verlorenen Vorräten Ausschau zu halten. Ihr könnt sie wahrscheinlich in ihren Lagern finden; die Stacheleber werden durch ihre schändlichen Taten fett.$B$BDie Einwohner des Wegekreuzes wären in Eurer Schuld.', `Objectives_loc3`='Findet die Vorratskisten des Wegekreuzes und bringt sie zu Thork im Brachland zurück.', `RequestItemsText_loc3`='Wie läuft Eure Suche nach den Vorräten, $N? Ich schätze, die Stacheleber werden unter Eurer Kraft schnell fallen.', `OfferRewardText_loc3`='Haha! Danke, $N! Das wird uns höchst dienlich sein. Ihr seid ein Segen für Crossroads und die Horde. Wenn ich etwas für Euch tun kann, dann lasst es mich bitte wissen.' WHERE `entry`=5041;
-- q.6344
UPDATE `locales_quest` SET `Title_loc3`='Nessa Schattensang', `Details_loc3`='Eine Freundin von mir, Nessa Schattensang, ist Anglerbedarfshändlerin in Rut\'theran. Sie muss ein Päckchen nach Dunkelküste bringen und sucht jemanden, der ihr hilft.$B$BWenn Ihr zu Nessa wollt, dann müsst Ihr in Darnassus das Portal nach Rut\theran benutzen. Ihr findet das Portal westlich der Tempelgärten.', `Objectives_loc3`='Sprecht mit Nessa Schattensang.' WHERE `entry`=6344;
-- ID 6386 Return to the Crossroads.
Update `locales_quest` SET `Title_loc3`='Kehrt zum Wegekreuz zurück', `Details_loc3`='Meine Windreiter wurden ausgebildet, an viele verschiedene Orte zu fliegen, wenn Ihr schon an diesem Ort gewesen seid und mit dem Windreitermeister dort gesprochen habt.$B$BIhr seid am Wegekreuz gewesen und habt mit dem Windreitermeister Devrak gesprochen, daher könnt Ihr jetzt direkt zu ihm fliegen. Wenn Ihr beim Wegekreuz seid, könnt Ihr Gryshkas Brief zu Zargh bringen.$B$BSprecht wieder mit mir, wenn Ihr bereit zum Aufbruch seid.', `Objectives_loc3`='Bucht einen Windreiter zum Wegekreuz bei Windreitermeister Doras und bringt dann Gryshkas Brief zu Zargh beim Wegekreuz.', `RequestItemsText_loc3`='Seid Ihr von Orgrimmar zurück? Hat Gryshka das Fleisch geschmeckt, das ich ihr geschickt habe?', `OfferRewardText_loc3`='Ha! Natürlich hat es ihr geschmeckt! Nichts macht die Wangen einer Dame so rot wie ein großes, saftiges Steak!$B$BDanke, $N. Ihr habt mir einen großen Dienst erwiesen. Hier habt Ihr etwas Geld für Eure Mühe, und seid nicht überrascht, wenn ich Euch zu meiner Hochzeit einlade!' WHERE `entry`=6386;
-- ID 9504 Call of Water
Update `locales_quest` SET `Title_loc3`='Ruf des Wassers', `Details_loc3`='Es ist schlimmer als ich befürchtet hatte. Die Verunreinigung ist hartnäckig und könnte, wenn man nicht rechtzeitig handelt, ungehindert in die Ströme des Meeres fließen und sich somit in ganz Azeroth ausbreiten!$B$BWir brauchen eine Probe reinsten Wassers, um diesem Übel entgegenzuwirken. Auf dem nahegelegenen Kontinent Kalimdor gibt es ein Waldgebiet namens Eschental. Unweit seiner südwestlichen Begrenzung findet Ihr die Sternenstaubruinen.$B$BNehmt diesen Botabeutel und füllt ihn mit Wasser aus dem Brunnen auf der kleinen Insel im Zentrum der Ruinen. Beeilt Euch, $N!', `Objectives_loc3`='Füllt den leeren Botabeutel und kehrt anschließend zu Aqueous im versteckten Riff bei der Blutmythosinsel zurück.', `RequestItemsText_loc3`='Habt Ihr das reine Wasser von den Ruinen?', `OfferRewardText_loc3`='Wasser schwindet schnell, vereinigt man aber genug davon, bildet es eine unaufhaltsame Kraft. Es spült Erde und Feuer hinfort und bahnt sich auch durch die Luft seinen Weg.$B$BWir sind diese unaufhaltsame Kraft, $N, nicht diejenigen, die die Blutmythosinsel vergiftet haben!' WHERE `entry`=9504;
-- ID 9509 Call of Water
Update `locales_quest` SET `Title_loc3`='Ruf des Wassers', `Details_loc3`='Ich habe etwas von dem Wasser aus dem Eschental beiseite gelegt, jedoch nicht, weil ich an Euren Fähigkeiten, die Situation in den Griff zu bekommen, gezweifelt habe. Im Gegenteil, ich wusste, dass Ihr Erfolg haben würdet. Ich wollte lediglich sicherstellen, dass Ihr etwas Besonderes habt, das Ihr zurück zu Nobundo bringen könnt.$B$BHier, $N, nehmt dieses Fläschchen mit reinstem Wasser. Die Erstellung eines mächtigen Wassertotems ist Euch dadurch gewiss.$B$BWeissager Nobundo erwartet Eure Rückkehr bei der Exodar.', `Objectives_loc3`='Nehmt das Fläschchen mit reinstem Wasser zu Weissager Nobundo innerhalb der Exodar auf der Azurmythosinsel.', `RequestItemsText_loc3`='Die Elemente haben mir von großen Taten erzählt, die Ihr vollbracht habt. Kommt, sprecht mit mir.', `OfferRewardText_loc3`='Ihr habt eine Weisheit an den Tag gelegt, die Eurem Alter vorauseilt, $N. Ich kann spüren, dass das Element des Wassers mit Euch zufrieden ist. Es ist eine Ehre für mich, wenn ich das reine Wasser, das Ihr mir gebracht habt, in Euer neues Wassertotem einfließen lassen kann.$B$BVergesst niemals die Lehren des Wassers und Ihr werdet das Element mit der Zeit noch besser verstehen und zu meistern lernen.' WHERE `entry`=9509;

-- ============================================================
-- locales_item
-- ============================================================
UPDATE `locales_item` SET `name_loc3`='Leere Phiole' WHERE `entry`=3371; -- Empty Vial
UPDATE `locales_item` SET `name_loc3`='Verbleite Phiole' WHERE `entry`=3372; -- Leaded Vial
UPDATE `locales_item` SET `name_loc3`='Winterbiss' WHERE `entry`=3819; -- Wintersbite
Update `locales_item` SET `name_loc3`='Streunerklauen' WHERE `entry`=5096; -- Prowler Claws
Update `locales_item` SET `name_loc3`='Bluthornfeder' WHERE `entry`=5165; -- Sunscale Feather
UPDATE `locales_item` SET `name_loc3`='Kristallphiole' WHERE `entry`=8925; -- Crystal Vial
UPDATE `locales_item` SET `name_loc3`='Magieerfüllte Phiole' WHERE `entry`=18256; -- Imbued Vial

