-- Qiraji Mindslayer / Qiraji Slayer

SET @entrystart := 25373;
DELETE FROM `pool_template` WHERE `entry` BETWEEN @entrystart AND @entrystart +33;
INSERT INTO `pool_template` (`entry`, `max_limit`, `description`) VALUES 
(@entrystart + 0, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 1, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 2, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 3, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 4, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 5, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 6, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 7, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 8, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 9, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 10, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 11, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 12, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 13, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 14, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 15, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 16, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 17, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 18, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 19, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 20, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 21, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 22, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 23, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 24, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 25, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 26, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 27, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 28, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 29, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 30, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 31, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 32, 1, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@entrystart + 33, 1, 'AQ40 - Qiraji Mindslayer / Slayer');

