-- Qiraji Mindslayer / Qiraji Slayer

SET @guidstart := 93762;
SET @poolentrystart := 25373;
DELETE FROM `pool_creature` WHERE `guid` BETWEEN @guidstart + 0 AND @guidstart + 63;
INSERT INTO `pool_creature` (`guid`, `pool_entry`, `chance`, `description`) VALUES 
(@guidstart + 0, @poolentrystart + 0, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 1, @poolentrystart + 1, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 2, @poolentrystart + 2, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 3, @poolentrystart + 3, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 4, @poolentrystart + 0, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 5, @poolentrystart + 1, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 6, @poolentrystart + 2, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 7, @poolentrystart + 3, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),

(@guidstart + 8, @poolentrystart + 4, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 9, @poolentrystart + 5, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 10, @poolentrystart + 6, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 11, @poolentrystart + 7, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 12, @poolentrystart + 4, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 13, @poolentrystart + 5, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 14, @poolentrystart + 6, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 15, @poolentrystart + 7, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),

(@guidstart + 16, @poolentrystart + 8, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 17, @poolentrystart + 9, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 18, @poolentrystart + 10, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 19, @poolentrystart + 11, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 20, @poolentrystart + 8, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 21, @poolentrystart + 9, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 22, @poolentrystart + 10, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 23, @poolentrystart + 11, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),

(@guidstart + 24, @poolentrystart + 12, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 25, @poolentrystart + 13, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 26, @poolentrystart + 14, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 27, @poolentrystart + 15, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 28, @poolentrystart + 12, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 29, @poolentrystart + 13, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 30, @poolentrystart + 14, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 31, @poolentrystart + 15, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),

(@guidstart + 32, @poolentrystart + 16, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 33, @poolentrystart + 17, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 34, @poolentrystart + 18, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 35, @poolentrystart + 19, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 36, @poolentrystart + 16, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 37, @poolentrystart + 17, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 38, @poolentrystart + 18, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 39, @poolentrystart + 19, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),

(@guidstart + 40, @poolentrystart + 20, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 41, @poolentrystart + 21, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 42, @poolentrystart + 22, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 43, @poolentrystart + 23, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 44, @poolentrystart + 20, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 45, @poolentrystart + 21, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 46, @poolentrystart + 22, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 47, @poolentrystart + 23, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),

(@guidstart + 48, @poolentrystart + 24, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 49, @poolentrystart + 25, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 50, @poolentrystart + 26, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 51, @poolentrystart + 27, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 52, @poolentrystart + 24, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 53, @poolentrystart + 25, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 54, @poolentrystart + 26, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 55, @poolentrystart + 27, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),

(@guidstart + 56, @poolentrystart + 28, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 57, @poolentrystart + 29, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 58, @poolentrystart + 30, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 59, @poolentrystart + 31, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 60, @poolentrystart + 28, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 61, @poolentrystart + 29, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 62, @poolentrystart + 30, 50, 'AQ40 - Qiraji Mindslayer / Slayer'),
(@guidstart + 63, @poolentrystart + 31, 50, 'AQ40 - Qiraji Mindslayer / Slayer');