SET @POOL := 25407;

DELETE FROM `pool_template` WHERE `entry` BETWEEN @POOL + 0 AND @POOL + 36;
INSERT INTO `pool_template` (`entry`, `max_limit`, `description`) VALUES 
(@POOL + 0, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 1, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 2, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 3, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 4, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 5, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 6, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 7, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 8, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 9, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 10, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 11, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 12, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 13, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 14, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 15, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 16, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 17, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 18, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 19, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 20, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 21, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 22, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 23, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 24, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 25, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 26, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 27, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 28, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 29, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 30, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 31, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 32, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 33, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 34, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 35, 1, 'MC - Firelord / Lava Annihilator'),
(@POOL + 36, 1, 'MC - Firelord / Lava Annihilator');
