
UPDATE `quest_template` SET `rewmoneymaxlevel`='4980' WHERE `entry`='8578';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8584';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8585';
UPDATE `quest_template` SET `rewmoneymaxlevel`='5970' WHERE `entry`='8730';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3960' WHERE `entry`='8733';
UPDATE `quest_template` SET `rewmoneymaxlevel`='990' WHERE `entry`='8734';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1505';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='1558';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1638';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1639';
UPDATE `quest_template` SET `rewmoneymaxlevel`='126' WHERE `entry`='1640';
UPDATE `quest_template` SET `rewmoneymaxlevel`='252' WHERE `entry`='1665';
UPDATE `quest_template` SET `minlevel`='10', `rewmoneymaxlevel`='252' WHERE `entry`='1666';
UPDATE `quest_template` SET `questlevel`='11', `rewmoneymaxlevel`='660' WHERE `entry`='1678';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1679';
UPDATE `quest_template` SET `rewmoneymaxlevel`='54' WHERE `entry`='1680';
UPDATE `quest_template` SET `rewmoneymaxlevel`='375' WHERE `entry`='1682';
UPDATE `quest_template` SET `rewmoneymaxlevel`='510' WHERE `entry`='1683';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1684';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='1687';
UPDATE `quest_template` SET `rewmoneymaxlevel`='252' WHERE `entry`='1692';
UPDATE `quest_template` SET `rewmoneymaxlevel`='375' WHERE `entry`='1693';
UPDATE `quest_template` SET `rewmoneymaxlevel`='96' WHERE `entry`='1698';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='345' WHERE `entry`='1700';
UPDATE `quest_template` SET `rewmoneymaxlevel`='264' WHERE `entry`='1702';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='690' WHERE `entry`='1703';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='345' WHERE `entry`='1704';
UPDATE `quest_template` SET `minlevel`='20' WHERE `entry`='1705';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='1830' WHERE `entry`='1706';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='1050' WHERE `entry`='1708';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='1830' WHERE `entry`='1709';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='1110' WHERE `entry`='1710';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='1830' WHERE `entry`='1711';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1410' WHERE `entry`='1713';
UPDATE `quest_template` SET `rewmoneymaxlevel`='360' WHERE `entry`='1718';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1470' WHERE `entry`='1719';
UPDATE `quest_template` SET `rewmoneymaxlevel`='2340' WHERE `entry`='1792';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='1800';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1818';
UPDATE `quest_template` SET `rewmoneymaxlevel`='510' WHERE `entry`='1819';
UPDATE `quest_template` SET `rewmoneymaxlevel`='126' WHERE `entry`='1820';
UPDATE `quest_template` SET `rewmoneymaxlevel`='525' WHERE `entry`='1822';
UPDATE `quest_template` SET `rewmoneymaxlevel`='96' WHERE `entry`='1823';
UPDATE `quest_template` SET `rewmoneymaxlevel`='930' WHERE `entry`='1824';
UPDATE `quest_template` SET `rewmoneymaxlevel`='465' WHERE `entry`='1825';
UPDATE `quest_template` SET `rewmoneymaxlevel`='2190' WHERE `entry`='1838';
UPDATE `quest_template` SET `minlevel`='20' WHERE `entry`='1839';
UPDATE `quest_template` SET `minlevel`='20' WHERE `entry`='1840';
UPDATE `quest_template` SET `minlevel`='20', `requiredraces`='178' WHERE `entry`='1841';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='1110' WHERE `entry`='1847';
UPDATE `quest_template` SET `minlevel`='20' WHERE `entry`='1842';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='1110' WHERE `entry`='1843';
UPDATE `quest_template` SET `minlevel`='20' WHERE `entry`='1844';
UPDATE `quest_template` SET `minlevel`='20', `rewmoneymaxlevel`='1110' WHERE `entry`='1845';
UPDATE `quest_template` SET `minlevel`='20' WHERE `entry`='1846';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1830' WHERE `entry`='1848';
UPDATE `quest_template` SET `rewmoneymaxlevel`='252' WHERE `entry`='1860';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1879';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1881';
UPDATE `quest_template` SET `rewmoneymaxlevel`='51' WHERE `entry`='1883';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='1884';
UPDATE `quest_template` SET `rewmoneymaxlevel`='66' WHERE `entry`='1919';
UPDATE `quest_template` SET `rewmoneymaxlevel`='690' WHERE `entry`='1920';
UPDATE `quest_template` SET `questlevel`='15', `rewmoneymaxlevel`='480' WHERE `entry`='1921';
UPDATE `quest_template` SET `rewmoneymaxlevel`='480' WHERE `entry`='1961';
UPDATE `quest_template` SET `rewmoneymaxlevel`='630' WHERE `entry`='1939';
UPDATE `quest_template` SET `questlevel`='15', `rewmoneymaxlevel`='630' WHERE `entry`='1941';
UPDATE `quest_template` SET `questlevel`='26' WHERE `entry`='1942';
UPDATE `quest_template` SET `rewmoneymaxlevel`='126' WHERE `entry`='1943';
UPDATE `quest_template` SET `rewmoneymaxlevel`='174' WHERE `entry`='1947';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1890' WHERE `entry`='1948';
UPDATE `quest_template` SET `rewmoneymaxlevel`='870' WHERE `entry`='1949';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1110' WHERE `entry`='1950';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1890' WHERE `entry`='1951';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1890' WHERE `entry`='1952';
UPDATE `quest_template` SET `rewmoneymaxlevel`='192' WHERE `entry`='1953';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1410' WHERE `entry`='1954';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1410' WHERE `entry`='1955';
UPDATE `quest_template` SET `minlevel`='35', `rewmoneymaxlevel`='2340' WHERE `entry`='1956';
UPDATE `quest_template` SET `minlevel`='35', `rewmoneymaxlevel`='1410' WHERE `entry`='1957';
UPDATE `quest_template` SET `minlevel`='35', `rewmoneymaxlevel`='1890' WHERE `entry`='1958';
UPDATE `quest_template` SET `rewmoneymaxlevel`='66' WHERE `entry`='1959';
UPDATE `quest_template` SET `rewmoneymaxlevel`='690' WHERE `entry`='1960';
UPDATE `quest_template` SET `questlevel`='15', `rewmoneymaxlevel`='630' WHERE `entry`='1962';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='915';
UPDATE `quest_template` SET `minlevel`='10', `rewmoneymaxlevel`='390' WHERE `entry`='4822';
UPDATE `quest_template` SET `minlevel`='10', `rewmoneymaxlevel`='990' WHERE `entry`='171';
UPDATE `quest_template` SET `minlevel`='10', `rewmoneymaxlevel`='990' WHERE `entry`='5502';
UPDATE `quest_template` SET `minlevel`='30', `rewmoneymaxlevel`='3960' WHERE `entry`='8150';
UPDATE `quest_template` SET `minlevel`='30', `rewmoneymaxlevel`='3960' WHERE `entry`='8149';
UPDATE `quest_template` SET `rewmoneymaxlevel`='300' WHERE `entry`='8151';
UPDATE `quest_template` SET `rewmoneymaxlevel`='300' WHERE `entry`='8233';
UPDATE `quest_template` SET `rewmoneymaxlevel`='300' WHERE `entry`='8250';
UPDATE `quest_template` SET `rewmoneymaxlevel`='300' WHERE `entry`='8254';
UPDATE `quest_template` SET `minlevel`='51', `rewmoneymaxlevel`='4980' WHERE `entry`='8367';
UPDATE `quest_template` SET `minlevel`='51' WHERE `entry`='8388';
UPDATE `quest_template` SET `rewmoneymaxlevel`='870' WHERE `entry`='8368';
UPDATE `quest_template` SET `rewmoneymaxlevel`='435' WHERE `entry`='8389';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1410' WHERE `entry`='8426';
UPDATE `quest_template` SET `rewmoneymaxlevel`='720' WHERE `entry`='8431';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1800' WHERE `entry`='8427';
UPDATE `quest_template` SET `rewmoneymaxlevel`='900' WHERE `entry`='8432';
UPDATE `quest_template` SET `rewmoneymaxlevel`='2730' WHERE `entry`='8428';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1350' WHERE `entry`='8433';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3840' WHERE `entry`='8429';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1920' WHERE `entry`='8434';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3960' WHERE `entry`='8430';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1980' WHERE `entry`='8435';
UPDATE `quest_template` SET `rewmoneymaxlevel`='4980' WHERE `entry`='8369';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1980' WHERE `entry`='8436';
UPDATE `quest_template` SET `rewmoneymaxlevel`='2730' WHERE `entry`='8437';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3840' WHERE `entry`='8438';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3960' WHERE `entry`='8439';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1410' WHERE `entry`='8370';
UPDATE `quest_template` SET `rewmoneymaxlevel`='720' WHERE `entry`='8390';
UPDATE `quest_template` SET `rewmoneymaxlevel`='900' WHERE `entry`='8440';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1350' WHERE `entry`='8441';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1920' WHERE `entry`='8442';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1980' WHERE `entry`='8443';
UPDATE `quest_template` SET `minlevel`='51', `rewmoneymaxlevel`='4980' WHERE `entry`='8371';
UPDATE `quest_template` SET `minlevel`='51', `rewmoneymaxlevel`='3960' WHERE `entry`='8385';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3960' WHERE `entry`='8403';
UPDATE `quest_template` SET `rewmoneymaxlevel`='870' WHERE `entry`='8372';
UPDATE `quest_template` SET `rewmoneymaxlevel`='435' WHERE `entry`='8386';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1410' WHERE `entry`='8399';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1800' WHERE `entry`='8400';
UPDATE `quest_template` SET `rewmoneymaxlevel`='2730' WHERE `entry`='8401';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3840' WHERE `entry`='8402';
UPDATE `quest_template` SET `rewmoneymaxlevel`='720' WHERE `entry`='8404';
UPDATE `quest_template` SET `rewmoneymaxlevel`='900' WHERE `entry`='8405';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1350' WHERE `entry`='8406';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1920' WHERE `entry`='8407';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1980' WHERE `entry`='8408';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1410' WHERE `entry`='8374';
UPDATE `quest_template` SET `rewmoneymaxlevel`='720' WHERE `entry`='8384';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1800' WHERE `entry`='8393';
UPDATE `quest_template` SET `rewmoneymaxlevel`='900' WHERE `entry`='8391';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1350' WHERE `entry`='8392';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1920' WHERE `entry`='8397';
UPDATE `quest_template` SET `rewmoneymaxlevel`='1980' WHERE `entry`='8398';
UPDATE `quest_template` SET `rewmoneymaxlevel`='2730' WHERE `entry`='8394';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3840' WHERE `entry`='8395';
UPDATE `quest_template` SET `rewmoneymaxlevel`='3960' WHERE `entry`='8396';
UPDATE `quest_template` SET `questlevel`='50', `rewmoneymaxlevel`='2280' WHERE `entry`='8410';
UPDATE `quest_template` SET `questlevel`='50', `rewmoneymaxlevel`='300' WHERE `entry`='8415';
UPDATE `quest_template` SET `questlevel`='50', `rewmoneymaxlevel`='300' WHERE `entry`='8417';
UPDATE `quest_template` SET `rewmoneymaxlevel`='5970' WHERE `entry`='8446';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8619';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8635';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8636';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8642';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8643';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8644';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8645';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8646';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8647';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8648';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8649';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8650';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8651';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8652';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8653';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8654';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8670';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8671';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8672';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8673';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8674';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8675';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8676';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8677';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8678';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8679';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8680';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8681';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8682';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8683';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8684';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8685';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8686';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8688';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8713';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8714';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8715';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8716';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8717';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8718';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8719';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8720';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8721';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8722';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8723';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8724';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8725';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8726';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8727';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8866';
UPDATE `quest_template` SET `minlevel`='1', `questlevel`='1' WHERE `entry`='8744';
UPDATE `quest_template` SET `minlevel`='1', `questlevel`='1' WHERE `entry`='8767';
UPDATE `quest_template` SET `questlevel`='1' WHERE `entry`='8788';
UPDATE `quest_template` SET `questlevel`='20' WHERE `entry`='8768';
UPDATE `quest_template` SET `questlevel`='40' WHERE `entry`='8769';
UPDATE `quest_template` SET `questlevel`='10' WHERE `entry`='8803';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8811';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8812';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8813';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8814';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8815';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8816';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8817';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8818';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8830';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8832';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8834';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8836';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8838';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8840';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8842';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8844';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8822';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8823';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8824';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8825';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8826';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8831';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8833';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8835';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8837';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8839';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8841';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8843';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8845';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8819';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8820';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='8821';
UPDATE `quest_template` SET `questlevel`='1', `rewmoneymaxlevel`='6' WHERE `entry`='8828';
UPDATE `quest_template` SET `questlevel`='1', `rewmoneymaxlevel`='6' WHERE `entry`='8827';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='8846';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='8847';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='8848';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='8849';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='8850';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8867';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255', `rewmoneymaxlevel`='390' WHERE `entry`='8883';
UPDATE `quest_template` SET `rewmoneymaxlevel`='300' WHERE `entry`='9063';
