
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1110' WHERE `entry`='862';
UPDATE `quest_template` SET `minlevel`='9', `requiredraces`='255' WHERE `entry`='866';
UPDATE `quest_template` SET `requiredraces`='178' WHERE `entry`='972';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='495' WHERE `entry`='1094';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='660' WHERE `entry`='1095';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1530' WHERE `entry`='1740';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='360' WHERE `entry`='1758';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1470' WHERE `entry`='1795';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1890' WHERE `entry`='1799';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='360' WHERE `entry`='1801';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='810' WHERE `entry`='2381';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1170' WHERE `entry`='2478';
UPDATE `quest_template` SET `minlevel`='30', `requiredraces`='0', `RewMoneyMaxLevel`='252' WHERE `entry`='3526';
UPDATE `quest_template` SET `minlevel`='30', `requiredraces`='255', `RewMoneyMaxLevel`='252' WHERE `entry`='3633';
UPDATE `quest_template` SET `minlevel`='30', `questlevel`='47', `RewMoneyMaxLevel`='252' WHERE `entry`='3635';
UPDATE `quest_template` SET `minlevel`='30', `questlevel`='47', `requiredraces`='77', `RewMoneyMaxLevel`='252' WHERE `entry`='3634';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='252' WHERE `entry`='3632';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='252' WHERE `entry`='3637';
UPDATE `quest_template` SET `minlevel`='30', `questlevel`='47', `RewMoneyMaxLevel`='252' WHERE `entry`='3630';
UPDATE `quest_template` SET `minlevel`='30', `questlevel`='47', `RewMoneyMaxLevel`='252' WHERE `entry`='3629';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='4181';
UPDATE `quest_template` SET `minlevel`='30' WHERE `entry`='3644';
UPDATE `quest_template` SET `minlevel`='30' WHERE `entry`='3645';
UPDATE `quest_template` SET `minlevel`='30', `requiredraces`='255' WHERE `entry`='3646';
UPDATE `quest_template` SET `minlevel`='30' WHERE `entry`='3647';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='375' WHERE `entry`='4736';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='375' WHERE `entry`='4737';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='375' WHERE `entry`='4738';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='375' WHERE `entry`='4739';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='810' WHERE `entry`='4782';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='1796';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1260' WHERE `entry`='4784';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1710' WHERE `entry`='4783';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1200' WHERE `entry`='4781';
UPDATE `quest_template` SET `minlevel`='31', `requiredraces`='255' WHERE `entry`='4785';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2130' WHERE `entry`='4786';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1410' WHERE `entry`='4961';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1410' WHERE `entry`='4962';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1410' WHERE `entry`='4963';
UPDATE `quest_template` SET `minlevel`='35', `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='4964';
UPDATE `quest_template` SET `minlevel`='35', `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='4975';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='810' WHERE `entry`='4965';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='810' WHERE `entry`='4967';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='810' WHERE `entry`='4968';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='810' WHERE `entry`='4969';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='930' WHERE `entry`='4976';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='450' WHERE `entry`='6123';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='450' WHERE `entry`='6128';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='450' WHERE `entry`='6124';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='450' WHERE `entry`='6129';
