
UPDATE `quest_template` SET `RewMoneyMaxLevel`='720' WHERE `entry`='2622';
UPDATE `quest_template` SET `minlevel`='45', `questlevel`='58', `RewMoneyMaxLevel`='375' WHERE `entry`='3625';
UPDATE `quest_template` SET `minlevel`='45' WHERE `entry`='3626';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3060' WHERE `entry`='8423';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3060' WHERE `entry`='8424';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3810' WHERE `entry`='8425';
UPDATE `quest_template` SET `minlevel`='58', `questlevel`='60' WHERE `entry`='7483';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5130' WHERE `entry`='5081';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='6402';
UPDATE `quest_template` SET `minlevel`='60', `requiredraces`='178', `RewMoneyMaxLevel`='375' WHERE `entry`='7562';
UPDATE `quest_template` SET `minlevel`='60', `requiredraces`='255', `RewMoneyMaxLevel`='4650' WHERE `entry`='7563';
UPDATE `quest_template` SET `minlevel`='60', `requiredraces`='255', `RewMoneyMaxLevel`='1860' WHERE `entry`='7564';
UPDATE `quest_template` SET `minlevel`='60', `requiredraces`='255', `RewMoneyMaxLevel`='3720' WHERE `entry`='7623';
UPDATE `quest_template` SET `minlevel`='60', `requiredraces`='255', `RewMoneyMaxLevel`='3720' WHERE `entry`='7624';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7625';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7626';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7627';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7628';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7629';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7630';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='4230' WHERE `entry`='7631';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='216' WHERE `entry`='1599';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3106';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3107';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3108';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3109';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3110';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3112';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3113';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3114';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3115';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7881';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7882';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7883';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7884';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7885';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7889';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7890';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7891';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7892';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7893';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7894';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7895';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7896';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7897';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7898';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7899';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7900';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7901';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7902';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7903';
UPDATE `quest_template` SET `minlevel`='1', `questlevel`='55', `requiredraces`='255', `RewMoneyMaxLevel`='330' WHERE `entry`='7907';
UPDATE `quest_template` SET `minlevel`='1', `requiredraces`='255', `RewMoneyMaxLevel`='330' WHERE `entry`='7927';
UPDATE `quest_template` SET `minlevel`='1', `requiredraces`='255', `RewMoneyMaxLevel`='330' WHERE `entry`='7928';
UPDATE `quest_template` SET `minlevel`='1', `requiredraces`='255', `RewMoneyMaxLevel`='330' WHERE `entry`='7929';
UPDATE `quest_template` SET `minlevel`='6', `requiredraces`='255' WHERE `entry`='7930';
UPDATE `quest_template` SET `minlevel`='15', `requiredraces`='255' WHERE `entry`='7931';
UPDATE `quest_template` SET `minlevel`='30', `requiredraces`='255' WHERE `entry`='7932';
UPDATE `quest_template` SET `minlevel`='45', `requiredraces`='255' WHERE `entry`='7933';
UPDATE `quest_template` SET `minlevel`='6', `requiredraces`='255' WHERE `entry`='7934';
UPDATE `quest_template` SET `minlevel`='45', `requiredraces`='255' WHERE `entry`='7936';
UPDATE `quest_template` SET `minlevel`='25', `requiredraces`='255' WHERE `entry`='7935';
UPDATE `quest_template` SET `minlevel`='10', `requiredraces`='255', `RewMoneyMaxLevel`='390' WHERE `entry`='7937';
UPDATE `quest_template` SET `minlevel`='10', `requiredraces`='255', `RewMoneyMaxLevel`='390' WHERE `entry`='7938';
UPDATE `quest_template` SET `minlevel`='10', `requiredraces`='255', `RewMoneyMaxLevel`='390' WHERE `entry`='7944';
UPDATE `quest_template` SET `minlevel`='10', `requiredraces`='255', `RewMoneyMaxLevel`='390' WHERE `entry`='7945';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7939';
UPDATE `quest_template` SET `minlevel`='55', `requiredraces`='255' WHERE `entry`='7940';
UPDATE `quest_template` SET `minlevel`='55', `requiredraces`='255' WHERE `entry`='7981';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7941';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7942';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7943';
UPDATE `quest_template` SET `questlevel`='1', `requiredraces`='255' WHERE `entry`='7946';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8222';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8223';
