
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='968';
UPDATE `quest_template` SET `minlevel`='10', `RewMoneyMaxLevel`='276' WHERE `entry`='1579';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='1580';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='2178';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='27';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='26';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1440' WHERE `entry`='1198';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1530' WHERE `entry`='1199';
UPDATE `quest_template` SET `minlevel`='8', `RewMoneyMaxLevel`='810' WHERE `entry`='1582';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='345' WHERE `entry`='2260';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='2820' WHERE `entry`='3803';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5628';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5629';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5630';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5631';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5632';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5633';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5673';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5674';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5675';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5921';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5922';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='5923';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='5924';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='5925';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='5926';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='5927';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='5928';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6001';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6002';
UPDATE `quest_template` SET `questlevel`='14', `RewMoneyMaxLevel`='60' WHERE `entry`='6126';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='60' WHERE `entry`='6121';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178' WHERE `entry`='8360';
UPDATE `quest_template` SET `minlevel`='10', `questlevel`='60', `requiredraces`='77' WHERE `entry`='8357';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8870';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8871';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8872';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8873';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8874';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='8875';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='114' WHERE `entry`='1470';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3095';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3083';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3088';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3096';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3102';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3118';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3097';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3098';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3099';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='150' WHERE `entry`='3901';
UPDATE `quest_template` SET `questlevel`='1' WHERE `entry`='5421';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='2130' WHERE `entry`='5581';
UPDATE `quest_template` SET `minlevel`='30' WHERE `entry`='5821';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1680' WHERE `entry`='6143';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1680' WHERE `entry`='6161';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='375' WHERE `entry`='384';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='276' WHERE `entry`='1647';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='540' WHERE `entry`='1648';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='138' WHERE `entry`='1778';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='405' WHERE `entry`='1783';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='405' WHERE `entry`='1784';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='1785';
UPDATE `quest_template` SET `title`='Tome of Divinity', `RewMoneyMaxLevel`='54' WHERE `entry`='2999';
UPDATE `quest_template` SET `requiredraces`='4' WHERE `entry`='1789';
UPDATE `quest_template` SET `requiredraces`='1' WHERE `entry`='1790';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='2218';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='2298';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='2299';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='138' WHERE `entry`='2998';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='54' WHERE `entry`='2997';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='138' WHERE `entry`='3681';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='138' WHERE `entry`='3000';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='162' WHERE `entry`='5624';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='162' WHERE `entry`='5625';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='54' WHERE `entry`='5623';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='54' WHERE `entry`='5626';

