
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8947';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8951';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8952';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8953';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8954';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8955';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8956';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8957';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8958';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='8959';
UPDATE `quest_template` SET `minlevel`='58', `RewMoneyMaxLevel`='3960' WHERE `entry`='8970';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='1506';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='1522';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='1523';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='1524';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='540' WHERE `entry`='1525';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='1526';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='1527';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='2983';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='2984';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='1859';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='66' WHERE `entry`='2161';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='2380';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='162' WHERE `entry`='5648';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='162' WHERE `entry`='5621';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='162' WHERE `entry`='5650';
UPDATE `quest_template` SET `minlevel`='5' WHERE `entry`='5624';
UPDATE `quest_template` SET `minlevel`='5' WHERE `entry`='5625';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='54' WHERE `entry`='5649';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='54' WHERE `entry`='5651';
UPDATE `quest_template` SET `minlevel`='5', `RewMoneyMaxLevel`='54' WHERE `entry`='5622';
UPDATE `quest_template` SET `minlevel`='10', `questlevel`='10', `RewMoneyMaxLevel`='126' WHERE `entry`='5656';
UPDATE `quest_template` SET `minlevel`='10', `questlevel`='10', `RewMoneyMaxLevel`='126' WHERE `entry`='5657';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5654';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5655';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6064';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6084';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6085';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6063';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6101';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6102';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6061';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6087';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6088';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6062';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6082';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='510' WHERE `entry`='6083';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='6086';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='6103';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='6089';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='6081';
UPDATE `quest_template` SET `minlevel`='10', `questlevel`='60', `requiredraces`='77' WHERE `entry`='8355';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178' WHERE `entry`='8358';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='420' WHERE `entry`='1302';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='6607';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='5463';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5280' WHERE `entry`='5464';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='5521';
UPDATE `quest_template` SET `requiredraces`='178' WHERE `entry`='5524';
UPDATE `quest_template` SET `requiredraces`='178' WHERE `entry`='5504';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='5507';
UPDATE `quest_template` SET `minlevel`='56' WHERE `entry`='6144';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7621';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='5970' WHERE `entry`='7622';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='9128';
UPDATE `quest_template` SET `title`='Savage Flora' WHERE `entry`='9136';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9232';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9233';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9234';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9235';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9236';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9237';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9238';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9239';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9240';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9241';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9242';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9243';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9244';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9245';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='9246';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='0' WHERE `entry`='9229';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='0' WHERE `entry`='9230';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='54' WHERE `entry`='1646';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='54' WHERE `entry`='1642';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='276' WHERE `entry`='1643';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='540' WHERE `entry`='1644';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='138' WHERE `entry`='1780';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='405' WHERE `entry`='1786';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='405' WHERE `entry`='1787';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='1788';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='1685';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='2205';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='2281';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='2300';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='0' WHERE `entry`='4108';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='0' WHERE `entry`='4110';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='0' WHERE `entry`='4111';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='0' WHERE `entry`='4112';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='0' WHERE `entry`='4109';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='5156';
UPDATE `quest_template` SET `minlevel`='46' WHERE `entry`='6162';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3390' WHERE `entry`='7602';
UPDATE `quest_template` SET `minlevel`='50', `requiredraces`='255', `RewMoneyMaxLevel`='4230' WHERE `entry`='7603';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='5970' WHERE `entry`='7632';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7633';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='6540' WHERE `entry`='7634';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='5970' WHERE `entry`='7635';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='5970' WHERE `entry`='7636';
UPDATE `quest_template` SET `minlevel`='50', `questlevel`='52', `requiredraces`='255' WHERE `entry`='8420';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3060' WHERE `entry`='8421';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3810' WHERE `entry`='8422';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1170' WHERE `entry`='2847';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1170' WHERE `entry`='2854';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2848';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2855';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2849';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2856';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2850';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2857';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2851';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2858';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2852';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='1740' WHERE `entry`='2859';
UPDATE `quest_template` SET `minlevel`='30' WHERE `entry`='2853';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='2340' WHERE `entry`='2860';
UPDATE `quest_template` SET `questlevel`='47' WHERE `entry`='2939';
UPDATE `quest_template` SET `minlevel`='37' WHERE `entry`='2976';
UPDATE `quest_template` SET `minlevel`='39' WHERE `entry`='2982';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='282' WHERE `entry`='3788';
UPDATE `quest_template` SET `minlevel`='47', `RewMoneyMaxLevel`='2820' WHERE `entry`='3791';
UPDATE `quest_template` SET `minlevel`='47', `questlevel`='55', `RewMoneyMaxLevel`='330' WHERE `entry`='3792';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='3909';
UPDATE `quest_template` SET `questlevel`='55' WHERE `entry`='7726';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1320' WHERE `entry`='7738';
UPDATE `quest_template` SET `minlevel`='20' WHERE `entry`='540';
UPDATE `quest_template` SET `minlevel`='20', `RewMoneyMaxLevel`='2130' WHERE `entry`='542';
UPDATE `quest_template` SET `minlevel`='25' WHERE `entry`='563';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='1658';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='96' WHERE `entry`='2480';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1170' WHERE `entry`='6681';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='6701';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='7645';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='8249';
UPDATE `quest_template` SET `minlevel`='25', `questlevel`='60', `requiredraces`='77', `RewMoneyMaxLevel`='990' WHERE `entry`='8373';
UPDATE `quest_template` SET `questlevel`='50' WHERE `entry`='8411';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3060' WHERE `entry`='8412';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3810' WHERE `entry`='8413';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='2640' WHERE `entry`='2877';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1650' WHERE `entry`='971';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='264' WHERE `entry`='1442';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='1578';
UPDATE `quest_template` SET `minlevel`='1', `RewMoneyMaxLevel`='690' WHERE `entry`='1618';
UPDATE `quest_template` SET `questlevel`='22', `RewMoneyMaxLevel`='1320' WHERE `entry`='1654';
UPDATE `quest_template` SET `questlevel`='22' WHERE `entry`='1806';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='495' WHERE `entry`='1653';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='264' WHERE `entry`='1655';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='1715';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='1717';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1470' WHERE `entry`='1803';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1470' WHERE `entry`='1805';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1470' WHERE `entry`='1802';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1470' WHERE `entry`='1804';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1530' WHERE `entry`='2200';
UPDATE `quest_template` SET `minlevel`='37' WHERE `entry`='2361';
UPDATE `quest_template` SET `minlevel`='37' WHERE `entry`='2204';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='246' WHERE `entry`='2769';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='3630';
UPDATE `quest_template` SET `requiredraces`='178' WHERE `entry`='3637';
UPDATE `quest_template` SET `minlevel`='30', `requiredraces`='77', `RewMoneyMaxLevel`='252' WHERE `entry`='3642';
UPDATE `quest_template` SET `minlevel`='30', `requiredraces`='255', `RewMoneyMaxLevel`='252' WHERE `entry`='3638';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='3640';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1890' WHERE `entry`='3643';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1890' WHERE `entry`='3641';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1890' WHERE `entry`='3639';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='3644';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='3645';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='3647';
UPDATE `quest_template` SET `requiredraces`='178' WHERE `entry`='3526';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='3629';
UPDATE `quest_template` SET `requiredraces`='77' WHERE `entry`='4181';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1890' WHERE `entry`='5301';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1890' WHERE `entry`='5283';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1890' WHERE `entry`='5302';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1890' WHERE `entry`='5284';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5645';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5647';
UPDATE `quest_template` SET `minlevel`='35', `RewMoneyMaxLevel`='585' WHERE `entry`='6609';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='585' WHERE `entry`='6612';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='585' WHERE `entry`='6625';
UPDATE `quest_template` SET `minlevel`='10', `questlevel`='60' WHERE `entry`='7022';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='990' WHERE `entry`='7025';
UPDATE `quest_template` SET `questlevel`='60', `RewMoneyMaxLevel`='990' WHERE `entry`='7042';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178', `RewMoneyMaxLevel`='990' WHERE `entry`='6963';
UPDATE `quest_template` SET `questlevel`='60', `RewMoneyMaxLevel`='2970' WHERE `entry`='7045';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178', `RewMoneyMaxLevel`='2970' WHERE `entry`='6984';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='6964';
UPDATE `quest_template` SET `minlevel`='10', `RewMoneyMaxLevel`='390' WHERE `entry`='7062';
UPDATE `quest_template` SET `minlevel`='10', `RewMoneyMaxLevel`='390' WHERE `entry`='7061';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='7063';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='7639';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='7638';
UPDATE `quest_template` SET `minlevel`='10', `questlevel`='60', `requiredraces`='77' WHERE `entry`='8353';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178' WHERE `entry`='8354';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178', `RewMoneyMaxLevel`='2970' WHERE `entry`='8746';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='77', `RewMoneyMaxLevel`='2970' WHERE `entry`='8762';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='77' WHERE `entry`='8763';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178' WHERE `entry`='8799';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6068';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6069';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6070';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6065';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6066';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6067';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6071';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6072';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6073';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6722';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6074';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6075';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='6076';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='525' WHERE `entry`='28';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='525' WHERE `entry`='29';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='525' WHERE `entry`='30';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='525' WHERE `entry`='272';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='31';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='5061';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='5929';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='252' WHERE `entry`='5930';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='5931';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='51' WHERE `entry`='5932';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='450' WHERE `entry`='6122';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='585' WHERE `entry`='6125';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='585' WHERE `entry`='6130';
UPDATE `quest_template` SET `title`='The Principal Source', `RewMoneyMaxLevel`='450' WHERE `entry`='6127';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8862';
UPDATE `quest_template` SET `questlevel`='50', `requiredraces`='255' WHERE `entry`='8863';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8864';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8865';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='8868';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8876';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8877';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8878';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8879';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8880';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8881';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='255' WHERE `entry`='8882';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='216' WHERE `entry`='1598';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3100';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3101';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3103';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3085';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3119';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='2383';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3065';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3091';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3116';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3086';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3104';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3090';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3105';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='192' WHERE `entry`='1061';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='525' WHERE `entry`='1501';
UPDATE `quest_template` SET `requiredraces`='178', `RewMoneyMaxLevel`='96' WHERE `entry`='1716';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='96' WHERE `entry`='1472';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='96' WHERE `entry`='1507';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='1508';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='1509';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='465' WHERE `entry`='1510';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='930' WHERE `entry`='1511';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='1512';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='1689';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='1471';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='1474';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='1513';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='1739';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='1515';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='276' WHERE `entry`='1858';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='405' WHERE `entry`='1963';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='2382';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='690' WHERE `entry`='2458';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='96' WHERE `entry`='2460';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='630' WHERE `entry`='2479';
UPDATE `quest_template` SET `requiredraces`='178', `RewMoneyMaxLevel`='1530' WHERE `entry`='2751';
UPDATE `quest_template` SET `requiredraces`='178', `RewMoneyMaxLevel`='1530' WHERE `entry`='2752';
UPDATE `quest_template` SET `minlevel`='32', `requiredraces`='178', `RewMoneyMaxLevel`='1680' WHERE `entry`='2753';
UPDATE `quest_template` SET `minlevel`='32', `requiredraces`='178' WHERE `entry`='2754';
UPDATE `quest_template` SET `minlevel`='32', `requiredraces`='178', `RewMoneyMaxLevel`='168' WHERE `entry`='2755';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1890' WHERE `entry`='2756';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='930' WHERE `entry`='2757';
UPDATE `quest_template` SET `questlevel`='35' WHERE `entry`='2950';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='360' WHERE `entry`='2996';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='360' WHERE `entry`='1798';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='360' WHERE `entry`='3001';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='0' WHERE `entry`='4002';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='6540' WHERE `entry`='4974';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5642';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5643';
UPDATE `quest_template` SET `minlevel`='35', `RewMoneyMaxLevel`='585' WHERE `entry`='6608';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='585' WHERE `entry`='6623';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='585' WHERE `entry`='6611';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='7024';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='6961';
UPDATE `quest_template` SET `minlevel`='10', `questlevel`='60' WHERE `entry`='7021';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178', `RewMoneyMaxLevel`='990' WHERE `entry`='6962';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='2970' WHERE `entry`='7667';
UPDATE `quest_template` SET `minlevel`='58' WHERE `entry`='7666';
UPDATE `quest_template` SET `minlevel`='10', `requiredraces`='77', `RewMoneyMaxLevel`='990' WHERE `entry`='8311';
UPDATE `quest_template` SET `minlevel`='10', `requiredraces`='178', `RewMoneyMaxLevel`='990' WHERE `entry`='8312';
UPDATE `quest_template` SET `minlevel`='10', `questlevel`='60', `requiredraces`='77' WHERE `entry`='8356';
UPDATE `quest_template` SET `questlevel`='60', `requiredraces`='178' WHERE `entry`='8359';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3117';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3120';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7785';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='6540' WHERE `entry`='7786';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='6540' WHERE `entry`='7787';
UPDATE `quest_template` SET `questlevel`='58' WHERE `entry`='8282';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8288';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1800' WHERE `entry`='8307';
UPDATE `quest_template` SET `minlevel`='54', `requiredraces`='255', `RewMoneyMaxLevel`='3600' WHERE `entry`='8313';
UPDATE `quest_template` SET `title`='Unraveling the Mystery' WHERE `entry`='8314';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8316';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8376';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8377';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8378';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8379';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8380';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8381';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='8382';
UPDATE `quest_template` SET `minlevel`='54', `requiredraces`='255', `RewMoneyMaxLevel`='1800' WHERE `entry`='8317';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='8363';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='2100' WHERE `entry`='8364';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='8497';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='8498';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='8501';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='8502';
UPDATE `quest_template` SET `minlevel`='60' WHERE `entry`='8805';
UPDATE `quest_template` SET `minlevel`='60', `questlevel`='60' WHERE `entry`='8806';
UPDATE `quest_template` SET `minlevel`='60' WHERE `entry`='8807';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='0' WHERE `entry`='428';
UPDATE `quest_template` SET `minlevel`='10' WHERE `entry`='429';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='525' WHERE `entry`='438';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='102' WHERE `entry`='1085';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='495' WHERE `entry`='1070';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='495' WHERE `entry`='1074';
UPDATE `quest_template` SET `questlevel`='22' WHERE `entry`='1082';
UPDATE `quest_template` SET `questlevel`='20', `RewMoneyMaxLevel`='234' WHERE `entry`='1649';
UPDATE `quest_template` SET `questlevel`='23', `RewMoneyMaxLevel`='1110' WHERE `entry`='1650';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='600' WHERE `entry`='1651';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1530' WHERE `entry`='1652';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='192' WHERE `entry`='4485';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='192' WHERE `entry`='4486';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='375' WHERE `entry`='1688';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='375' WHERE `entry`='1471';
UPDATE `quest_template` SET `requiredraces`='77', `RewMoneyMaxLevel`='465' WHERE `entry`='1716';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='930' WHERE `entry`='1738';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='2360';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5635';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5636';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5637';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5639';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5676';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5677';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='7637';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='7640';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='390' WHERE `entry`='7641';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='990' WHERE `entry`='7642';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='2970' WHERE `entry`='7643';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1980' WHERE `entry`='7646';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='5970' WHERE `entry`='7647';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='7648';
UPDATE `quest_template` SET `minlevel`='60' WHERE `entry`='7666';
UPDATE `quest_template` SET `minlevel`='1' WHERE `entry`='619';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1890' WHERE `entry`='2760';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='2761';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='2762';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='2763';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='1740' WHERE `entry`='2764';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='2765';
UPDATE `quest_template` SET `minlevel`='20' WHERE `entry`='2843';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='4260' WHERE `entry`='3721';
UPDATE `quest_template` SET `minlevel`='40' WHERE `entry`='8552';
UPDATE `quest_template` SET `minlevel`='40', `questlevel`='50' WHERE `entry`='8553';
UPDATE `quest_template` SET `minlevel`='40', `questlevel`='50' WHERE `entry`='8554';
UPDATE `quest_template` SET `minlevel`='30' WHERE `entry`='9259';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2520' WHERE `entry`='3512';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7581';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7582';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3960' WHERE `entry`='7583';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='2771';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='2772';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='2773';
UPDATE `quest_template` SET `minlevel`='40', `requiredraces`='255' WHERE `entry`='2882';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='282' WHERE `entry`='2967';
UPDATE `quest_template` SET `questlevel`='47' WHERE `entry`='3022';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='2340' WHERE `entry`='6610';
UPDATE `quest_template` SET `minlevel`='40', `RewMoneyMaxLevel`='3720' WHERE `entry`='8181';
UPDATE `quest_template` SET `minlevel`='6' WHERE `entry`='952';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='2259';
UPDATE `quest_template` SET `minlevel`='5' WHERE `entry`='2520';
UPDATE `quest_template` SET `questlevel`='8' WHERE `entry`='2541';
UPDATE `quest_template` SET `minlevel`='1', `requiredraces`='77', `RewMoneyMaxLevel`='375' WHERE `entry`='4161';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1470' WHERE `entry`='1531';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1470' WHERE `entry`='1532';
UPDATE `quest_template` SET `minlevel`='25' WHERE `entry`='1160';
UPDATE `quest_template` SET `minlevel`='13' WHERE `entry`='1064';
UPDATE `quest_template` SET `minlevel`='47', `questlevel`='55' WHERE `entry`='3804';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='1953';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='1478';
UPDATE `quest_template` SET `requiredraces`='178' WHERE `entry`='1657';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='1885';
UPDATE `quest_template` SET `minlevel`='30', `RewMoneyMaxLevel`='990' WHERE `entry`='8322';
UPDATE `quest_template` SET `minlevel`='25', `RewMoneyMaxLevel`='990' WHERE `entry`='8409';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='930' WHERE `entry`='1476';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='375' WHERE `entry`='1473';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='930' WHERE `entry`='1474';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='405' WHERE `entry`='1886';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='138' WHERE `entry`='1898';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='138' WHERE `entry`='1899';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='525' WHERE `entry`='1998';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='930' WHERE `entry`='1999';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='72' WHERE `entry`='2378';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5644';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='234' WHERE `entry`='5646';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5660';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5661';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5662';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='126' WHERE `entry`='5663';
UPDATE `quest_template` SET `questlevel`='53' WHERE `entry`='4144';
UPDATE `quest_template` SET `minlevel`='47' WHERE `entry`='4146';
UPDATE `quest_template` SET `minlevel`='50' WHERE `entry`='4492';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3060' WHERE `entry`='9051';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3060' WHERE `entry`='9052';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='3810' WHERE `entry`='9053';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3087';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3089';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3082';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='24' WHERE `entry`='3084';
UPDATE `quest_template` SET `minlevel`='51' WHERE `entry`='4984';
UPDATE `quest_template` SET `requiredraces`='178' WHERE `entry`='5511';
UPDATE `quest_template` SET `minlevel`='52' WHERE `entry`='5848';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='6186';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3960' WHERE `entry`='6569';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='2970' WHERE `entry`='6570';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3060' WHERE `entry`='8414';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1530' WHERE `entry`='8416';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3810' WHERE `entry`='8418';
UPDATE `quest_template` SET `minlevel`='0' WHERE `entry`='117';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1170' WHERE `entry`='2359';
UPDATE `quest_template` SET `minlevel`='25' WHERE `entry`='637';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='3390' WHERE `entry`='978';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='1800' WHERE `entry`='979';
UPDATE `quest_template` SET `questlevel`='50' WHERE `entry`='5067';
UPDATE `quest_template` SET `minlevel`='55' WHERE `entry`='5126';
UPDATE `quest_template` SET `RewMoneyMaxLevel`='4980' WHERE `entry`='5127';
UPDATE `quest_template` SET `questlevel`='60' WHERE `entry`='5161';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='4980' WHERE `entry`='5305';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='4980' WHERE `entry`='8869';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='5130' WHERE `entry`='5306';
UPDATE `quest_template` SET `requiredraces`='255', `RewMoneyMaxLevel`='5130' WHERE `entry`='5307';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7652';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7653';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7654';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7655';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7656';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7657';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7658';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='7659';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='8789';
UPDATE `quest_template` SET `requiredraces`='255' WHERE `entry`='8790';

