
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='4991';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='1908';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='2179';
UPDATE `item_template` SET `Material`='2', `sheath`='4' WHERE `entry`='5258';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='2559';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='5300';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='1983';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1910';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='3346';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='11542';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='5288';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='9659';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='5303';
UPDATE `item_template` SET `Material`='2', `InventoryType`='17', `sheath`='1' WHERE `entry`='5293';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10617';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10612';
UPDATE `item_template` SET `Material`='2', `sheath`='4' WHERE `entry`='5262';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='2180';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='1984';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5281';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='5291';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5278';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='2552';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13222';
UPDATE `item_template` SET `class`='4', `subclass`='0', `Material`='2', `sheath`='7' WHERE `entry`='13221';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='12934';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12933';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='2182';
UPDATE `item_template` SET `class`='4', `subclass`='0', `Material`='2', `sheath`='7' WHERE `entry`='13219';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='3494';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='11506';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='2177';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5284';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='12403';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12868';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='6618';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='3361';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12932';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='13312';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='3432';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12882';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='12950';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='11763';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12523';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12742';
UPDATE `item_template` SET `subclass`='8', `Material`='1', `sheath`='1' WHERE `entry`='12949';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='1906';
UPDATE `item_template` SET `class`='4', `subclass`='0', `Material`='1' WHERE `entry`='12855';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12751';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='1907';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1905';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='2714';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12298';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10616';
UPDATE `item_template` SET `class`='4', `subclass`='0', `Material`='1' WHERE `entry`='12861';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12959';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='21465';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='21794';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='21796';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12746';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='18122';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13723';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13698';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='5746';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10614';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='15910';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='2176';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='3433';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='5870';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='13632';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='12063';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1899';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12980';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='1903';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='3351';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='3362';
UPDATE `item_template` SET `class`='4', `subclass`='0', `Material`='2' WHERE `entry`='13605';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12748';
UPDATE `item_template` SET `class`='4', `subclass`='0', `Material`='1' WHERE `entry`='12863';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='13631';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10619';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1897';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='11424';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12993';
UPDATE `item_template` SET `Material`='2', `sheath`='4' WHERE `entry`='14118';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13061';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='18293';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10611';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='2052';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='2704';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='2183';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='17383';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5286';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='1985';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='14527';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='5287';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='6224';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='13316';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='14618';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='14837';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13705';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='18123';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12285';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='13150';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13050';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='11383';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='5597';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='2717';
UPDATE `item_template` SET `class`='4', `subclass`='0', `Material`='2', `InventoryType`='23', `sheath`='7' WHERE `entry`='3757';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12889';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='19404';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='6680';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='5304';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='5277';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12297';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12304';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='12788';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10825';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12331';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12755';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12338';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='2023';
UPDATE `item_template` SET `Material`='2', `sheath`='4' WHERE `entry`='13147';
UPDATE `item_template` SET `subclass`='14', `Material`='1', `sheath`='7' WHERE `entry`='6227';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='5276';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1896';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1909';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1900';
UPDATE `item_template` SET `Material`='1', `sheath`='5' WHERE `entry`='2551';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='2184';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1895';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='2051';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5285';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='1904';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='2711';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='3326';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='2197';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='3350';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='3367';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='2557';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='2827';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='1957';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12937';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='1117';
UPDATE `item_template` SET `Material`='2', `sheath`='4' WHERE `entry`='5260';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='2196';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='1901';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='2809';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='2053';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='1911';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='5745';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='10685';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='5289';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='3774';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='2081';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2200';
UPDATE `item_template` SET `Material`='2', `sheath`='4' WHERE `entry`='2550';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='1961';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12890';
UPDATE `item_template` SET `subclass`='8', `Material`='1', `sheath`='1' WHERE `entry`='11087';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12850';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2201';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2703';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='2202';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2705';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2198';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5305';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='23583';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='22724';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='22738';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='23582';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='22709';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='14873';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13750';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='13708';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='11322';
UPDATE `item_template` SET `Material`='2', `sheath`='4' WHERE `entry`='5261';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='2147';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='13160';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='22199';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='13623';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='23356';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='2181';
UPDATE `item_template` SET `subclass`='8', `Material`='1', `sheath`='1' WHERE `entry`='21553';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2199';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='14642';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12745';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='5301';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='2813';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5280';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='2178';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='2695';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='4993';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='11019';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `sheath`='7' WHERE `entry`='4994';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='3697';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='2' WHERE `entry`='3699';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='11343';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `sheath`='3' WHERE `entry`='5532';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='2810';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2707';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `sheath`='7' WHERE `entry`='2718';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `sheath`='7' WHERE `entry`='19485';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='6233';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='2884';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='12786';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12454';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12750';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12322';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13722';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13104';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='11342';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='12883';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13721';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='19053';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13611';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12862';
UPDATE `item_template` SET `Material`='4' WHERE `entry`='22596';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13406';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10613';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='10756';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='2558';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='20417';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='14882';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='32731';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12893';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='18983';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12902';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='11586';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='5491';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='3698';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12332';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='6232';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='13339';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='20468';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='23328';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='11587';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='22341';
UPDATE `item_template` SET `Material`='2', `sheath`='4' WHERE `entry`='14105';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='5598';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12629';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='13720';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='14823';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='13706';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13610';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12860';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='2', `sheath`='2' WHERE `entry`='3368';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `sheath`='7' WHERE `entry`='2716';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12452';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12329';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='1902';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13854';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='3695';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10898';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='14533';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='13925';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='12901';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='14706';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='14836';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='14534';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13627';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12995';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='18167';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='18166';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='6254';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='13319';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='15460';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12951';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='13924';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='18062';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13753';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12328';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13292';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13293';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='23369';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12981';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='18419';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='18596';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='18644';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='14643';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13609';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='19916';
UPDATE `item_template` SET `class`='4', `subclass`='0', `Material`='1' WHERE `entry`='19917';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='21551';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='21573';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='11323';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `InventoryType`='13' WHERE `entry`='12856';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='13628';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='10591';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='21564';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='21572';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='21554';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='21555';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='20412';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13337';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='14879';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='14870';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='21549';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='17283';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12294';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12944';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='12787';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12290';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='23743';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13069';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='22210';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='22211';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='22215';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='22213';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12456';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='14824';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='11369';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13622';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13718';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13707';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='21286';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='21192';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12869';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='21129';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='17942';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `InventoryType`='13', `sheath`='7' WHERE `entry`='6228';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12754';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='21122';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='12870';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13709';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='14475';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='21123';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13078';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='21121';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='14881';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='20738';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12851';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12857';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13336';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='20718';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='20719';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='11041';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='12453';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='14874';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='17282';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `InventoryType`='13' WHERE `entry`='13861';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='19988';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='19980';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `InventoryType`='22' WHERE `entry`='12747';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='2', `InventoryType`='13', `sheath`='3' WHERE `entry`='13607';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='19763';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='19762';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12854';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12858';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='19623';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='11314';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='18002';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='14586';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='17463';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='2', `sheath`='3' WHERE `entry`='12801';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12867';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='19214';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `InventoryType`='13', `sheath`='7' WHERE `entry`='6229';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='3694';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='6234';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='21580';
UPDATE `item_template` SET `subclass`='0', `Material`='1', `sheath`='3' WHERE `entry`='19014';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='18985';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12859';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13859';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13606';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='13894';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10618';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='17462';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='14877';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='17382';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12991';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='14893';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='11589';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13625';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='11021';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12593';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='13630';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='11042';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13165';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='11317';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='17482';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='11762';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='143';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2706';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2708';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2709';
UPDATE `item_template` SET `entry`='2710', `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='2710';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='3364';
UPDATE `item_template` SET `subclass`='8', `Material`='1', `sheath`='1' WHERE `entry`='3366';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='2' WHERE `entry`='3696';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='3756';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='5292';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='5495';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5502';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='5599';
UPDATE `item_template` SET `Material`='1', `sheath`='7' WHERE `entry`='5600';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='5747';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `sheath`='7' WHERE `entry`='6225';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='6230';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='6231';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='6235';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='6236';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='6237';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='6322';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='6334';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='6434';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='7612';
UPDATE `item_template` SET `subclass`='5', `Material`='2', `sheath`='1' WHERE `entry`='7706';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='2' WHERE `entry`='9700';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='2' WHERE `entry`='9701';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='2' WHERE `entry`='9702';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='10568';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10615';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='10878';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='11025';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='11264';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='11321';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='11365';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='11585';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='11588';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='11591';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12142';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12182';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='12183';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='12348';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12421';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12461';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12482';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12502';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12591';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12743';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12744';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12749';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12852';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12864';
UPDATE `item_template` SET `Material`='1' WHERE `entry`='12865';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1' WHERE `entry`='12866';
UPDATE `item_template` SET `Material`='1', `sheath`='1' WHERE `entry`='12892';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='12941';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='12943';
UPDATE `item_template` SET `Material`='2', `sheath`='7' WHERE `entry`='13220';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13290';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13341';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13407';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13504';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13604';
UPDATE `item_template` SET `class`='2', `subclass`='14', `Material`='1', `sheath`='7' WHERE `entry`='13612';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='13629';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='13719';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='13751';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='13814';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='13855';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='13922';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='14082';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='14084';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='14092';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='14532';
UPDATE `item_template` SET `Material`='1', `sheath`='2' WHERE `entry`='14535';
UPDATE `item_template` SET `Material`='2', `sheath`='3' WHERE `entry`='14575';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='14707';
UPDATE `item_template` SET `Material`='2', `sheath`='1' WHERE `entry`='14820';
UPDATE `item_template` SET `Material`='2', `sheath`='2' WHERE `entry`='14845';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='14875';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='14880';
UPDATE `item_template` SET `Material`='2' WHERE `entry`='16582';
UPDATE `item_template` SET `Material`='1', `sheath`='3' WHERE `entry`='17123';
UPDATE `item_template` SET `Material`='1', `sheath`='4' WHERE `entry`='25818';
UPDATE `item_template` SET `AllowableClass`='-1', `AllowableRace`='-1' WHERE `entry`='2715';
