
UPDATE `creature_template` SET `healthmultiplier`='3', `armormultiplier`='1' WHERE `Entry`='15177';
UPDATE `creature_template` SET `healthmultiplier`='3', `armormultiplier`='1' WHERE `Entry`='15178';
UPDATE `creature_template` SET `healthmultiplier`='3', `armormultiplier`='1' WHERE `Entry`='16227';
UPDATE `creature_template` SET `healthmultiplier`='3', `armormultiplier`='1' WHERE `Entry`='10583';
UPDATE `creature_template` SET `rank`='0', `healthmultiplier`='1.15', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2835';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='13177';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='12740';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='10897';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='11138';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='11139';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='11899';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='11900';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='11901';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='12577';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='12578';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='12596';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='12616';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='12617';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='12636';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='10378';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2851';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2858';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2859';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2861';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2941';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2995';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='3305';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='3310';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='3615';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='3838';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='3841';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='4267';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='4312';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='4314';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='4317';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='4319';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='4321';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='4407';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='4551';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='6026';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='6706';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='6726';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='7823';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='7824';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='8018';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='8019';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='8020';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='8609';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='8610';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='1387';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='1571';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='1572';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='1573';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2226';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2299';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2389';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2409';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='2432';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='352';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='523';
UPDATE `creature_template` SET `healthmultiplier`='3', `powermultiplier`='3', `armormultiplier`='1' WHERE `Entry`='931';
