-- Add trainer greetings for 455 trainers.
DELETE FROM trainer_greeting WHERE 1;
INSERT INTO trainer_greeting VALUES
(198, 'Hello, mage!  Ready for some training?'),
(328, 'Hello, mage!  Ready for some training?'),
(331, 'Hello, mage!  Ready for some training?'),
(375, 'Hello, priest!  Ready for some training?'),
(376, 'Hello, priest!  Ready for some training?'),
(377, 'Hello, priest!  Ready for some training?'),
(459, 'Hello, warlock! Ready for some training?'),
(460, 'Hello, warlock! Ready for some training?'),
(461, 'Hello, warlock! Ready for some training?'),
(514, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(543, ''),
(812, 'Searching for herbs requires both knowledge and instinct.'),
(837, 'Hello, priest!  Ready for some training?'),
(895, 'Hello, hunter!  Ready for some training?'),
(906, 'Hello, warlock! Ready for some training?'),
(908, 'Searching for herbs requires both knowledge and instinct.'),
(911, 'Hello, warrior!  Ready for some training?'),
(912, 'Hello, warrior!  Ready for some training?'),
(913, 'Hello, warrior!  Ready for some training?'),
(914, 'Hello, warrior!  Ready for some training?'),
(915, 'Hello, rogue!  Ready for some training?'),
(916, 'Hello, rogue!  Ready for some training?'),
(917, 'Hello, rogue!  Ready for some training?'),
(918, 'Hello, rogue!  Ready for some training?'),
(925, 'Hello, paladin!  Ready for some training?'),
(926, 'Hello, paladin!  Ready for some training?'),
(927, 'Hello, paladin!  Ready for some training?'),
(928, 'Hello, paladin!  Ready for some training?'),
(944, 'Hello, mage!  Ready for some training?'),
(985, 'Hello, warrior!  Ready for some training?'),
(986, 'Hello, shaman!  Ready for some training?'),
(987, 'Hello, hunter!  Ready for some training?'),
(988, 'Hello, warlock! Ready for some training?'),
(1103, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(1215, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(1218, 'Searching for herbs requires both knowledge and instinct.'),
(1226, 'Hello, priest!  Ready for some training?'),
(1228, 'Hello, mage!  Ready for some training?'),
(1229, 'Hello, warrior!  Ready for some training?'),
(1231, 'Hello, hunter!  Ready for some training?'),
(1232, 'Hello, paladin!  Ready for some training?'),
(1234, 'Hello, rogue!  Ready for some training?'),
(1241, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(1292, 'It requires a steady hand to remove the leather from a slain beast.'),
(1300, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(1317, 'Enchanting is the art of improving existing items through magic. '),
(1346, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(1355, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(1382, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(1385, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(1386, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(1404, 'Hello, hunter!  Ready for some training?'),
(1411, 'Hello, rogue!  Ready for some training?'),
(1430, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(1458, 'Searching for herbs requires both knowledge and instinct.'),
(1470, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(1473, 'Searching for herbs requires both knowledge and instinct.'),
(1632, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(1651, 'I can teach you how to use a fishing pole to catch fish.'),
(1676, 'Engineering is very simple once you grasp the basics.'),
(1680, 'I can teach you how to use a fishing pole to catch fish.'),
(1681, 'You have not lived until you have dug deep into the earth.'),
(1683, 'I can teach you how to use a fishing pole to catch fish.'),
(1699, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(1700, 'I can teach you how to use a fishing pole to catch fish.'),
(1701, 'You have not lived until you have dug deep into the earth.'),
(1702, 'Engineering is very simple once you grasp the basics.'),
(1703, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(1901, 'Hello, warrior!  Ready for some training?'),
(2114, 'Searching for herbs requires both knowledge and instinct.'),
(2119, 'Hello, warrior!  Ready for some training?'),
(2122, 'Hello, rogue!  Ready for some training?'),
(2123, 'Hello, priest!  Ready for some training?'),
(2124, 'Hello, mage!  Ready for some training?'),
(2126, 'Hello, warlock! Ready for some training?'),
(2127, 'Hello, warlock! Ready for some training?'),
(2128, 'Hello, mage!  Ready for some training?'),
(2129, 'Hello, priest!  Ready for some training?'),
(2130, 'Hello, rogue!  Ready for some training?'),
(2131, 'Hello, warrior!  Ready for some training?'),
(2132, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(2326, 'Here, let me show you how to bind those wounds....'),
(2327, 'Here, let me show you how to bind those wounds....'),
(2329, 'Here, let me show you how to bind those wounds....'),
(2367, 'I can teach you how to use a fishing pole to catch fish.'),
(2390, 'Searching for herbs requires both knowledge and instinct.'),
(2391, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(2399, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(2485, 'Welcome!'),
(2489, 'Welcome!'),
(2492, 'Welcome!'),
(2627, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(2704, ''),
(2798, 'Here, let me show you how to bind those wounds....'),
(2818, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(2834, 'I can teach you how to use a fishing pole to catch fish.'),
(2836, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(2837, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(2855, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(2856, 'Searching for herbs requires both knowledge and instinct.'),
(2878, ''),
(2879, ''),
(2998, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(3001, 'You have not lived until you have dug deep into the earth.'),
(3004, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(3007, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(3009, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(3011, 'Enchanting is the art of improving existing items through magic. '),
(3013, 'Searching for herbs requires both knowledge and instinct.'),
(3026, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(3028, 'I can teach you how to use a fishing pole to catch fish.'),
(3030, 'Hello, shaman!  Ready for some training?'),
(3031, 'Hello, shaman!  Ready for some training?'),
(3032, 'Hello, shaman!  Ready for some training?'),
(3033, 'Hello, druid!  Ready for some training?'),
(3034, 'Hello, druid!  Ready for some training?'),
(3036, 'Hello, druid!  Ready for some training?'),
(3038, 'Hello, hunter!  Ready for some training?'),
(3039, 'Hello, hunter!  Ready for some training?'),
(3040, 'Hello, hunter!  Ready for some training?'),
(3041, 'Hello, warrior!  Ready for some training?'),
(3042, 'Hello, warrior!  Ready for some training?'),
(3043, 'Hello, warrior!  Ready for some training?'),
(3044, 'Hello, priest!  Ready for some training?'),
(3045, 'Hello, priest!  Ready for some training?'),
(3046, 'Hello, priest!  Ready for some training?'),
(3047, 'Hello, mage!  Ready for some training?'),
(3048, 'Hello, mage!  Ready for some training?'),
(3049, 'Hello, mage!  Ready for some training?'),
(3059, 'Hello, warrior!  Ready for some training?'),
(3060, 'Hello, druid!  Ready for some training?'),
(3061, 'Hello, hunter!  Ready for some training?'),
(3062, 'Hello, shaman!  Ready for some training?'),
(3063, 'Hello, warrior!  Ready for some training?'),
(3064, 'Hello, druid!  Ready for some training?'),
(3065, 'Hello, hunter!  Ready for some training?'),
(3066, 'Hello, shaman!  Ready for some training?'),
(3067, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(3069, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(3087, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(3136, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(3137, 'You have not lived until you have dug deep into the earth.'),
(3153, 'Hello, warrior!  Ready for some training?'),
(3154, 'Hello, hunter!  Ready for some training?'),
(3155, 'Hello, rogue!  Ready for some training?'),
(3156, 'Hello, warlock! Ready for some training?'),
(3157, 'Hello, shaman!  Ready for some training?'),
(3169, 'Hello, warrior!  Ready for some training?'),
(3170, 'Hello, rogue!  Ready for some training?'),
(3171, 'Hello, hunter!  Ready for some training?'),
(3172, 'Hello, warlock! Ready for some training?'),
(3173, 'Hello, shaman!  Ready for some training?'),
(3174, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(3175, 'You have not lived until you have dug deep into the earth.'),
(3179, 'I can teach you how to use a fishing pole to catch fish.'),
(3181, 'Here, let me show you how to bind those wounds....'),
(3184, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(3185, 'Searching for herbs requires both knowledge and instinct.'),
(3290, 'Engineering is very simple once you grasp the basics.'),
(3306, ''),
(3324, 'Hello, warlock! Ready for some training?'),
(3325, 'Hello, warlock! Ready for some training?'),
(3326, 'Hello, warlock! Ready for some training?'),
(3327, 'Hello, rogue!  Ready for some training?'),
(3328, 'Hello, rogue!  Ready for some training?'),
(3332, 'I can teach you how to use a fishing pole to catch fish.'),
(3344, 'Hello, shaman!  Ready for some training?'),
(3345, 'Enchanting is the art of improving existing items through magic. '),
(3347, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(3352, 'Hello, hunter!  Ready for some training?'),
(3353, 'Hello, warrior!  Ready for some training?'),
(3354, 'Hello, warrior!  Ready for some training?'),
(3355, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(3357, 'You have not lived until you have dug deep into the earth.'),
(3363, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(3365, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(3373, 'Here, let me show you how to bind those wounds....'),
(3399, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(3401, 'Hello, rogue!  Ready for some training?'),
(3403, 'Hello, shaman!  Ready for some training?'),
(3404, 'Searching for herbs requires both knowledge and instinct.'),
(3406, 'Hello, hunter!  Ready for some training?'),
(3407, 'Hello, hunter!  Ready for some training?'),
(3408, 'Hello, warrior!  Ready for some training?'),
(3478, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(3484, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(3494, 'Engineering is very simple once you grasp the basics.'),
(3523, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(3545, ''),
(3549, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(3555, 'You have not lived until you have dug deep into the earth.'),
(3557, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(3593, 'Hello, warrior!  Ready for some training?'),
(3594, 'Hello, rogue!  Ready for some training?'),
(3595, 'Hello, priest!  Ready for some training?'),
(3596, 'Hello, hunter!  Ready for some training?'),
(3597, 'Hello, druid!  Ready for some training?'),
(3598, 'Hello, warrior!  Ready for some training?'),
(3599, 'Hello, rogue!  Ready for some training?'),
(3600, 'Hello, priest!  Ready for some training?'),
(3601, 'Hello, hunter!  Ready for some training?'),
(3602, 'Hello, druid!  Ready for some training?'),
(3603, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(3604, 'Searching for herbs requires both knowledge and instinct.'),
(3605, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(3606, 'Enchanting is the art of improving existing items through magic. '),
(3607, 'I can teach you how to use a fishing pole to catch fish.'),
(3620, ''),
(3622, ''),
(3624, ''),
(3688, ''),
(3690, 'Hello!  Can I teach you something?'),
(3698, ''),
(3703, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(3704, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(3706, 'Hello, priest!  Ready for some training?'),
(3707, 'Hello, priest!  Ready for some training?'),
(3963, 'Hello, hunter!  Ready for some training?'),
(3964, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(3965, 'Searching for herbs requires both knowledge and instinct.'),
(3967, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(4087, 'Hello, warrior!  Ready for some training?'),
(4089, 'Hello, warrior!  Ready for some training?'),
(4090, 'Hello, priest!  Ready for some training?'),
(4091, 'Hello, priest!  Ready for some training?'),
(4092, 'Hello, priest!  Ready for some training?'),
(4138, 'Hello, hunter!  Ready for some training?'),
(4146, 'Hello, hunter!  Ready for some training?'),
(4156, 'I can teach you how to use a fishing pole to catch fish.'),
(4159, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(4160, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(4163, 'Hello, rogue!  Ready for some training?'),
(4165, 'Welcome!'),
(4193, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(4204, 'Searching for herbs requires both knowledge and instinct.'),
(4205, 'Hello, hunter!  Ready for some training?'),
(4210, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(4211, 'Here, let me show you how to bind those wounds....'),
(4212, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(4213, 'Enchanting is the art of improving existing items through magic. '),
(4214, 'Hello, rogue!  Ready for some training?'),
(4215, 'Hello, rogue!  Ready for some training?'),
(4217, 'Hello, druid!  Ready for some training?'),
(4218, 'Hello, druid!  Ready for some training?'),
(4219, 'Hello, druid!  Ready for some training?'),
(4254, 'You have not lived until you have dug deep into the earth.'),
(4258, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(4320, '');
INSERT INTO trainer_greeting VALUES
(4552, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(4563, 'Hello, warlock! Ready for some training?'),
(4564, 'Hello, warlock! Ready for some training?'),
(4565, 'Hello, warlock! Ready for some training?'),
(4566, 'Hello, mage!  Ready for some training?'),
(4567, 'Hello, mage!  Ready for some training?'),
(4568, 'Hello, mage!  Ready for some training?'),
(4573, 'I can teach you how to use a fishing pole to catch fish.'),
(4576, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(4578, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(4582, 'Hello, rogue!  Ready for some training?'),
(4583, 'Hello, rogue!  Ready for some training?'),
(4584, 'Hello, rogue!  Ready for some training?'),
(4588, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(4591, 'Here, let me show you how to bind those wounds....'),
(4593, 'Hello, warrior!  Ready for some training?'),
(4594, 'Hello, warrior!  Ready for some training?'),
(4595, 'Hello, warrior!  Ready for some training?'),
(4596, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(4598, 'You have not lived until you have dug deep into the earth.'),
(4606, 'Hello, priest!  Ready for some training?'),
(4607, 'Hello, priest!  Ready for some training?'),
(4608, 'Hello, priest!  Ready for some training?'),
(4611, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(4614, 'Searching for herbs requires both knowledge and instinct.'),
(4616, 'Enchanting is the art of improving existing items through magic. '),
(4732, 'Hello!  Can I teach you something?'),
(4752, 'Hello!  Can I teach you something?'),
(4753, 'Hello!  Can I teach you something?'),
(4772, 'Hello!  Can I teach you something?'),
(4773, 'Hello!  Can I teach you something?'),
(4898, 'Searching for herbs requires both knowledge and instinct.'),
(4900, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(5032, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(5037, 'Engineering is very simple once you grasp the basics.'),
(5038, 'Enchanting is the art of improving existing items through magic. '),
(5040, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(5041, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(5113, 'Hello, warrior!  Ready for some training?'),
(5114, 'Hello, warrior!  Ready for some training?'),
(5115, 'Hello, hunter!  Ready for some training?'),
(5116, 'Hello, hunter!  Ready for some training?'),
(5117, 'Hello, hunter!  Ready for some training?'),
(5127, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(5137, 'Searching for herbs requires both knowledge and instinct.'),
(5141, 'Hello, priest!  Ready for some training?'),
(5142, 'Hello, priest!  Ready for some training?'),
(5143, 'Hello, priest!  Ready for some training?'),
(5144, 'Hello, mage!  Ready for some training?'),
(5145, 'Hello, mage!  Ready for some training?'),
(5146, 'Hello, mage!  Ready for some training?'),
(5147, 'Hello, paladin!  Ready for some training?'),
(5148, 'Hello, paladin!  Ready for some training?'),
(5149, 'Hello, paladin!  Ready for some training?'),
(5150, 'Here, let me show you how to bind those wounds....'),
(5153, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(5157, 'Enchanting is the art of improving existing items through magic. '),
(5159, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(5161, 'I can teach you how to use a fishing pole to catch fish.'),
(5164, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(5165, 'Hello, rogue!  Ready for some training?'),
(5166, 'Hello, rogue!  Ready for some training?'),
(5167, 'Hello, rogue!  Ready for some training?'),
(5171, 'Hello, warlock! Ready for some training?'),
(5172, 'Hello, warlock! Ready for some training?'),
(5173, 'Hello, warlock! Ready for some training?'),
(5174, 'Engineering is very simple once you grasp the basics.'),
(5177, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(5392, 'You have not lived until you have dug deep into the earth.'),
(5479, 'Hello, warrior!  Ready for some training?'),
(5480, 'Hello, warrior!  Ready for some training?'),
(5482, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(5484, 'Hello, priest!  Ready for some training?'),
(5489, 'Hello, priest!  Ready for some training?'),
(5491, 'Hello, paladin!  Ready for some training?'),
(5492, 'Hello, paladin!  Ready for some training?'),
(5493, 'I can teach you how to use a fishing pole to catch fish.'),
(5495, 'Hello, warlock! Ready for some training?'),
(5496, 'Hello, warlock! Ready for some training?'),
(5497, 'Hello, mage!  Ready for some training?'),
(5498, 'Hello, mage!  Ready for some training?'),
(5499, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(5501, 'Hello, hunter!  Ready for some training?'),
(5502, 'Searching for herbs requires both knowledge and instinct.'),
(5504, 'Hello, druid!  Ready for some training?'),
(5505, 'Hello, druid!  Ready for some training?'),
(5506, 'Hello, druid!  Ready for some training?'),
(5511, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(5513, 'You have not lived until you have dug deep into the earth.'),
(5515, 'Hello, hunter!  Ready for some training?'),
(5516, 'Hello, hunter!  Ready for some training?'),
(5517, 'Hello, hunter!  Ready for some training?'),
(5518, 'Engineering is very simple once you grasp the basics.'),
(5564, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(5566, 'Searching for herbs requires both knowledge and instinct.'),
(5612, 'Hello, warlock! Ready for some training?'),
(5690, 'I can teach you how to use a fishing pole to catch fish.'),
(5695, 'Enchanting is the art of improving existing items through magic. '),
(5759, 'Here, let me show you how to bind those wounds....'),
(5784, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(5880, 'Hello, mage!  Ready for some training?'),
(5882, 'Hello, mage!  Ready for some training?'),
(5883, 'Hello, mage!  Ready for some training?'),
(5884, 'Hello, mage!  Ready for some training?'),
(5885, 'Hello, mage!  Ready for some training?'),
(5938, 'I can teach you how to use a fishing pole to catch fish.'),
(5939, 'Here, let me show you how to bind those wounds....'),
(5941, 'I can teach you how to use a fishing pole to catch fish.'),
(5943, 'Here, let me show you how to bind those wounds....'),
(5957, 'Welcome!'),
(5958, 'Welcome!'),
(5994, 'Hello, priest!  Ready for some training?'),
(6014, 'Hello, priest!  Ready for some training?'),
(6018, 'Hello, priest!  Ready for some training?'),
(6094, 'Here, let me show you how to bind those wounds....'),
(6251, 'Hello, warlock!  Ready for some training?'),
(6286, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(6287, 'It requires a steady hand to remove the leather from a slain beast.'),
(6288, 'It requires a steady hand to remove the leather from a slain beast.'),
(6289, 'It requires a steady hand to remove the leather from a slain beast.'),
(6290, 'It requires a steady hand to remove the leather from a slain beast.'),
(6291, 'It requires a steady hand to remove the leather from a slain beast.'),
(6292, 'It requires a steady hand to remove the leather from a slain beast.'),
(6295, 'It requires a steady hand to remove the leather from a slain beast.'),
(6297, 'You have not lived until you have dug deep into the earth.'),
(6299, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(6306, 'It requires a steady hand to remove the leather from a slain beast.'),
(6387, 'It requires a steady hand to remove the leather from a slain beast.'),
(6707, 'Hello, rogue!  Ready for some training?'),
(7087, 'It requires a steady hand to remove the leather from a slain beast.'),
(7088, 'It requires a steady hand to remove the leather from a slain beast.'),
(7089, 'It requires a steady hand to remove the leather from a slain beast.'),
(7230, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(7231, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(7232, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(7311, 'Hello, mage!  Ready for some training?'),
(7312, 'Hello, mage!  Ready for some training?'),
(7315, 'Hello, warrior!  Ready for some training?'),
(7406, 'Engineering is very simple once you grasp the basics.'),
(7866, 'Greetings! Can I teach you how to turn beast hides into armor?'),
(7867, 'Greetings! Can I teach you how to turn beast hides into armor?'),
(7868, 'Greetings! Can I teach you how to turn beast hides into armor?'),
(7869, 'Greetings! Can I teach you how to turn beast hides into armor?'),
(7870, 'Greetings! Can I teach you how to turn beast hides into armor?'),
(7871, 'Greetings! Can I teach you how to turn beast hides into armor?'),
(7944, 'Engineering is very simple once you grasp the basics.'),
(7946, 'I can teach you how to use a fishing pole to catch fish.'),
(7948, 'With alchemy you can turn found herbs into healing and other types of potions.'),
(7949, 'Enchanting is the art of improving existing items through magic. '),
(7953, 'Hello!  Can I teach you something?'),
(7954, 'Hello!  Can I teach you something?'),
(8126, 'Engineering is very simple once you grasp the basics.'),
(8128, 'You have not lived until you have dug deep into the earth.'),
(8140, 'Hello, paladin!  Ready for some training?'),
(8141, 'Hello, warrior!  Ready for some training?'),
(8142, 'Hello, druid!  Ready for some training?'),
(8144, 'It requires a steady hand to remove the leather from a slain beast.'),
(8146, 'Searching for herbs requires both knowledge and instinct.'),
(8153, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(8306, 'Can I teach you how to turn the meat you find on beasts into a feast?'),
(8308, 'Hello, hunter!  Ready for some training?'),
(8736, 'Engineering is very simple once you grasp the basics.'),
(8738, 'Engineering is very simple once you grasp the basics.'),
(9465, 'Hello, druid!  Ready for some training?'),
(9584, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(10086, ''),
(10088, ''),
(10089, ''),
(10090, ''),
(10930, 'Hello, hunter!  Ready for some training?'),
(10993, 'Engineering is very simple once you grasp the basics.'),
(11017, 'Engineering is very simple once you grasp the basics.'),
(11025, 'Engineering is very simple once you grasp the basics.'),
(11031, 'Engineering is very simple once you grasp the basics.'),
(11037, 'Engineering is very simple once you grasp the basics.'),
(11048, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(11050, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(11051, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(11052, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(11072, 'Enchanting is the art of improving existing items through magic. '),
(11073, 'Enchanting is the art of improving existing items through magic. '),
(11074, 'Enchanting is the art of improving existing items through magic. '),
(11097, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(11098, 'Greetings!  Can I teach you how to turn beast hides into armor?'),
(11146, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(11177, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(11178, 'Care to learn how to turn the ore that you find into weapons and metal armor?'),
(11397, 'Hello, priest!  Ready for some training?'),
(11401, 'Hello, priest!  Ready for some training?'),
(11406, 'Hello, priest!  Ready for some training?'),
(11557, 'Greetings!  Can I teach you how to turn found cloth into cloth armor?'),
(11865, ''),
(11866, ''),
(11867, ''),
(11868, ''),
(11869, ''),
(11870, ''),
(12025, 'Searching for herbs requires both knowledge and instinct.'),
(12030, 'It requires a steady hand to remove the leather from a slain beast.'),
(12032, 'I can teach you how to use a fishing pole to catch fish.'),
(12042, 'Hello, druid!  Ready for some training?'),
(12961, 'I can teach you how to use a fishing pole to catch fish.'),
(13084, ''),
(13283, 'Hello, rogue!  Ready for some training?'),
(13417, 'Hello, shaman!  Ready for some training?'),
(14740, 'I can teach you how to use a fishing pole to catch fish.');
