-- name pool 1-103
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 96;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47392;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 527558;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 1;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 21269;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47368;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47406;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 2;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 21268;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47383;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 50327;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 3;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 21264;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47371;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47387;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 4;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 479;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 485;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 35505;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 5;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 21247;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47366;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 50329;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 6;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 21244;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47379;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47516;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 7;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 21243;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47525;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 50328;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 8;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 502;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 21242;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47397;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 9;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 21241;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47385;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47523;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 10;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 21238;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47367;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47384;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 11;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 536;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 21225;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47405;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 12;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 543;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 21224;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47520;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 13;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 553;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 554;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 21223;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 14;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 559;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 21222;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47524;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 15;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 581;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 618;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 21221;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 16;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 622;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 20877;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47521;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 17;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 624;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 639;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 35482;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 18;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 11173;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18185;
UPDATE `pool_template` SET `description` = 'Dustwallow Marsh - Fishing Pool' WHERE `entry` = 19;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 11169;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50334;
UPDATE `pool_template` SET `description` = 'Dustwallow Marsh - Fishing Pool' WHERE `entry` = 20;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 11168;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 50336;
UPDATE `pool_template` SET `description` = 'Dustwallow Marsh - Fishing Pool' WHERE `entry` = 21;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 20857;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47381;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47401;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 22;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18206;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 32561;
UPDATE `pool_template` SET `description` = 'Desolace - Fishing Pool' WHERE `entry` = 23;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 649;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 676;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 20827;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 24;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 20826;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47380;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47522;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 25;
UPDATE `pool_gameobject` SET `description` = 'Greater Sagefish School' WHERE `guid` = 35466;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 50345;
UPDATE `pool_template` SET `description` = 'Alterac Mountains - Fishing Pool' WHERE `entry` = 26;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 698;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 706;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 20823;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 27;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 708;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 713;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 20821;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 28;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 722;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 20819;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47400;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 29;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 724;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 20804;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47375;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 30;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 725;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 20803;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47390;
UPDATE `pool_template` SET `description` = 'Hillsbrad Foothills - Fishing Pool' WHERE `entry` = 31;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18146;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47329;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47510;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 47548;
UPDATE `pool_template` SET `description` = 'Stranglethorn Vale - Fishing Pool' WHERE `entry` = 32;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 726;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 732;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 35453;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 33;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 733;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 738;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 35441;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 34;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 751;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 767;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 35439;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 35;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 776;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 807;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 35438;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 36;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18147;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47336;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 64517;
UPDATE `pool_template` SET `description` = 'Stranglethorn Vale - Fishing Pool' WHERE `entry` = 37;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 18071;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18123;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 18227;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 49900;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 38;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18066;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 18082;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 50180;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 39;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 18083;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 49910;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 40;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 808;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18165;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47369;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 41;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 811;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 14722;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18172;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 42;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 822;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 823;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18169;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 43;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18189;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 20377;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47418;
UPDATE `pool_template` SET `description` = 'Dustwallow Marsh - Fishing Pool' WHERE `entry` = 44;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18181;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 20339;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47424;
UPDATE `pool_template` SET `description` = 'Dustwallow Marsh - Fishing Pool' WHERE `entry` = 45;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 18213;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47417;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47538;
UPDATE `pool_template` SET `description` = 'Dustwallow Marsh - Fishing Pool' WHERE `entry` = 46;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 18279;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 49911;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 50265;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 47;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18128;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 18232;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50277;
UPDATE `pool_template` SET `description` = 'Tanaris - Fishing Pool' WHERE `entry` = 48;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 18086;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 18284;
UPDATE `pool_template` SET `description` = 'Azshara - Fishing Pool' WHERE `entry` = 49;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 18282;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 49912;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50308;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 50;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 840;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 841;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 35429;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 51;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 846;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 854;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 35428;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 52;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 861;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 865;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 35426;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 53;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 872;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 873;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 35425;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 54;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 874;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 875;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 35424;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 55;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 894;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 897;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 35423;
UPDATE `pool_template` SET `description` = 'Silverpine Forest - Fishing Pool' WHERE `entry` = 56;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 17356;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 30712;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 49908;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 57;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 17357;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 17891;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 49915;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 58;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18062;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 49913;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 50263;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 59;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18063;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 50182;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 60;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18125;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 49906;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50259;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 61;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18105;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 50178;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50261;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 50311;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 62;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18107;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 50181;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 63;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 898;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 18157;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 47517;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 64;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 899;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 915;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18144;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 65;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18109;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 49901;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 66;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18111;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 33285;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 49902;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 67;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18117;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 49904;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 68;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18118;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 49903;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 50264;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 69;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18120;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 18629;
UPDATE `pool_template` SET `description` = 'Tanaris - Fishing Pool' WHERE `entry` = 70;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 916;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18145;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 50306;
UPDATE `pool_template` SET `description` = 'Darkshore - Fishing Pool' WHERE `entry` = 71;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18121;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 50184;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 72;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 919;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 13429;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 18151;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 73;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 936;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 13422;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 18153;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 74;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 952;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18139;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 18154;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 75;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18064;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 50179;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 76;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18065;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 49909;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 50301;
UPDATE `pool_template` SET `description` = 'Feralas - Fishing Pool' WHERE `entry` = 77;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 18069;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 18070;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 50298;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 50303;
UPDATE `pool_template` SET `description` = 'Tanaris - Fishing Pool' WHERE `entry` = 78;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 12053;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 18148;
UPDATE `pool_template` SET `description` = 'Stranglethorn Vale - Fishing Pool' WHERE `entry` = 79;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 17250;
UPDATE `pool_gameobject` SET `description` = 'Stonescale Eel Swarm' WHERE `guid` = 18631;
UPDATE `pool_template` SET `description` = 'Tanaris - Fishing Pool' WHERE `entry` = 80;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18149;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47326;
UPDATE `pool_template` SET `description` = 'Stranglethorn Vale - Fishing Pool' WHERE `entry` = 81;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 961;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 14903;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50332;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 82;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 964;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 14902;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 47391;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 83;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 17247;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 18127;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50262;
UPDATE `pool_template` SET `description` = 'Tanaris - Fishing Pool' WHERE `entry` = 84;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 965;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 973;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 14852;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 85;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 977;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 985;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 14627;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 86;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 986;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 988;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 14626;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 87;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 989;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 1012;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 14625;
UPDATE `pool_template` SET `description` = 'Wetlands - Fishing Pool' WHERE `entry` = 88;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 15708;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50276;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 89;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 15707;
UPDATE `pool_gameobject` SET `description` = 'Firefin Snapper School' WHERE `guid` = 50335;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 90;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 1048;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 14778;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 50267;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 91;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1124;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 1188;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 13432;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 92;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1431;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 1438;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 13431;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 93;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1441;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 1442;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 13430;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 94;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1457;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 1461;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 13421;
UPDATE `pool_template` SET `description` = 'The Barrens - Fishing Pool' WHERE `entry` = 95;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 1465;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1466;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 12782;
UPDATE `pool_template` SET `description` = 'Loch Modan - Fishing Pool' WHERE `entry` = 96;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 1477;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1489;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 12780;
UPDATE `pool_template` SET `description` = 'Loch Modan - Fishing Pool' WHERE `entry` = 97;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 1492;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1526;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 12778;
UPDATE `pool_template` SET `description` = 'Loch Modan - Fishing Pool' WHERE `entry` = 98;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 1604;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1605;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 12775;
UPDATE `pool_template` SET `description` = 'Loch Modan - Fishing Pool' WHERE `entry` = 99;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 1611;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1617;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 12774;
UPDATE `pool_template` SET `description` = 'Loch Modan - Fishing Pool' WHERE `entry` = 100;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 1618;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1619;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 12773;
UPDATE `pool_template` SET `description` = 'Loch Modan - Fishing Pool' WHERE `entry` = 101;
UPDATE `pool_gameobject` SET `description` = 'Oily Blackmouth School' WHERE `guid` = 1624;
UPDATE `pool_gameobject` SET `description` = 'Floating Debris' WHERE `guid` = 1635;
UPDATE `pool_gameobject` SET `description` = 'Sagefish School' WHERE `guid` = 12770;
UPDATE `pool_template` SET `description` = 'Loch Modan - Fishing Pool' WHERE `entry` = 102;
UPDATE `pool_gameobject` SET `description` = 'Greater Sagefish School' WHERE `guid` = 33211;
UPDATE `pool_gameobject` SET `description` = 'Floating Wreckage' WHERE `guid` = 47461;
UPDATE `pool_template` SET `description` = 'Alterac Mountains - Fishing Pool' WHERE `entry` = 103;
