UPDATE creature_movement_template SET waittime=1 WHERE entry=7607 AND point=16;
UPDATE creature_movement_template SET waittime=1 WHERE entry=10430 AND point=13;
UPDATE creature_movement_template SET waittime=1 WHERE entry=9022 AND point=3;
UPDATE creature_movement_template SET waittime=1 WHERE entry=9679 AND point=5;
UPDATE creature_movement_template SET waittime=1 WHERE entry=11492 AND point=2;
UPDATE creature_movement_template SET waittime=1 WHERE entry=14325 AND point=25;
UPDATE creature_movement_template SET waittime=1 WHERE entry=14351 AND point=14;
UPDATE creature_movement_template SET waittime=1 WHERE entry=14566 AND point=29;
UPDATE creature_movement_template SET waittime=1 WHERE entry=13996 AND point=15 AND pathId=0;
UPDATE creature_movement_template SET waittime=1 WHERE entry=13996 AND point=13 AND pathId=1;
