UPDATE dbscript_string SET content_default="Lovely song, isn't it?", broadcast_text_id=11089 WHERE entry=2000000009;
UPDATE dbscript_string SET content_default="Spirits of Water, I give you praise, and I beg of you a favor. You have heard $N's pleas, and I trust $ghis:her; intent is noble. Please, will you aid us?", broadcast_text_id=6586 WHERE entry=2000000057;
UPDATE dbscript_string SET content_default="Follow me, good Paladin.  I'll have your barding done faster than I could down a Dwarven stout.  Mmmm... stout.", broadcast_text_id=9776 WHERE entry=2000000063;
UPDATE dbscript_string SET content_default="Hear ye, denizens of Tanaris! Let it be known that $N is an exalted member of the Mithril Order. A blacksmith of honor, dedication, and infinite patience. Three cheers for $N!", broadcast_text_id=4365 WHERE entry=2000000076;
UPDATE dbscript_string SET content_default="%s takes a big swig of ale.", broadcast_text_id=1857 WHERE entry=2000000116;
UPDATE dbscript_string SET content_default="The invisibility liquor is ready for you, $n.", broadcast_text_id=1853 WHERE entry=2000000134;
UPDATE dbscript_string SET content_default="Oomph!  Here's another load of supplies, Harlan.  It must be selling fast!", broadcast_text_id=260 WHERE entry=2000000146;
UPDATE dbscript_string SET content_default="Ah, much appreciated, Corbett.  We'll get these on the racks immediately.", broadcast_text_id=261 WHERE entry=2000000148;
UPDATE dbscript_string SET content_default="Well, I'm off then.  Take care, Harlan.", broadcast_text_id=263 WHERE entry=2000000150;
UPDATE dbscript_string SET content_default="Good day, Elling!  Hullo Elaine!  Let me have a wheel of bleu cheese, eh?", broadcast_text_id=284 WHERE entry=2000000153;
UPDATE dbscript_string SET content_default="I shall use the time wisely, milord. Thank you.", broadcast_text_id=3791 WHERE entry=2000000177;
UPDATE dbscript_string SET content_default="Rouse and to arms, citizens of Darkshire! An abomination of the undead approaches along the road!", broadcast_text_id=89 WHERE entry=2000000186;
UPDATE dbscript_string SET content_default="The beast is slain! All's well in Darkshire!", broadcast_text_id=93 WHERE entry=2000000188;
UPDATE dbscript_string SET content_default="We most definitely do not need anymore attention drawn to us, stranger. Return to those that sent you in search of the lost master and tell them that nothing could be found. When this is done - and I will know when it is so - return and I shall reveal the secrets of the deceased.", broadcast_text_id=9448 WHERE entry=2000000198;
UPDATE dbscript_string SET content_default="What... what is this? Could this be the answer to my prayers? Elune has granted me a weapon--this scythe--to defeat the demons.", broadcast_text_id=1358 WHERE entry=2000000240;
UPDATE dbscript_string SET content_default="Come, $N. The lake is just around the bend.", broadcast_text_id=10866 WHERE entry=2000000375;
UPDATE dbscript_string SET content_default="Remulos, old friend. It is good to see you once more. I knew that the message would find its way to you - one way or another.", broadcast_text_id=10869 WHERE entry=2000000378;
UPDATE dbscript_string SET content_default="I fear for the worst, old friend. Within the Dream we fight a new foe, born of an ancient evil. Ysera's noble brood has fallen victim to the old whisperings. It seems as if the Nightmare has broken through the realm and seeks a new host on Azeroth.", broadcast_text_id=10871 WHERE entry=2000000380;
UPDATE dbscript_string SET content_default="You have been gone too long, Malfurion. Peace between the children of Azeroth is tenuous at best. What of my father? Of your brother? Have you any news?", broadcast_text_id=10874 WHERE entry=2000000383;
UPDATE dbscript_string SET content_default="Cenarius fights at my side. Illidan sits atop his throne in the Outland - brooding. I am afraid that the loss to Arthas proved to be his breaking point. Madness has embraced him, Remulos. He replays the events in his mind a thousand times per day, but in his mind, he is the victor and Arthas is utterly defeated. He is too far gone, old friend. I fear that the time may soon come that our bond is tested and it will not be as it was at the Well in Zin-Azshari. ", broadcast_text_id=10876 WHERE entry=2000000384;
UPDATE dbscript_string SET content_default="Time for the Gizleton Caravan to head on out! We'll be back soon but if you cannot wait, head north to Kormek's Hut. We open shop in about an hour.", broadcast_text_id=7506 WHERE entry=2000000402; -- Typo in Gizleton instead of Gizelton is intended as it is present in Blizzard broadcast texts
UPDATE dbscript_string SET content_default="Feralas: A History... Hmmmm... Let me examine this for a moment.", broadcast_text_id=4039 WHERE entry=2000000523;
UPDATE dbscript_string SET content_default="They will live, if only to see the fruits of their labor: the destruction and chaos that will surely ensue as the legion of Blackrock invade the gorge.", broadcast_text_id=4461 WHERE entry=2000000531;
UPDATE dbscript_string SET content_default="And might I add, that dress is lovely! You must tell me where you got it from.", broadcast_text_id=12144 WHERE entry=2000000642;
UPDATE dbscript_string SET content_default="NO! Shhhh! Just shut up. Goretooth is coming!", broadcast_text_id=4668 WHERE entry=2000000652;
UPDATE dbscript_string SET broadcast_text_id=4669 WHERE entry=2000000653;
UPDATE dbscript_string SET broadcast_text_id=4695 WHERE entry=2000000667;
UPDATE dbscript_string SET content_default="That is wonderous, Rimblat! Even this foul, sundered earth is not beyond healing.", broadcast_text_id=11945 WHERE entry=2000000671;
UPDATE dbscript_string SET content_default="Klaven doesn't pay me enough to deal with zombies, drones, or whatever he calls 'em.", broadcast_text_id=4018 WHERE entry=2000000795;
UPDATE dbscript_string SET content_default="Your discs are now ready!  Engage the Discs of Norgannon once again to retrieve them!", broadcast_text_id=3743 WHERE entry=2000000818;
UPDATE dbscript_string SET content_default="It was the will of Ragnaros that Obsidion be built. Obsidion will destroy the Blackrock orcs of Blackrock Spire, uniting us with our bretheren in the fiery depths.", broadcast_text_id=4397 WHERE entry=2000001340;
UPDATE dbscript_string SET content_default="%s's laughter trails off...", broadcast_text_id=4399 WHERE entry=2000001342;
UPDATE dbscript_string SET content_default="You know there are crocilisks in the Canals. They were brought from the swamp as pets, but got thrown in the canals.", broadcast_text_id=156 WHERE entry=2000001907;
UPDATE dbscript_string SET content_default="This is unforseen.  The being who enchanted this is known to me...", broadcast_text_id=516 WHERE entry=2000002028;
UPDATE dbscript_string SET content_default="Bijou lost! SQUAWK! *cough*", broadcast_text_id=5541 WHERE entry=2000005002;
UPDATE dbscript_string SET content_default="They all go to the Spire but none ever come back... just like Bijou.", broadcast_text_id=5544 WHERE entry=2000005006;
UPDATE dbscript_string SET content_default="Ah, this must be him now... no?  Bah!", broadcast_text_id=5960 WHERE entry=2000005018;
UPDATE dbscript_string SET content_default="Our oldest clutch of dragons are still far from maturity, but with patience and study, we are confident the dragonflight will soon be ready.", broadcast_text_id=7191 WHERE entry=2000005029;
UPDATE dbscript_string SET content_default="And then the Tauren said, '13 INCHES!'", broadcast_text_id=6405 WHERE entry=2000005032;
UPDATE dbscript_string SET content_default="Gimme my dolly!!", broadcast_text_id=694 WHERE entry=2000005062;
UPDATE dbscript_string SET content_default="O'course I'm talkin to myself. Only way to get decent conversation in this city.", broadcast_text_id=1108 WHERE entry=2000005105;
UPDATE dbscript_string SET content_default="Children if you would please follow me, we will now be going to see the keep where King Anduin Wrynn himself sits on his throne.", broadcast_text_id=1155 WHERE entry=2000005136;
UPDATE dbscript_string SET content_default="The magical wards at that point should be supported enough by the energy flux to contain the entity.", broadcast_text_id=207 WHERE entry=2000005151;
UPDATE dbscript_string SET content_default="But isn't that what caused the initial problems with Adept Syleria's magical formulae?", broadcast_text_id=214 WHERE entry=2000005160;
UPDATE dbscript_string SET content_default="Billy says Fizzles used to be a great wizard. But he got turned into a rabbit when one of his spells went bad.", broadcast_text_id=1091 WHERE entry=2000005184;
UPDATE dbscript_string SET content_default="Ask me how to get a free drink at the Blue Recluse!", broadcast_text_id=1192 WHERE entry IN (2000005191, 2000005197);
UPDATE dbscript_string SET content_default="Just sit right back and you'll hear a ta... *hic* a tai... *hic* a taiiii *hic* Damnit!", broadcast_text_id=6402 WHERE entry=2000005233;
UPDATE dbscript_string SET content_default="People of the Horde, citizens of Orgrimmar, come, gather round and celebrate a hero of the Horde. On this day, $N, under the auspices of our glorious Warchief, laid a mortal blow against the Black Dragonflight. The brood mother, Onyxia, has been slain!", broadcast_text_id=9491 WHERE entry=2000005236;
UPDATE dbscript_string SET content_default="%s bursts open!", broadcast_text_id=1460 WHERE entry=2000005241;
UPDATE dbscript_string SET content_default="My leg feels much better now, the remedy must be working. If you will excuse me, I must go report to my superiors about what has transpired here.", broadcast_text_id=7202 WHERE entry=2000005630;
UPDATE dbscript_string SET content_default="If you're here, then it means you are prepared to begin the study of summoning demonic cohorts to do your bidding. We will start with the lowliest creatures you will be able to call and continue from there. Let us begin.", broadcast_text_id=2049 WHERE entry=2000005634;
UPDATE dbscript_string SET content_default="Now that you have had a chance to study the imp, let us move on to the next minion you will be able to summon, the voidwalker.", broadcast_text_id=2052 WHERE entry=2000005637;
UPDATE dbscript_string SET content_default="This demonic entity is known as the Voidwalker. Its strength and endurance are significant, making it ideal for defense. Send it to attack your enemy, then use it as a shield while you use your spells and abilities to drain away your opponent's life.", broadcast_text_id=2053 WHERE entry=2000005638;
UPDATE dbscript_string SET content_default="All right now. Aside from the obvious distractions a minion like this will provide against your more masculine foes, she is also capable of dealing out impressive amounts of damage. However, her fragile endurance makes her almost useless as a shield.", broadcast_text_id=2055 WHERE entry=2000005640;
UPDATE dbscript_string SET content_default="Study hard and you might one day be able to summon one on your own, but for now it's time to move on to the felhunter.", broadcast_text_id=2056 WHERE entry=2000005641;
UPDATE dbscript_string SET content_default="When is pappa coming back from the fights in Warsong? It has been so long... ", broadcast_text_id=10303 WHERE entry=2000005775;
UPDATE dbscript_string SET content_default="%s listens to $N's report...", broadcast_text_id=981 WHERE entry=2000005777;
UPDATE dbscript_string SET content_default="Smashes the dead, twisted claw.", broadcast_text_id=984 WHERE entry=2000005779;
