-- Jordan's Weapon Notes
-- corrected (WDB data)
DELETE FROM page_text WHERE entry BETWEEN 871 AND 876;
INSERT INTO page_text (entry,text,next_page) VALUES
('871','$N,$BBefore I go any further, let me thank you again for everything you\'ve done for my wife and I. You saved her life, and for that, I owe you far more than I could possibly repay in a hundred lives. She is everything to me. If she would have died... well, I don\'t know what I would have done.$B$BHere is the list of things you\'ll need to recover if I am going to forge a holy weapon for you. I put them in order of what I thought was easiest to hardest--I hope that makes it simpler for you.','872'),
('872','Some good whitestone oak - Before it was taken over, the mines below Moonbrook in Westfall had an abundance of the lumber; they used it in the construction of some of their more important lattices and tools because of its resilience to heat and pressure.$B$BIt was brought down there after being shipped from overseas somewhere. It\'s a rare wood that is plenty strong enough to be used in the crafting of your weapon. If any of it\'s left in the mines, then the goblin woodcarvers would have it.','873'),
('873','Refined Ore - There is a dwarf in Thelsamar, a smith that I trained with for some time, named Bailor Stonehand. He makes a very special alloy that I think would be perfect for your weapon. I expected a shipment of the alloy to arrive while I was in Ironforge, but I have yet to hear word from him.$B$BFind him and check on the shipment. And if he\'s no longer in Loch Modan, I would at least know what\'s happened to my old teacher.','874'),
('874','Smithing Hammer - Before the coming of the Plague and Arthas\' betrayal, I lived in a town called Pyrewood, deep within the beautiful forest of Silverpine. The forest isn\'t nearly as beautiful as it once was, and the keep where I learned the secret of steel has long since become corrupt and foul, overrun with creatures of unimaginable evil.$B$BWhen my wife and I made our escape from what is now called Shadowfang Keep, we left some of our most precious possessions.','875'),
('875','Among them, the smithing hammer my father gave me. I doubted it in my youth, but he always told me the hammer was enchanted, and it\'s the last reminder I had of him before he was killed by the Scourge.$B$BBring me my hammer, $N, so I may use it as a focus for my passion. If it is indeed enchanted, then it will only aid us both.$B$BI left it in the stables in the main courtyard of the keep. Unless the creatures there have taken up smithing themselves, then I expect it to still be lying there.','876'),
('876','A Kor Gem - From the tales I\'ve been told, the gems are used by some spell casters to hold energy for their magics, making them even deadlier. A night elf I once helped, Thundris Windweaver, can tell you more since you will be speaking on my behalf. I believe one of the gem\'s stored energies can be used in your weapon\'s creation.$B$BWhen last we spoke, Thundris was in Auberdine a town deep within Darkshore, the corrupted forest that dots the coast underneath the shadow of the night elf homeland.','0');
