UPDATE dbscripts_on_creature_movement JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_movement JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_movement JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_movement JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_quest_start JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_start JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_start JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_start JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_quest_end JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_gossip JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_gossip JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_gossip JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_gossip JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_go_use JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_use JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_use JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_use JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_go_template_use JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_template_use JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_template_use JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_go_template_use JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_event JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_event JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_event JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_event JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_relay JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_relay JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_relay JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_relay JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_spell JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_spell JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_spell JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_spell JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscripts_on_creature_death JOIN dbscript_string ON dataint=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_death JOIN dbscript_string ON dataint2=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint2=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_death JOIN dbscript_string ON dataint3=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint3=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;
UPDATE dbscripts_on_creature_death JOIN dbscript_string ON dataint4=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET dataint4=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;

UPDATE dbscript_random_templates JOIN dbscript_string ON target_id=entry JOIN broadcast_text ON dbscript_string.broadcast_text_id=broadcast_text.id
SET target_id=broadcast_text_id, broadcast_text.`ChatTypeID`=dbscript_string.`type`, broadcast_text.SoundEntriesID1=CASE WHEN broadcast_text.SoundEntriesID1 > 0 THEN broadcast_text.SoundEntriesID1 ELSE dbscript_string.sound END, broadcast_text.EmoteID1=CASE WHEN broadcast_text.EmoteID1 > 0 THEN broadcast_text.EmoteID1 ELSE dbscript_string.emote END;


TRUNCATE TABLE dbscript_string;
