UPDATE `spawn_group` SET `Name` = 'Feralas - Ooze Covered Mithril Deposit | Ooze Covered Gold Vein | Ooze Covered Truesilver Deposit (1) Ore 000' WHERE (`Id` = '10013');
UPDATE `spawn_group` SET `Name` = 'Feralas - Ooze Covered Mithril Deposit | Ooze Covered Gold Vein | Ooze Covered Truesilver Deposit (1) Ore 001' WHERE (`Id` = '10014');
UPDATE `spawn_group` SET `Name` = 'Feralas - Ooze Covered Mithril Deposit | Ooze Covered Gold Vein | Ooze Covered Truesilver Deposit (1) Ore 002' WHERE (`Id` = '10015');
UPDATE `spawn_group` SET `Name` = 'Silithus - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 000' WHERE (`Id` = '10018');
UPDATE `spawn_group` SET `Name` = 'Silithus - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 001' WHERE (`Id` = '10019');
UPDATE `spawn_group` SET `Name` = 'Silithus - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 002' WHERE (`Id` = '10020');
UPDATE `spawn_group` SET `Name` = 'Silithus - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 003' WHERE (`Id` = '10021');
UPDATE `spawn_group` SET `Name` = 'Un\'Goro Crater - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 000' WHERE (`Id` = '10030');
UPDATE `spawn_group` SET `Name` = 'Un\'Goro Crater - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 001' WHERE (`Id` = '10031');
UPDATE `spawn_group` SET `Name` = 'Un\'Goro Crater - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 002' WHERE (`Id` = '10032');
UPDATE `spawn_group` SET `Name` = 'Un\'Goro Crater - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 003' WHERE (`Id` = '10033');
UPDATE `spawn_group` SET `Name` = 'Thousand Needles - Ooze Covered Mithril Deposit | Ooze Covered Silver Vein | Ooze Covered Gold Vein (1) Ore 001' WHERE (`Id` = '10011');
UPDATE `spawn_group` SET `Name` = 'Thousand Needles - Ooze Covered Mithril Deposit | Ooze Covered Silver Vein | Ooze Covered Gold Vein (1) Ore 000' WHERE (`Id` = '10010');
UPDATE `spawn_group` SET `Name` = 'Western Plaguelands - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 000' WHERE (`Id` = '21');
UPDATE `spawn_group` SET `Name` = 'Western Plaguelands - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 001' WHERE (`Id` = '22');
UPDATE `spawn_group` SET `Name` = 'Western Plaguelands - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 002' WHERE (`Id` = '23');
UPDATE `spawn_group` SET `Name` = 'Western Plaguelands - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 003' WHERE (`Id` = '24');
UPDATE `spawn_group` SET `Name` = 'Western Plaguelands - Mithril Deposit | Gold Vein | Truesilver Deposit (1) Ore 004' WHERE (`Id` = '25');
UPDATE `spawn_group` SET `Name` = 'Western Plaguelands - Rich Thorium Vein | Truesilver Deposit (1) Ore 000' WHERE (`Id` = '31');
UPDATE `spawn_group` SET `Name` = 'Western Plaguelands - Rich Thorium Vein | Truesilver Deposit (1) Ore 001' WHERE (`Id` = '32');
UPDATE `spawn_group` SET `Name` = 'Western Plaguelands - Rich Thorium Vein | Truesilver Deposit (1) Ore 002' WHERE (`Id` = '33');
UPDATE `spawn_group` SET `Name` = 'Feralas - Ooze Covered Thorium Vein | Ooze Covered Truesilver Deposit (1) Ore 000' WHERE (`Id` = '10012');
UPDATE `spawn_group` SET `Name` = 'Un\'goro Crater - Ooze Covered Thorium Vein | Ooze Covered Truesilver Deposit (1) Ore 000' WHERE (`Id` = '10016');
UPDATE `spawn_group` SET `Name` = 'Un\'goro Crater - Ooze Covered Thorium Vein | Ooze Covered Truesilver Deposit (1) Ore 001' WHERE (`Id` = '10017');
UPDATE `spawn_group` SET `Name` = 'Silithus - Ooze Covered Rich Thorium Vein | Ooze Covered Truesilver Deposit (1) Ore 000' WHERE (`Id` = '10022');
UPDATE `spawn_group` SET `Name` = 'Silithus - Ooze Covered Rich Thorium Vein | Ooze Covered Truesilver Deposit (1) Ore 001' WHERE (`Id` = '10023');
UPDATE `spawn_group` SET `Name` = 'Silithus - Ooze Covered Rich Thorium Vein | Ooze Covered Truesilver Deposit (1) Ore 002' WHERE (`Id` = '10024');
UPDATE `spawn_group` SET `Name` = 'Silithus - Ooze Covered Rich Thorium Vein | Ooze Covered Truesilver Deposit (1) Ore 003' WHERE (`Id` = '10025');
UPDATE `spawn_group` SET `Name` = 'Silithus - Ooze Covered Rich Thorium Vein | Ooze Covered Truesilver Deposit (1) Ore 004' WHERE (`Id` = '10026');
UPDATE `spawn_group` SET `Name` = 'Un\'Goro Crater - Rich Thorium Vein | Truesilver Deposit (1) Ore 000' WHERE (`Id` = '10027');
UPDATE `spawn_group` SET `Name` = 'Un\'Goro Crater - Rich Thorium Vein | Truesilver Deposit (1) Ore 001' WHERE (`Id` = '10028');
UPDATE `spawn_group` SET `Name` = 'Un\'Goro Crater - Rich Thorium Vein | Truesilver Deposit (1) Ore 002' WHERE (`Id` = '10029');
