-- all expansions
INSERT INTO worldstate_name(Id, Name) VALUES
(1778,'Arathi Basin - Occupied Bases Horde'),
(1779,'Arathi Basin - Occupied Bases Alliance'),
(1776,'Arathi Basin - Resources Alliance'),
(1777,'Arathi Basin - Resources Horde'),
(1780,'Arathi Basin - Resources Max'),
(1955,'Arathi Basin - Close to Victory warning threshold'),
(1842,'Arathi Basin - Stable Neutral'),
(1843,'Arathi Basin - Gold Mine Neutral'),
(1844,'Arathi Basin - Lumber Mill Neutral'),
(1845,'Arathi Basin - Farm Neutral'),
(1846,'Arathi Basin - Blacksmith Neutral'),
(1767,'Arathi Basin - Stable Alliance'),
(1768,'Arathi Basin - Stable Horde'),
(1769,'Arathi Basin - Stable contested Alliance'),
(1770,'Arathi Basin - Stable contested Horde'),
(1772,'Arathi Basin - Farm Alliance'),
(1773,'Arathi Basin - Farm Horde'),
(1774,'Arathi Basin - Farm contested Alliance'),
(1775,'Arathi Basin - Farm contested Horde'),
(1782,'Arathi Basin - Blacksmith Alliance'),
(1783,'Arathi Basin - Blacksmith Horde'),
(1784,'Arathi Basin - Blacksmith contested Alliance'),
(1785,'Arathi Basin - Blacksmith contested Horde'),
(1792,'Arathi Basin - Lumber Mill Alliance'),
(1793,'Arathi Basin - Lumber Mill Horde'),
(1794,'Arathi Basin - Lumber Mill contested Alliance'),
(1795,'Arathi Basin - Lumber Mill contested Horde'),
(1787,'Arathi Basin - Gold Mine Alliance'),
(1788,'Arathi Basin - Gold Mine Horde'),
(1789,'Arathi Basin - Gold Mine contested Alliance'),
(1790,'Arathi Basin - Gold Mine contested Horde');


