-- Order Warlock Pet Trainer Vendor Lists
-- classicmangos does not have them as _templates yet
-- ["Spackle Thornberry"] = { -- classicmangos only uses npc_vendor e.g.: https://www.wowhead.com/classic/npc=5520/spackle-thornberry
UPDATE `npc_vendor` SET `Slot` = 1 WHERE `item` = 16302; -- Grimoire of Firebolt (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 2 WHERE `item` = 16316; -- Grimoire of Firebolt (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 3 WHERE `item` = 16317; -- Grimoire of Firebolt (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 4 WHERE `item` = 16318; -- Grimoire of Firebolt (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 5 WHERE `item` = 16319; -- Grimoire of Firebolt (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 6 WHERE `item` = 16320; -- Grimoire of Firebolt (Rank 7)
UPDATE `npc_vendor` SET `Slot` = 7 WHERE `item` = 22179; -- Grimoire of Firebolt (Rank 8)
UPDATE `npc_vendor` SET `Slot` = 8 WHERE `item` = 16321; -- Grimoire of Blood Pact (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 9 WHERE `item` = 16322; -- Grimoire of Blood Pact (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 10 WHERE `item` = 16323; -- Grimoire of Blood Pact (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 11 WHERE `item` = 16324; -- Grimoire of Blood Pact (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 12 WHERE `item` = 16325; -- Grimoire of Blood Pact (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 13 WHERE `item` = 22180; -- Grimoire of Blood Pact (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 14 WHERE `item` = 16326; -- Grimoire of Fire Shield (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 15 WHERE `item` = 16327; -- Grimoire of Fire Shield (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 16 WHERE `item` = 16328; -- Grimoire of Fire Shield (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 17 WHERE `item` = 16329; -- Grimoire of Fire Shield (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 18 WHERE `item` = 16330; -- Grimoire of Fire Shield (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 19 WHERE `item` = 22181; -- Grimoire of Fire Shield (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 20 WHERE `item` = 16331; -- Grimoire of Phase Shift
UPDATE `npc_vendor` SET `Slot` = 21 WHERE `item` = 16346; -- Grimoire of Torment (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 22 WHERE `item` = 16347; -- Grimoire of Torment (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 23 WHERE `item` = 16348; -- Grimoire of Torment (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 24 WHERE `item` = 16349; -- Grimoire of Torment (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 25 WHERE `item` = 16350; -- Grimoire of Torment (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 26 WHERE `item` = 22182; -- Grimoire of Torment (Rank 7)
UPDATE `npc_vendor` SET `Slot` = 27 WHERE `item` = 16351; -- Grimoire of Sacrifice (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 28 WHERE `item` = 16352; -- Grimoire of Sacrifice (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 29 WHERE `item` = 16353; -- Grimoire of Sacrifice (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 30 WHERE `item` = 16354; -- Grimoire of Sacrifice (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 31 WHERE `item` = 16355; -- Grimoire of Sacrifice (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 32 WHERE `item` = 16356; -- Grimoire of Sacrifice (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 33 WHERE `item` = 22185; -- Grimoire of Sacrifice (Rank 7)
UPDATE `npc_vendor` SET `Slot` = 34 WHERE `item` = 16357; -- Grimoire of Consume Shadows (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 35 WHERE `item` = 16358; -- Grimoire of Consume Shadows (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 36 WHERE `item` = 16359; -- Grimoire of Consume Shadows (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 37 WHERE `item` = 16360; -- Grimoire of Consume Shadows (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 38 WHERE `item` = 16361; -- Grimoire of Consume Shadows (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 39 WHERE `item` = 16362; -- Grimoire of Consume Shadows (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 40 WHERE `item` = 22184; -- Grimoire of Consume Shadows (Rank 7)
UPDATE `npc_vendor` SET `Slot` = 41 WHERE `item` = 16363; -- Grimoire of Suffering (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 42 WHERE `item` = 16364; -- Grimoire of Suffering (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 43 WHERE `item` = 16365; -- Grimoire of Suffering (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 44 WHERE `item` = 16366; -- Grimoire of Suffering (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 45 WHERE `item` = 22183; -- Grimoire of Suffering (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 46 WHERE `item` = 28068; -- Grimoire of Suffering (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 47 WHERE `item` = 16368; -- Grimoire of Lash of Pain (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 48 WHERE `item` = 16371; -- Grimoire of Lash of Pain (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 49 WHERE `item` = 16372; -- Grimoire of Lash of Pain (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 50 WHERE `item` = 16373; -- Grimoire of Lash of Pain (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 51 WHERE `item` = 16374; -- Grimoire of Lash of Pain (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 52 WHERE `item` = 22186; -- Grimoire of Lash of Pain (Rank 7)
UPDATE `npc_vendor` SET `Slot` = 53 WHERE `item` = 16375; -- Grimoire of Soothing Kiss (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 54 WHERE `item` = 16376; -- Grimoire of Soothing Kiss (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 55 WHERE `item` = 16377; -- Grimoire of Soothing Kiss (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 56 WHERE `item` = 16378; -- Grimoire of Soothing Kiss (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 57 WHERE `item` = 22187; -- Grimoire of Soothing Kiss (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 58 WHERE `item` = 16379; -- Grimoire of Seduction
UPDATE `npc_vendor` SET `Slot` = 59 WHERE `item` = 16380; -- Grimoire of Lesser Invisibility
UPDATE `npc_vendor` SET `Slot` = 60 WHERE `item` = 16381; -- Grimoire of Devour Magic (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 61 WHERE `item` = 16382; -- Grimoire of Devour Magic (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 62 WHERE `item` = 16383; -- Grimoire of Devour Magic (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 63 WHERE `item` = 22188; -- Grimoire of Devour Magic (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 64 WHERE `item` = 22189; -- Grimoire of Devour Magic (Rank 6)
UPDATE `npc_vendor` SET `Slot` = 65 WHERE `item` = 16384; -- Grimoire of Tainted Blood (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 66 WHERE `item` = 16385; -- Grimoire of Tainted Blood (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 67 WHERE `item` = 16386; -- Grimoire of Tainted Blood (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 68 WHERE `item` = 16387; -- Grimoire of Tainted Blood (Rank 4)
UPDATE `npc_vendor` SET `Slot` = 69 WHERE `item` = 22190; -- Grimoire of Tainted Blood (Rank 5)
UPDATE `npc_vendor` SET `Slot` = 70 WHERE `item` = 16388; -- Grimoire of Spell Lock (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 71 WHERE `item` = 16389; -- Grimoire of Spell Lock (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 72 WHERE `item` = 16390; -- Grimoire of Paranoia
UPDATE `npc_vendor` SET `Slot` = 73 WHERE `item` = 28071; -- Grimoire of Anguish (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 74 WHERE `item` = 28072; -- Grimoire of Anguish (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 75 WHERE `item` = 28073; -- Grimoire of Anguish (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 76 WHERE `item` = 23734; -- Grimoire of Cleave (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 77 WHERE `item` = 23745; -- Grimoire of Cleave (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 78 WHERE `item` = 23755; -- Grimoire of Cleave (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 79 WHERE `item` = 23711; -- Grimoire of Intercept (Rank 1)
UPDATE `npc_vendor` SET `Slot` = 80 WHERE `item` = 23730; -- Grimoire of Intercept (Rank 2)
UPDATE `npc_vendor` SET `Slot` = 81 WHERE `item` = 23731; -- Grimoire of Intercept (Rank 3)
UPDATE `npc_vendor` SET `Slot` = 82 WHERE `item` = 25900; -- Grimoire of Demonic Frenzy
UPDATE `npc_vendor` SET `Slot` = 83 WHERE `item` = 25469; -- Grimoire of Avoidance

