DELETE FROM worldstate_name WHERE Id IN(4823);
REPLACE INTO `worldstate_name` (`Id`, `Name`) VALUES
(121, 'Sunken Temple - Jammal\'an the Prophet'),
(347, 'Dire Maul - Illyanna Ravenoak'),
(741, 'Molten Core - Golemagg the Incinerator'),
(761, 'Molten Core - Sulfuron Harbinger'),
(845, 'Molten Core - Baron Geddon'),
(846, 'Molten Core - Garr'),
(847, 'Molten Core - Magmadar'),
(848, 'Molten Core - Gehennas'),
(850, 'Molten Core - Shazzrah'),
(1201, 'Scarlet Monastery - High Inquisitor Whitemane'),
(1301, 'Alterac Valley - Stoneheart Graveyard Horde'),
(1302, 'Alterac Valley - Stoneheart Graveyard Alliance'),
(1303, 'Alterac Valley - Stoneheart Graveyard Horde Contested'),
(1304, 'Alterac Valley - Stoneheart Graveyard Alliance Contested'),
(1325, 'Alterac Valley - Dun Baldar Graveyard Alliance'),
(1326, 'Alterac Valley - Dun Baldar Graveyard Alliance Contested'),
(1327, 'Alterac Valley - Dun Baldar Graveyard Horde'),
(1328, 'Alterac Valley - Dun Baldar Graveyard Horde Contested'),
(1333, 'Alterac Valley - Stormpike Graveyard Alliance'),
(1334, 'Alterac Valley - Stormpike Graveyard Horde'),
(1335, 'Alterac Valley - Stormpike Graveyard Alliance Contested'),
(1336, 'Alterac Valley - Stormpike Graveyard Horde Contested'),
(1337, 'Alterac Valley - Frostwolf Graveyard Alliance'),
(1338, 'Alterac Valley - Frostwolf Graveyard Horde'),
(1339, 'Alterac Valley - Frostwolf Graveyard Alliance Contested'),
(1340, 'Alterac Valley - Frostwolf Graveyard Horde Contested'),
(1341, 'Alterac Valley - Snowfall Alliance'),
(1342, 'Alterac Valley - Snowfall Horde'),
(1343, 'Alterac Valley - Snowfall Alliance contested'),
(1344, 'Alterac Valley - Snowfall Horde contested'),
(1346, 'Alterac Valley - Iceblood Graveyard Alliance'),
(1347, 'Alterac Valley - Iceblood Graveyard Horde'),
(1348, 'Alterac Valley - Iceblood Graveyard Alliance Contested'),
(1349, 'Alterac Valley - Iceblood Graveyard Horde Contested'),
(1355, 'Alterac Valley - Coldtooth Alliance'),
(1356, 'Alterac Valley - Coldtooth Horde'),
(1357, 'Alterac Valley - Coldtooth Neutral'),
(1358, 'Alterac Valley - Irondeep Alliance'),
(1359, 'Alterac Valley - Irondeep Horde'),
(1360, 'Alterac Valley - Irondeep Neutral'),
(1361, 'Alterac Valley - South Bunker Alliance'),
(1362, 'Alterac Valley - North Bunker Alliance'),
(1363, 'Alterac Valley - Icewing Bunker Alliance'),
(1364, 'Alterac Valley - Stoneheart Bunker Alliance'),
(1365, 'Alterac Valley - West Tower Alliance'),
(1366, 'Alterac Valley - East Tower Alliance'),
(1367, 'Alterac Valley - Tower Point Alliance'),
(1368, 'Alterac Valley - Iceblood Tower Alliance'),
(1370, 'Alterac Valley - South Bunker Horde'),
(1371, 'Alterac Valley - North Bunker Horde'),
(1372, 'Alterac Valley - Icewing Bunker Horde'),
(1373, 'Alterac Valley - Stoneheart Bunker Horde'),
(1374, 'Alterac Valley - North Bunker Alliance Contested'),
(1375, 'Alterac Valley - South Bunker Alliance Contested'),
(1376, 'Alterac Valley - Icewing Bunker Alliance Contested'),
(1377, 'Alterac Valley - Stoneheart Bunker Alliance Contested'),
(1378, 'Alterac Valley - South Bunker Horde Contested'),
(1379, 'Alterac Valley - North Bunker Horde Contested'),
(1380, 'Alterac Valley - Icewing Bunker Horde Contested'),
(1381, 'Alterac Valley - Stoneheart Bunker Horde Contested'),
(1382, 'Alterac Valley - West Tower Horde'),
(1383, 'Alterac Valley - East Tower Horde'),
(1384, 'Alterac Valley - Tower Point Horde'),
(1385, 'Alterac Valley - Iceblood Tower Horde'),
(1387, 'Alterac Valley - West Tower Alliance Contested'),
(1388, 'Alterac Valley - East Tower Alliance Contested'),
(1389, 'Alterac Valley - Tower Point Alliance Contested'),
(1390, 'Alterac Valley - Iceblood Tower Alliance Contested'),
(1392, 'Alterac Valley - West Tower Horde Contested'),
(1393, 'Alterac Valley - East Tower Horde Contested'),
(1394, 'Alterac Valley - Tower Point Horde Contested'),
(1395, 'Alterac Valley - Iceblood Tower Horde Contested'),
(1502, 'Molten Core - Majordomo Executus'),
(1544, 'Dire Maul - King Gordok'),
(1545, 'Warsong Gulch - Picked up flag state Alliance'),
(1546, 'Warsong Gulch - Picked up flag state Horde'),
(1581, 'Warsong Gulch - Captures Alliance'),
(1582, 'Warsong Gulch - Captures Horde'),
(1601, 'Warsong Gulch - Captures Max'),
(1641, 'Blackwing Lair - Nefarian'),
(1666, 'Molten Core - Ragnaros'),
(1767, 'Arathi Basin - Stable Alliance'),
(1768, 'Arathi Basin - Stable Horde'),
(1769, 'Arathi Basin - Stable contested Alliance'),
(1770, 'Arathi Basin - Stable contested Horde'),
(1772, 'Arathi Basin - Farm Alliance'),
(1773, 'Arathi Basin - Farm Horde'),
(1774, 'Arathi Basin - Farm contested Alliance'),
(1775, 'Arathi Basin - Farm contested Horde'),
(1776, 'Arathi Basin - Resources Alliance'),
(1777, 'Arathi Basin - Resources Horde'),
(1778, 'Arathi Basin - Occupied Bases Horde'),
(1779, 'Arathi Basin - Occupied Bases Alliance'),
(1780, 'Arathi Basin - Resources Max'),
(1782, 'Arathi Basin - Blacksmith Alliance'),
(1783, 'Arathi Basin - Blacksmith Horde'),
(1784, 'Arathi Basin - Blacksmith contested Alliance'),
(1785, 'Arathi Basin - Blacksmith contested Horde'),
(1787, 'Arathi Basin - Gold Mine Alliance'),
(1788, 'Arathi Basin - Gold Mine Horde'),
(1789, 'Arathi Basin - Gold Mine contested Alliance'),
(1790, 'Arathi Basin - Gold Mine contested Horde'),
(1792, 'Arathi Basin - Lumber Mill Alliance'),
(1793, 'Arathi Basin - Lumber Mill Horde'),
(1794, 'Arathi Basin - Lumber Mill contested Alliance'),
(1795, 'Arathi Basin - Lumber Mill contested Horde'),
(1842, 'Arathi Basin - Stable Neutral'),
(1843, 'Arathi Basin - Gold Mine Neutral'),
(1844, 'Arathi Basin - Lumber Mill Neutral'),
(1845, 'Arathi Basin - Farm Neutral'),
(1846, 'Arathi Basin - Blacksmith Neutral'),
(1955, 'Arathi Basin - Close to Victory warning threshold'),
(1966, 'Alterac Valley - Snowfall Neutral'),
(1967, 'Zul\'gurub - High Priest Venoxis'),
(1968, 'Zul\'gurub - High Priestess Jeklik'),
(1969, 'Zul\'gurub - High Priestess Mar\'li'),
(1970, 'Zul\'gurub - High Priest Thekal'),
(1971, 'Zul\'gurub - High Priestess Arlokk'),
(2174, 'General Rajaxx completed'),
(2238, 'Naxxramas - Gothik the Harvester'),
(2242, 'Naxxramas - Gluth'),
(2243, 'Naxxramas - Thaddius'),
(2244, 'Naxxramas - Patchwerk '),
(2245, 'Naxxramas - Loatheb'),
(2247, 'Naxxramas - Grobbulus'),
(2253, 'Naxxramas - Maexxna'),
(2255, 'Naxxramas - Anub\'Rekhan'),
(2256, 'Naxxramas - Grand Widow Faerlina'),
(2257, 'Naxxramas - Noth the Plaguebringer'),
(2258, 'Naxxramas - Heigan the Unclean '),
(2268, 'Naxxramas - Sapphiron'),
(2269, 'Naxxramas - Kel\'Thuzad'),
(2296, 'Temple of Ahn\'Qiraj - Ouro'),
(2307, 'Naxxramas - Instructor Razuvious'),
(2309, 'Karazhan - Moroes - Encounter completed'),
(2315, 'Karazhan - Midnight - Encounter completed'),
(2336, 'Karazahn - Terestian Illhoof'),
(2338, 'Warsong Gulch - Horde HUD enabled'),
(2339, 'Warsong Gulch - Alliance HUD enabled'),
(2400, 'Blood Furnace - The Maker'),
(2403, 'Blood Furnace - Keli\'dan the Breaker'),
(2448, 'The Underbog - Swamplord Musel\'ek'),
(2464, 'Battle for Mount Hyjal - Anetheron'),
(2487, 'Battle for Mount Hyjal - Azgalor'),
(2501, 'Karazahn - The Curator'),
(2517, 'Karazahn - Chess Event'),
(2519, 'Battle for Mount Hyjal - Rage Winterchill'),
(2523, 'Battle for Mount Hyjal - Kaz\'rogal'),
(2530, 'Battle for Mount Hyjal - Archimonde'),
(2532, 'The Slave Pens - Quagmirran'),
(2702, 'Auchenai Crypts - Exarch Maladaar'),
(2711, 'The Escape From Durnholde - Captain Skarloc'),
(2718, 'Eye of the Storm - Point Slider Display'),
(2722, 'Eye of the Storm - Blood Elf Tower Neutral'),
(2723, 'Eye of the Storm - Blood Elf Tower Alliance'),
(2724, 'Eye of the Storm - Blood Elf Tower Horde'),
(2725, 'Eye of the Storm - Fel Reaver Ruins Neutral'),
(2726, 'Eye of the Storm - Fel Reaver Ruins Alliance'),
(2727, 'Eye of the Storm - Fel Reaver Ruins Horde'),
(2728, 'Eye of the Storm - Mage Tower Neutral'),
(2729, 'Eye of the Storm - Mage Tower Horde'),
(2730, 'Eye of the Storm - Mage Tower Alliance'),
(2731, 'Eye of the Storm - Draenei Ruins Neutral'),
(2732, 'Eye of the Storm - Draenei Ruins Alliance'),
(2733, 'Eye of the Storm - Draenei Ruins Horde'),
(2749, 'Eye of the Storm - Resources Alliance'),
(2750, 'Eye of the Storm - Resources Horde'),
(2752, 'Eye of the Storm - Towers Alliance'),
(2753, 'Eye of the Storm - Towers Horde'),
(2757, 'Eye of the Storm - Flag Ready'),
(2769, 'Eye of the Storm - Flag state Alliance'),
(2770, 'Eye of the Storm - Flag state Horde'),
(2778, 'Gruuls\'Lair - Highking Maulgar - Encounter completed'),
(2802, 'Shadow Labyrinth - Blackheart the Inciter'),
(2803, 'Shadow Labyrinth - Grandmaster Vorpil'),
(2804, 'Shattered Halls - Grand Warlock Nethekurse'),
(2818, 'Sethekk Halls - Talon King Ikiss'),
(2819, 'Caverns of Time - Aeonus'),
(2820, 'Caverns of Time - Chrono Lord Deja'),
(2821, 'Caverns of Time - Temporus'),
(2844, 'Shattered Halls - Warbringer O\'mrogg'),
(2853, 'Serpentshrine Cavern - Hydross the Unstable'),
(2854, 'Serpentshrine Cavern - Morogrim Tidewalker'),
(2855, 'Serpentshrine Cavern - The Lurker Below'),
(2856, 'Serpentshrine Cavern - Fathom-Lord Karathress'),
(2857, 'Serpentshrine Cavern - Leotheras the Blind'),
(2865, 'Karazahn - Netherspite'),
(2907, 'Shattered Halls - Warchief Kargath Bladefist'),
(2910, 'Karazahn - Shade of Aran'),
(3012, 'Black Temple - Supremus'),
(3013, 'Black Temple - High Warlord Naj\'entus'),
(3014, 'Black Temple - Gurtogg Bloodboil'),
(3022, 'Sethekk Halls - Anzu'),
(3030, 'Black Temple - The Illidari Council'),
(3058, 'Black Temple - Shade of Akama'),
(3077, 'Zul\'Aman - Nalorakk'),
(3122, 'Zul\'Aman - Akil\'zon'),
(3127, 'Alterac Valley - Score Alliance'),
(3128, 'Alterac Valley - Score Horde'),
(3133, 'Alterac Valley - Score Enabled Horde'),
(3134, 'Alterac Valley - Score Enabled Alliance'),
(3146, 'Zul\'Aman - Hex Lord Malacrass'),
(3152, 'Zul\'Aman - Halazzi'),
(3153, 'Zul\'Aman - Jan\'alai'),
(3336, 'Sunwell Plateau - Brutallus'),
(3337, 'Sunwell Plateau - Felmyst'),
(3423, 'Sunwell Plateau - M\'uru'),
(3434, 'Sunwell Plateau - Kalecgos'),
(3435, 'Sunwell Plateau - Eredar Twins'),
(3448, 'Magisters Terrace - Selin Fireheart'),
(3449, 'Magisters Terrace - Vexallus'),
(3450, 'Magisters Terrace - Priestess Delrissa'),
(3685, 'The Nexus - Frozen Commander'),
(3691, 'The Nexus - Grand Magus Telestra'),
(3692, 'The Nexus - Anomalus'),
(3693, 'The Nexus - Ormorok the Tree-Shaper'),
(3694, 'The Nexus - Keristrasza'),
(3808, 'Utgarde Pinnacle - King Ymiron'),
(3809, 'Utgarde Pinnacle - Skadi the Ruthless'),
(3828, 'Violet Hold - First Prisoner'),
(3833, 'Violet Hold - Second Prisoner'),
(3836, 'Violet Hold - Cyanigosa'),
(3850, 'Gun\'drakGal\'darah'),
(3851, 'Gun\'drakMoorabi'),
(3852, 'Gun\'drakSlad\'ran'),
(3853, 'Gun\'drakDrakkari Colossus'),
(3854, 'Gun\'drakEck the Ferocious'),
(3861, 'Halls of Stone - Tribunal of Ages'),
(3863, 'Halls of Lightning - General Bjarngrim'),
(3864, 'Halls of Lightning - Volkhan'),
(3865, 'Halls of Lightning - Ionar'),
(3866, 'Halls of Lightning - Loken'),
(3869, 'The Oculus - Drakos the Interrogator'),
(3870, 'Ahn\'kahet: The Old KingdomPrince Taldaram'),
(3871, 'The Oculus - Varos Cloudstrider'),
(3872, 'The Oculus - Mage-Lord Urom'),
(3873, 'The Oculus - Ley-Guardian Eregos'),
(3874, 'Azjol-Nerub - Krik\'thir the Gatewatcher'),
(4012, 'Naxxramas - The Four Horsemen'),
(4050, 'Ulduar - Hodir'),
(4057, 'Ulduar - Thorim'),
(4059, 'Ulduar - Freya'),
(4060, 'Ulduar - Mimiron'),
(4067, 'Ulduar - General Vezax'),
(4089, 'Ulduar - Kologarn'),
(4093, 'Ulduar - Algalon the Observer'),
(4114, 'Ulduar - Flame Leviathan'),
(4121, 'Ulduar - Yogg-Saron'),
(4138, 'Ulduar - XT-002 Deconstructor'),
(4140, 'Ulduar - Auriaya'),
(4241, 'Trial of the Crusader - Anub\'arak'),
(4272, 'Trial of the Crusader - Lord Jaraxxus'),
(4334, 'Trial of the Crusader - Val\'kyr Twins'),
(4361, 'Trial of the Champion - Grand Champions'),
(4362, 'Trial of the Champion - Argent Champion'),
(4363, 'Trial of the Champion - The Black Knight'),
(4370, 'Trial of the Crusader - Northrend Beasts'),
(4424, 'The Forge of Souls - Devourer of Souls'),
(4435, 'Icecrown Citadel - Rotface'),
(4471, 'Icecrown Citadel - Lord Marrowgar'),
(4492, 'Icecrown Citadel - Icecrown Gunship Battle'),
(4519, 'Icecrown Citadel - Deathbringer Saurfang'),
(4567, 'Scarlet Monastery - Interrogator Vishas'),
(4569, 'Scarlet Monastery - Houndmaster Loksey'),
(4570, 'Scarlet Monastery - Arcanist Doan'),
(4571, 'Scarlet Monastery - Herod'),
(4572, 'Scarlet Monastery - High Inquisitor Fairbanks'),
(4573, 'Scholomance - Kirtonos the Herald'),
(4574, 'Scholomance - Jandice Barov'),
(4575, 'Scholomance - Rattlegore'),
(4576, 'Scholomance - Marduk Blackpool'),
(4577, 'Scholomance - Vectus'),
(4578, 'Scholomance - Ras Frostwhisper'),
(4588, 'Scholomance - Instructor Malicia'),
(4589, 'Scholomance - Doctor Theolen Krastinov'),
(4590, 'Scholomance - Lorekeeper Polkelt'),
(4591, 'Scholomance - The Ravenian'),
(4592, 'Scholomance - Lord Alexei Barov'),
(4593, 'Scholomance - Lady Illucia Barov'),
(4594, 'Scholomance - Darkmaster Gandling'),
(4597, 'Shadowfang Keep - Baron Silverlaine'),
(4598, 'Shadowfang Keep - Commander Springvale'),
(4603, 'Auchenai Crypts - Shirrak the Dead Watcher'),
(4604, 'Mana-Tombs - Pandemonius'),
(4605, 'Mana-Tombs - Tavarok'),
(4606, 'Mana-Tombs - Nexus-Prince Shaffar'),
(4607, 'Mana-Tombs - Yor'),
(4608, 'Sethekk Halls - Darkweaver Syth'),
(4609, 'Shadow Labyrinth - Ambassador Hellmaw'),
(4610, 'Shadow Labyrinth - Murmur'),
(4611, 'Ahn\'kahet: The Old KingdomElder Nadox'),
(4612, 'Ahn\'kahet: The Old KingdomJedoga Shadowseeker'),
(4613, 'Ahn\'kahet: The Old KingdomHerald Volazj'),
(4614, 'Ahn\'kahet: The Old KingdomAmanitar'),
(4615, 'Azjol-Nerub - Hadronox'),
(4616, 'Azjol-Nerub - Anub\'arak'),
(4617, 'Blackfathom deeps - Ghamoo-ra'),
(4624, 'Blackfathom deeps - Aku\'mai'),
(4625, 'Blackrock Depths - High Interrogator Gerstahn'),
(4626, 'Blackrock Depths - Lord Roccor'),
(4627, 'Blackrock Depths - Houndmaster Grebmar'),
(4628, 'Blackrock Depths - Ring of Law'),
(4629, 'Blackrock Depths - Pyromancer Loregrain'),
(4630, 'Blackrock Depths - Lord Incendius'),
(4633, 'Blackrock Depths - Warder Stilgiss'),
(4634, 'Blackrock Depths - Fineous Darkvire'),
(4635, 'Blackrock Depths - Bael\'Gar'),
(4636, 'Blackrock Depths - General Angerforge'),
(4637, 'Blackrock Depths - Golem Lord Argelmach'),
(4638, 'Blackrock Depths - Hurley Blackbreath'),
(4639, 'Blackrock Depths - Phalanx'),
(4640, 'Blackrock Depths - Ribbly Screwspigot'),
(4641, 'Blackrock Depths - Plugger Spazzring'),
(4642, 'Blackrock Depths - Ambassador Flamelash'),
(4643, 'Blackrock Depths - The Seven'),
(4644, 'Blackrock Depths - Magmus'),
(4645, 'Blackrock Depths - Emperor Dagran Thaurissan'),
(4646, 'Blackrock Spire - Highlord Omokk'),
(4647, 'Blackrock Spire - Shadow Hunter Vosh\'gajin'),
(4648, 'Blackrock Spire - War Master Voone'),
(4649, 'Blackrock Spire - Mother Smolderweb'),
(4650, 'Blackrock Spire - Urok Doomhowl'),
(4651, 'Blackrock Spire - Quartermaster Zigris'),
(4652, 'Blackrock Spire - Gizrul the Slavener'),
(4653, 'Blackrock Spire - Halycon'),
(4654, 'Blackrock Spire - Overlord Wyrmthalak'),
(4659, 'The Escape From Durnholde - Lieutenant Drake'),
(4660, 'The Escape From Durnholde - Epoch Hunter'),
(4661, 'The Slave Pens - Mennu the Betrayer'),
(4662, 'The Slave Pens - Rokmar the Crackler'),
(4663, 'The Steamvault - Hydromancer Thespia'),
(4664, 'The Steamvault - Mekgineer Steamrigger'),
(4665, 'The Steamvault - Warlord Kalithresh'),
(4666, 'The Underbog - Hungarfen'),
(4667, 'The Underbog - Ghaz\'an'),
(4668, 'The Underbog - The Black Stalker'),
(4669, 'Dire Maul - Zevrim Thornhoof'),
(4670, 'Dire Maul - Hydrospawn'),
(4671, 'Dire Maul - Lethtendris'),
(4672, 'Dire Maul - Alzzin the Wildshaper'),
(4673, 'Dire Maul - Tendris Warpwood'),
(4675, 'Dire Maul - Magister Kalendris'),
(4676, 'Dire Maul - Immol\'thar'),
(4677, 'Dire Maul - Prince Tortheldrin'),
(4678, 'Dire Maul - Guard Mol\'dar'),
(4679, 'Dire Maul - Stomper Kreeg'),
(4680, 'Dire Maul - Guard Fengus'),
(4681, 'Dire Maul - Guard Slip\'kik'),
(4682, 'Dire Maul - Captain Kromcrush'),
(4683, 'Dire Maul - Cho\'Rush the Observer'),
(4684, 'Drak\'Tharon Keep - Trollgore'),
(4685, 'Drak\'Tharon Keep - Novos the Summoner'),
(4686, 'Drak\'Tharon Keep - King Dred'),
(4687, 'Drak\'Tharon Keep - The Prophet Tharon\'ja'),
(4688, 'The Culling of Stratholme - Meathook'),
(4689, 'The Culling of Stratholme - Salram the Fleshcrafter'),
(4690, 'The Culling of Stratholme - Chrono-Lord Epoch'),
(4691, 'The Culling of Stratholme - Mal\'ganis'),
(4693, 'Gnomeregan - Viscous Fallout'),
(4694, 'Gnomeregan - Grubbis'),
(4695, 'Gnomeregan - Electrocutioner 6000'),
(4696, 'Gnomeregan - Crowd Pummeler 9-60'),
(4697, 'Gnomeregan - Mekgineer Thermaplugg'),
(4698, 'Hellfire Ramparts - Watchkeeper Gargolmar - Encounter completed'),
(4699, 'Hellfire Ramparts - Omor the Unscarred - Encounter completed'),
(4700, 'Hellfire Ramparts - Vazruden the Herald - Encounter completed'),
(4701, 'Shattered Halls - Blood Guard Porung'),
(4702, 'Magisters Terrace - Kael\'thas Sunstrider'),
(4703, 'Maraudon - Noxxion'),
(4704, 'Maraudon - Razorlash'),
(4705, 'Maraudon - Lord Vyletongue'),
(4706, 'Maraudon - Celebras the Cursed'),
(4707, 'Maraudon - Landslide'),
(4708, 'Maraudon - Tinkerer Gizlock'),
(4709, 'Maraudon - Rotgrip'),
(4710, 'Maraudon - Princess Theradras'),
(4719, 'Stratholme - The Unforgiven'),
(4720, 'Stratholme - Hearthsinger Forresten'),
(4721, 'Stratholme - Timmy the Cruel'),
(4725, 'Stratholme - Balnazzar'),
(4726, 'Stratholme - Baroness Anastari'),
(4727, 'Stratholme - Nerub\'enkan'),
(4728, 'Stratholme - Maleki the Pallid'),
(4729, 'Stratholme - Magistrate Barthilas'),
(4733, 'Icecrown Citadel - Blood Council'),
(4734, 'Sunken Temple - Dreamscythe'),
(4735, 'Sunken Temple - Weaver'),
(4737, 'Sunken Temple - Morphaz'),
(4738, 'Sunken Temple - Hazzas'),
(4739, 'Sunken Temple - Avatar of Hakkar'),
(4740, 'Sunken Temple - Shade of Eranikus'),
(4741, 'The Arcatraz - Zereketh the Unbound'),
(4742, 'The Arcatraz - Dalliah the Doomsayer'),
(4743, 'The Arcatraz - Wrath-Scryer Soccothrates'),
(4744, 'The Arcatraz - Harbinger Skyriss'),
(4745, 'The Botanica - Commander Sarannis'),
(4746, 'The Botanica - High Botanist Freywinn'),
(4747, 'The Botanica - Thorngrin the Tender'),
(4748, 'The Botanica - Laj'),
(4749, 'The Botanica - Warp Splinter'),
(4750, 'The Mechanar - Mechano-Lord Capacitus'),
(4751, 'The Mechanar - Nethermancer Sepethrea'),
(4752, 'The Mechanar - Pathaleon the Calculator'),
(4758, 'Uldaman - Revelosh'),
(4761, 'Uldaman - The Lost Dwarves'),
(4762, 'Uldaman - Ironaya'),
(4764, 'Uldaman - Ancient Stone Keeper'),
(4765, 'Uldaman - Galgann Firehammer'),
(4766, 'Uldaman - Grimlok'),
(4767, 'Uldaman - Archaedas'),
(4768, 'Halls of Stone - Krystallus'),
(4769, 'Halls of Stone - Maiden of Grief'),
(4770, 'Halls of Stone - Sjonnir the Ironshaper'),
(4771, 'Utgarde Keep - Ingvar the Plunderer'),
(4772, 'Utgarde Keep - Skarvold & Dalronn'),
(4773, 'Utgarde Keep - Prince Keleseth'),
(4774, 'Utgarde Pinnacle - Svala Sorrowgrave'),
(4775, 'Utgarde Pinnacle - Gortok Palehoof'),
(4776, 'Wailing Caverns - Lady Anacondra'),
(4777, 'Wailing Caverns - Lord Cobrahn'),
(4778, 'Wailing Caverns - Kresh'),
(4779, 'Wailing Caverns - Lord Pythas'),
(4780, 'Wailing Caverns - Skum'),
(4781, 'Wailing Caverns - Lord Serpentis'),
(4782, 'Wailing Caverns - Verdan the Everliving'),
(4783, 'Wailing Caverns - Mutanus the Devourer'),
(4784, 'Zul\'Farrak - Hydromancer Velratha'),
(4785, 'Zul\'Farrak - Ghaz\'rilla'),
(4786, 'Zul\'Farrak - Antu\'sul'),
(4787, 'Zul\'Farrak - Theka the Martyr'),
(4788, 'Zul\'Farrak - Witch Doctor Zum\'rah'),
(4789, 'Zul\'Farrak - Nekrum Gutchewer'),
(4790, 'Zul\'Farrak - Shadowpriest Sezz\'ziz'),
(4791, 'Zul\'Farrak - Chief Ukorz Sandscalp'),
(4792, 'Black Temple - Teron Gorefiend'),
(4793, 'Black Temple - Reliquary of Souls'),
(4794, 'Black Temple - Illidan Stormrage'),
(4795, 'Blackwing Lair - Razorgore the Untamed'),
(4796, 'Blackwing Lair - Vaelastrasz the Corrupt'),
(4797, 'Blackwing Lair - Broodlord Lashlayer'),
(4798, 'Blackwing Lair - Firemaw'),
(4799, 'Blackwing Lair - Ebonroc'),
(4800, 'Blackwing Lair - Flamegor'),
(4801, 'Blackwing Lair - Chromaggus'),
(4802, 'Serpentshrine Cavern - Lady Vashj'),
(4803, 'Trial of the Crusader - Faction Champions'),
(4804, 'Gruuls\'Lair - Gruul the Dragonkiller - Encounter completed'),
(4805, 'Magtheridon - Trash Respawn'),
(4807, 'Karazahn - Prince Malchezaar'),
(4808, 'Karazahn - Nightbane'),
(4809, 'Molten Core - Lucifron'),
(4810, 'Onyxia\'s Lair - Onyxia'),
(4811, 'Kurinnaxx completed'),
(4812, 'Moam completed'),
(4813, 'Buru the Gorger completed'),
(4814, 'Ayamiss the Hunter completed'),
(4815, 'Ossirian the Unscarred completed'),
(4816, 'Sunwell Plateau - Kil\'jaeden'),
(4817, 'The Eye - Al\'ar'),
(4818, 'The Eye - Void Reaver'),
(4819, 'The Eye - High Astromancer Solarian'),
(4820, 'The Eye - Kael\'thas Sunstrider'),
(4821, 'Temple of Ahn\'Qiraj - The Prophet Skeram'),
(4822, 'Temple of Ahn\'Qiraj - Silithid Royalty'),
(4823, 'Temple of Ahn\'Qiraj - Battleguard Sartura - Encounter completed'),
(4824, 'Temple of Ahn\'Qiraj - Fankriss the Unyielding'),
(4825, 'Temple of Ahn\'Qiraj - Viscidus'),
(4826, 'Temple of Ahn\'Qiraj - Princess Huhuran'),
(4827, 'Temple of Ahn\'Qiraj - Twin Emperors'),
(4828, 'Temple of Ahn\'Qiraj - C\'thun'),
(4829, 'The Eye of Eternity - Malygos'),
(4830, 'The Obsidian Sanctum - Tenebron'),
(4831, 'The Obsidian Sanctum - Shadron'),
(4832, 'The Obsidian Sanctum - Vesperon'),
(4833, 'The Obsidian Sanctum - Sartharion'),
(4834, 'Ulduar - Ignis the Furnace Master'),
(4835, 'Ulduar - Razorscale'),
(4836, 'Vault of Archavon - Archavon the Stone Watcher'),
(4837, 'Vault of Archavon - Emalon the Storm Watcher'),
(4838, 'Vault of Archavon - Koralon the Flame Watcher'),
(4839, 'Zul\'gurub - Bloodlord Mandokir'),
(4840, 'Zul\'gurub - Gahz\'ranka'),
(4841, 'Zul\'gurub - Jin\'do the Hexxer'),
(4842, 'Icecrown Citadel - Sindragosa'),
(4844, 'Zul\'gurub - Hakkar'),
(4850, 'Zul\'gurub - Edge of Madness'),
(4852, 'Pit of Saron - Forgemaster Garfrost'),
(4854, 'Blood Furnace - Broggok'),
(4855, 'Icecrown Citadel - Valithria Dreamwalker'),
(4859, 'The Forge of Souls - Bronjahm '),
(4860, 'Pit of Saron - Krick'),
(4868, 'Icecrown Citadel - Queen Lana\'thel'),
(4869, 'Icecrown Citadel - Lady Deathwhisper'),
(4870, 'Icecrown Citadel - Festergut'),
(4871, 'Icecrown Citadel - Professor Putricide'),
(4895, 'Vault of Archavon - Toravon the Ice Watcher'),
(4897, 'Halls of Reflection - Falric'),
(4898, 'Halls of Reflection - Marwyn'),
(4910, 'Icecrown Citadel - The Lich King'),
(4948, 'Halls of Reflection - Escaped from Arthas'),
(5031, 'The Ruby Sanctum - Baltharus the Warborn'),
(5032, 'The Ruby Sanctum - Saviana Ragefire'),
(5033, 'The Ruby Sanctum - General Zarithrian'),
(5048, 'The Ruby Sanctum - Halion');

