-- Thrash s.3391
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 478;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 1202;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 1783;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 1791;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 1843;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 2236;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 2560;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 2681;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 2717;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 2728;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 3256;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 3378;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 3456;
UPDATE `creature_template_addon` SET `auras` = '6822' WHERE `entry` = 3746;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4023;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4348;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4374;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4389;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4390;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4493;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4634;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4645;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4652;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 4656;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5234;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5363;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5455;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5456;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5457;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5458;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5459;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5460;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 5977;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 6005;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 6140;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 6210;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 6347;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 6348;
UPDATE `creature_template_addon` SET `auras` = '7276' WHERE `entry` = 6349;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 7039;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 7101;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 7234;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 8208;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 8299;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 8961;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 8981;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 9777;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 10158;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 10836;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 10925;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 11075;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 11442;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 11713;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 11714;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 11737;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 12138;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 12940;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 14426;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 14446;
UPDATE `creature_template_addon` SET `auras` = NULL WHERE `entry` = 15305;
UPDATE `creature_template` SET `SpellList` = 1498801 WHERE `entry` = 14988;
DELETE FROM `creature_spell_list_entry` WHERE `Id` = 1498801;
INSERT INTO `creature_spell_list_entry` (`Id`, `Name`, `ChanceSupportAction`, `ChanceRangedAttack`) VALUES
(1498801, 'Zul''Gurub - Ohgan (14988)', 0, 0);
DELETE FROM `creature_spell_list` WHERE `Id` = 1498801;
INSERT INTO `creature_spell_list` (`Id`, `Position`, `SpellId`, `Flags`, `CombatCondition`, `TargetId`, `ScriptId`, `Availability`, `Probability`, `InitialMin`, `InitialMax`, `RepeatMin`, `RepeatMax`, `Comments`) VALUES
(1498801, 1, 3391, 0, -1, 0, 0, 100, 1, 10000, 20000, 10000, 20000, 'Ohgan - Thrash');

