ALTER TABLE db_version CHANGE COLUMN required_z2816_01_mangos_precision_decimal required_z2817_01_mangos_spell_template bit;

DROP TABLE `spell_bonus_data`;
ALTER TABLE db_version CHANGE COLUMN required_z2817_01_mangos_spell_template required_z2818_01_mangos_spell_template_ap bit;

