UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=0, ResistanceArcane=0 WHERE Entry=19732; -- Ango'rosh Warlock (Demon Armor, bestiary)
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=0, ResistanceArcane=0 WHERE Entry=19994; -- Bloodmaul Warlock (Demon Armor, bestiary)
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=0, ResistanceArcane=0 WHERE Entry=436; -- Blackrock Shadowcaster (Demon Armor, bestiary)
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=50, ResistanceArcane=0 WHERE Entry=432; -- Shadowhide Brute
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=50, ResistanceArcane=0 WHERE Entry=568; -- Shadowhide Warrior
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=50, ResistanceArcane=0 WHERE Entry=429; -- Shadowhide Darkweaver
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=50, ResistanceArcane=0 WHERE Entry=431; -- Shadowhide Slayer
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=56, ResistanceArcane=0 WHERE Entry=533; -- Nightbane Shadow Weaver
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=60, ResistanceArcane=0 WHERE Entry=920; -- Nightbane Tainted One
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=118, ResistanceArcane=0 WHERE Entry=2642; -- Vilebranch Shadowcaster
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=250, ResistanceArcane=0 WHERE Entry=2647; -- Vilebranch Soul Eater
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=0, ResistanceArcane=78 WHERE Entry=7034; -- Firegut Ogre Mage
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=150, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=0, ResistanceArcane=0 WHERE Entry=5861; -- Twilight Fire Guard
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=105, ResistanceArcane=0 WHERE Entry=5617; -- Wastewander Shadow Mage
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=106, ResistanceArcane=0 WHERE Entry=6006; -- Shadowsworn Adept
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=108, ResistanceArcane=0 WHERE Entry=6008; -- Shadowsworn Warlock
UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=30, ResistanceShadow=0, ResistanceArcane=0 WHERE Entry=1028; -- Bluegill Muckdweller

-- cmangos diff
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='92'; -- Rock Elemental (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry` IN (1051,1052,1053,1054,1169,1222,1981,2575,2577,4062,5839,5840,5844,5846,6123,6523,8337,8504,8566,8637,15692); -- Dark Iron (wrong 100AR)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='119'; -- Longsnout (20 wrong, bestiary, probably hunter pet stats)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceArcane`='0' WHERE `entry`='1225'; -- Ol' Sooty (40 wrong, petstats)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1514'; -- Mokk the Savage (pet stats)
UPDATE `creature_template` SET `ResistanceFrost`='165' WHERE `entry`='1800'; -- Cold Wraith (0 wrong, bestiary, removed in 1.4)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2149'; -- Dark Iron Raider (100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2275'; -- Enraged Stanley (5 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2605'; -- Zalas Witherbark (40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='2755'; -- Myzrael (94 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceShadow`='0' WHERE `entry`='3417'; -- Living Flame (300 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='3569'; -- Bogling (5 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='3899'; -- Balizar the Umbrage (96 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='3990'; -- Venture Co. Cutter (30 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='110' WHERE `entry`='4333'; -- Firemane Devourer (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='4386'; -- Withervine Bark Ripper (37 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='4396'; -- Mudrock Tortoise (74 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='4398'; -- Mudrock Burrower (80 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='4399'; -- Mudrock Borer (86 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='4400'; -- Mudrock Snapjaw (84 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='95' WHERE `entry`='4683'; -- Doomwarder Lord (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='75', `ResistanceFrost`='75', `ResistanceNature`='75', `ResistanceShadow`='75' WHERE `entry`='4816'; -- Murkshallow Shellhide (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='5277'; -- Nightmare Scalebane (204 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='5280'; -- Nightmare Wyrmkin (200 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='5283'; -- Nightmare Wanderer (196 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='120' WHERE `entry`='5400'; -- Zekkis (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='5432'; -- Giant Surf Glider (150 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5889'; -- Mesa Earth Spirit (1 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5896'; -- Fire Spirit (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='6748'; -- Water Spirit (19/38 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='76' WHERE `entry`='7135'; -- Infernal Bodyguard (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='50', `ResistanceShadow`='50', `ResistanceArcane`='0' WHERE `entry`='7664'; -- Razelikh the Defiler (240/0 Arcane wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0', `ResistanceNature`='0' WHERE `entry`='7734'; -- Ilifar (240 is wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='120', `ResistanceNature`='120', `ResistanceShadow`='120' WHERE `entry`='7735'; -- Felcular (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceShadow`='0' WHERE `entry`='7738'; -- Burning Servant (300/30 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='7809'; -- Vilebranch Ambusher (70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='8281'; -- Scald - https://github.com/cmangos/tbc-db/commit/75fa2a9e9b1c3608679e945ae32778cd8ba9e392
UPDATE `creature_template` SET `ResistanceShadow`='147' WHERE `entry`='8319'; -- Nightmare Whelp (147 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='8336'; -- Hakkari Sapper (2 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='125' WHERE `entry`='8438'; -- Hakkari Bloodkeeper (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='125' WHERE `entry`='8440'; -- Shade of Hakkar (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='8497'; -- Nightmare Suppressor (196 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='75', `ResistanceFrost`='75', `ResistanceNature`='75', `ResistanceShadow`='75' WHERE `entry`='8668'; -- Felhound Tracker (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9026'; -- Overmaster Pyron (208/104/156 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='162' WHERE `entry`='9031'; -- Anub'shiah (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9178'; -- Burning Spirit (60 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='125', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9396'; -- Ground Pounder (42 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='9522'; -- Blackrock Ambusher (100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='75', `ResistanceFrost`='75', `ResistanceNature`='75', `ResistanceShadow`='75' WHERE `entry`='9556'; -- Felhound Minion (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9601'; -- Treant Spirit (53/106 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='9605'; -- Blackrock Raider (100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='177' WHERE `entry`='10258'; -- Rookery Guardian (236 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='10373'; -- Xabraxxis (76 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10385'; -- Ghostly Citizen (171 wrong, wotlkmangos/no bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10581'; -- Young Arikara (2 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10882'; -- Arikara (2 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='177' WHERE `entry`='10683'; -- Rookery Hatcher (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='84' WHERE `entry`='10699'; -- Carrion Scarab (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='10737'; -- Shy-Rotam (10 wrong, bestiary pet stats)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10813'; -- Balnazzar (5/248 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='84' WHERE `entry`='10876'; -- Undead Scarab (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='180', `ResistanceFrost`='180', `ResistanceNature`='180', `ResistanceShadow`='180', `ResistanceArcane`='180' WHERE `entry`='11143'; -- Postmaster Malown (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='11262'; -- Onyxian Whelp (95 wrong, bestiary || wotlk might be different, but nature makes no sense.)
-- https://us.forums.blizzard.com/en/wow/t/does-ragnaros-have-a-vulnerability-to-frost/199160 could not be confirmed, high damage comes from frost mage talents.
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0', `ResistanceFrost`='0' WHERE `entry`='11502'; -- Ragnaros (-40 wrong, bestiary) 
UPDATE `creature_template` SET `ResistanceShadow`='161' WHERE `entry`='11779'; -- Shadowshard Thunderer (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='135' WHERE `entry`='11780'; -- Ambershard Rager (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='93' WHERE `entry`='12142'; -- Flamewaker Guardian (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='12237'; -- Meshlok the Harvester (30 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='150' WHERE `entry`='12739'; -- Onyxia's Elite Guard (90 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='95', `ResistanceNature`='95' WHERE `entry`='12806'; -- Magmakin (Added in SoM? xD)
UPDATE `creature_template` SET `ResistanceHoly`='60', `ResistanceFire`='60', `ResistanceFrost`='60', `ResistanceNature`='60', `ResistanceShadow`='60', `ResistanceArcane`='60' WHERE `entry`='12916'; -- Unkillable Test Dummy 60 Low Magic Resistances (0 makes no sense)
UPDATE `creature_template` SET `ResistanceHoly`='255', `ResistanceFire`='255', `ResistanceFrost`='255', `ResistanceNature`='255', `ResistanceShadow`='255', `ResistanceArcane`='255' WHERE `entry`='12917'; -- Unkillable Test Dummy 60 High Magic Resistances (0 makes no sense)
UPDATE `creature_template` SET `ResistanceFire`='100', `ResistanceArcane`='100' WHERE `entry`='14162'; -- RaidMage (subname: 100FR Arcane) (0 wrong)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='14340'; -- Alshirr Banebreath (216 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='75', `ResistanceFrost`='75', `ResistanceNature`='75', `ResistanceShadow`='75' WHERE `entry`='14502'; -- Xorothian Dreadsteed (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='14530'; -- Solenor the Slayer (239 worng, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='162' WHERE `entry`='14694'; -- Necrosis (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='14748'; -- Vilebranch Kidnapper (70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='1000' WHERE `entry`='15339'; -- Ossirian the Unscarred (0 wrong, bestiary: "Arcane Resistance: 01000"), if it was 0 it would not be written, typo. Also: SPELL_WEAKNESS_ARCANE   = 25181
UPDATE `creature_template` SET `ResistanceFire`='210', `ResistanceFrost`='210', `ResistanceNature`='210', `ResistanceShadow`='210', `ResistanceArcane`='210' WHERE `entry`='17536'; -- Nazan (Normal Version missing, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='24895'; -- Madrigosa (tbc wrong, rp npc now has SetDeathPrevention(true) so this hack is no longer needed)

-- part of vmangos diff showing some improvements
UPDATE `creature_template` SET `ResistanceFire`='0', `SchoolImmuneMask`='4' WHERE `entry`='89'; -- Infernal (300, immune)
UPDATE `creature_template` SET `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='157'; -- Goretusk (40/10 wrong, petstats)
UPDATE `creature_template` SET `ResistanceNature`='0', `SchoolImmuneMask`='8' WHERE `entry`='329'; -- Earth Elemental (260 wrong, immune)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='334'; -- Gath'Ilzogg (100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='423'; -- Redridge Mongrel (50 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='474'; -- Defias Rogue Wizard (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='594'; -- Defias Henchman (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='619'; -- Defias Conjurer (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1706'; -- Defias Prisoner (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1707'; -- Defias Captive (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1708'; -- Defias Inmate (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1711'; -- Defias Convict (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1715'; -- Defias Insurgent (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1725'; -- Defias Watchman (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1726'; -- Defias Magician (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='521'; -- Lupos (80 wrong, bestiary/petstats)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='628'; -- Black Ravager (wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='1258'; -- Black Ravager Mastiff (wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='742'; -- Green Wyrmkin (168 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='744'; -- Green Scalebane (172 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='100' WHERE `entry`='746'; -- Elder Dragonkin (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='40' WHERE `entry`='832'; -- Dust Devil (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1035'; -- Dragonmaw Swamprunner (25 wrong, bestiary only fire)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1049'; -- Wyrmkin Firebrand (5 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='1050'; -- Scalebane Royal Guard (5 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='1199'; -- Juvenile Snow Leopard (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='1201'; -- Snow Leopard (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceArcane`='0' WHERE `entry`='1253'; -- Father Gavin (30/70 wrong, vmangos) - looks like buffs?
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1495'; -- Deathguard Linnea (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1496'; -- Deathguard Dillinger (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1519'; -- Deathguard Simmer (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1735'; -- Deathguard Abraham (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1736'; -- Deathguard Randolph (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1737'; -- Deathguard Oliver (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1739'; -- Deathguard Phillip (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1741'; -- Deathguard Bartrand (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1742'; -- Deathguard Bartholomew (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1743'; -- Deathguard Lawrence (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1745'; -- Deathguard Morris (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1746'; -- Deathguard Cyrus (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2209'; -- Deathguard Gavin (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2210'; -- Deathguard Royann (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2405'; -- Tarren Mill Deathguard (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2418'; -- Deathguard Samsa (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2419'; -- Deathguard Humbert (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='5725'; -- Deathguard Lundmark (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6389'; -- Deathguard Podrig (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='7489'; -- Silverpine Deathguard (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='12428'; -- Deathguard Kel (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='1509'; -- Ragged Scavenger (1 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='1515'; -- Executor Zygand (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='150' WHERE `entry`='1795'; -- Searing Ghoul (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2038'; -- Lord Melenas (32 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='5760'; -- Lord Azrethoc (160 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9017'; -- Lord Incendius (55 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceArcane`='0' WHERE `entry`='11034'; -- Lord Maxwell Tyrosus (30/70 wrong, vmangos) - looks like buffs?
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12803'; -- Lord Lakmaeran (10/300 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='14506'; -- Lord Hel'nurath (10/248 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='2091'; -- Chieftain Nek'rosh (400 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2175'; -- Shadowclaw (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2241'; -- Syndicate Thief (100 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2252'; -- Crushridge Ogre (35-40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2253'; -- Crushridge Brute (35-40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2254'; -- Crushridge Mauler (35-40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2255'; -- Crushridge Mage (35-40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2256'; -- Crushridge Enforcer (35-40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2287'; -- Crushridge Warmonger (35-40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2416'; -- Crushridge Plunderer (35-40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0' WHERE `entry`='2425'; -- Varimathras (10 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceNature`='74' WHERE `entry`='2258'; -- Stone Fury (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2359'; -- Elemental Slave (15 wrong, immune)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2592'; -- Rumbling Exile (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2597'; -- Lord Falconcrest (100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2691'; -- Highvale Outrunner (66-70 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2692'; -- Highvale Scout (66-70 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2693'; -- Highvale Marksman (66-70 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='2694'; -- Highvale Ranger (66-70 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2735'; -- Lesser Rock Elemental (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2736'; -- Greater Rock Elemental (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2791'; -- Enraged Rock Elemental (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='70' WHERE `entry`='2752'; -- Rumbler (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='2761'; -- Cresting Exile (immune)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='2776'; -- Vengeful Surge (immune)
UPDATE `creature_template` SET `ResistanceFrost`='0', `SchoolImmuneMask`='16' WHERE `entry`='2794'; -- Summoned Guardian (immune, vmangos)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2919'; -- Fam'retor Guardian (15 wrong, immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceShadow`='0' WHERE `entry`='3272'; -- Kolkar Wrangler (missed) - https://github.com/cmangos/classic-db/commit/26ffcf944f13c148d63366f723089181b1ff46c5
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='3630'; -- Deviate Coiler (2 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='3631'; -- Deviate Stinglash (2 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5056'; -- Deviate Dreadfang (2 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5756'; -- Deviate Venomwing (2 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='3653'; -- Kresh (60 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='3654'; -- Mutanus the Devourer (400 wrong, immune)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='3662'; -- Delmanis the Hated (68 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='3773'; -- Akkrilus (104 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='75' WHERE `entry`='3917'; -- Befouled Water Elemental (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='3950'; -- Minor Water Guardian (1 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='4034'; -- Enraged Stone Spirit (25/50 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='4035'; -- Furious Stone Spirit (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='25', `ResistanceFrost`='25', `ResistanceNature`='25', `ResistanceShadow`='25', `ResistanceArcane`='0' WHERE `entry`='4053'; -- Daughter of Cenarius (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='4064'; -- Blackrock Scout (100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='4112'; -- Gravelsnout Vermin (80 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='4114'; -- Gravelsnout Forager (82 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='4116'; -- Gravelsnout Surveyor (90 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='4120'; -- Thundering Boulderkin (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='4499'; -- Rok'Alim the Pounder (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='4528'; -- Stone Rumbler (15 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='4619'; -- Geltharis (128 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceArcane`='0' WHERE `entry`='4787'; -- Argent Guard Thaelrid (70/30 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='4829'; -- Aku'mai (40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='4978'; -- Aku'mai Servant (26 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='5228'; -- Saturated Ooze (100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5243'; -- Cursed Atal'ai (30/70 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5256'; -- Atal'ai Warrior (30/70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5259'; -- Atal'ai Witch Doctor (30/70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5261'; -- Enthralled Atal'ai (30/70 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5263'; -- Mummified Atal'ai (30/70 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5267'; -- Unliving Atal'ai (30/70 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5270'; -- Atal'ai Corpse Eater (30/70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5271'; -- Atal'ai Deathwalker (30/70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5273'; -- Atal'ai High Priest (30/70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='5598'; -- Atal'ai Exile (30/70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='8317'; -- Atal'ai Deathwalker's Spirit (30/70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='8324'; -- Atal'ai Skeleton (30/70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='5288'; -- Rabid Longtooth (1 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='150', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5291'; -- Hakkari Frostwing (2 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5349'; -- Arash-ethis (85 wrong, petstats)
UPDATE `creature_template` SET `ResistanceFrost`='120', `SchoolImmuneMask`='16' WHERE `entry`='5461'; -- Sea Elemental (immune, but also resistance, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='125', `SchoolImmuneMask`='16' WHERE `entry`='5462'; -- Sea Spray (immune, but also resistance, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='125' WHERE `entry`='5465'; -- Land Rager (also immune, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='5624'; -- Undercity Guardian (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5834'; -- Azzere the Skyblade (55 wrong, petstats)
UPDATE `creature_template` SET `ResistanceFire`='170', `ResistanceNature`='170' WHERE `entry`='5855'; -- Magma Elemental (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='22', `ResistanceNature`='22' WHERE `entry`='11321'; -- Molten Elemental (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5890'; -- Redrock Earth Spirit (15 wrong)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5891'; -- Minor Manifestation of Earth (30 wrong)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5895'; -- Minor Manifestation of Water (30 wrong)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='5902'; -- Minor Manifestation of Air (30 wrong)
UPDATE `creature_template` SET `ResistanceFrost`='80' WHERE `entry`='6117'; -- Highborne Lichling (0, vmangos https://www.wowhead.com/wotlk/npc=6117/highborne-lichling#comments:id=297475)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6124'; -- Captain Beld (100 wrong, vmangos - dark iron issue)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6200'; -- Legashi Satyr (204 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6201'; -- Legashi Rogue (209 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6202'; -- Legashi Hellcaller (214 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6212'; -- Dark Iron Agent (100 wrong, bestiary - dark iron issue)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6228'; -- Dark Iron Ambassador (100 wrong, bestiary - dark iron issue)
UPDATE `creature_template` SET `ResistanceArcane`='100' WHERE `entry`='8338'; -- Dark Iron Marksman (100 wrong, bestiary - dark iron issue)
UPDATE `creature_template` SET `ResistanceFrost`='0', `SchoolImmuneMask`='16' WHERE `entry`='6220'; -- Irradiated Horror (immune vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='6239'; -- Cyclonian (immune, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='6352'; -- Coralshell Lurker (108 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6492'; -- Rift Spawn (17, vmangos - immune?)
UPDATE `creature_template` SET `ResistanceFire`='-51', `ResistanceFrost`='0' WHERE `entry`='6517'; -- Tar Beast (not -51 frost, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='-51', `ResistanceFrost`='0' WHERE `entry`='6518'; -- Tar Lurker (not -51 frost, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='-51', `ResistanceFrost`='0' WHERE `entry`='6519'; -- Tar Lord (not -51 frost, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='-51', `ResistanceFrost`='0' WHERE `entry`='6527'; -- Tar Creeper (not -51 frost, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='6550'; -- Mana Surge (immune, vmangos)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='6646'; -- Monnos the Elder (400 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='6932'; -- Swamp Spirit (40 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='190', `ResistanceFrost`='0', `ResistanceNature`='190', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='7031'; -- Obsidian Elemental (52 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='7099'; -- Ironbeak Hunter (20 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='7105'; -- Jadefire Satyr (200 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0', `SchoolImmuneMask`='8' WHERE `entry`='7132'; -- Toxic Horror (54/108 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='7266'; -- Ember (32/64, immune)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='7432'; -- Frostsaber Stalker (50 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='7433'; -- Frostsaber Huntress (50 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='7434'; -- Frostsaber Pride Watcher (50 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceShadow`='0' WHERE `entry`='7455'; -- Winterspring Owl (55/25 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceShadow`='0' WHERE `entry`='7456'; -- Winterspring Screecher (55/25 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='7846'; -- Teremus the Devourer
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='8211'; -- Old Cliff Jumper (90 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='8213'; -- Ironback (153/51 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='100' WHERE `entry`='8257'; -- Oozeling (100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='170', `ResistanceNature`='170' WHERE `entry`='8278'; -- Smoldar (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='100' WHERE `entry`='8302'; -- Deatheye (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='8303'; -- Grunter (40/10/230/60 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='8563'; -- Woodsman (88 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='8564'; -- Ranger (90 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='8565'; -- Pathstrider (87 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `SchoolImmuneMask`='4' WHERE `entry`='8616'; -- Infernal Servant (300 wrong, bestiary -> immune in vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0', `SchoolImmuneMask`='8' WHERE `entry`='8667'; -- Gusting Vortex (44 wrong, bestiary -> immune)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0', `SchoolImmuneMask`='4' WHERE `entry`='8680'; -- Massive Infernal (bestiary, immune in vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='8716'; -- Dreadlord (248A wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceShadow`='0' WHERE `entry`='8889'; -- Anvilrage Overseer (100/20 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceShadow`='0' WHERE `entry`='8890'; -- Anvilrage Warden (100/20 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='8911'; -- Fireguard Destroyer (55 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='153', `ResistanceFrost`='153', `ResistanceNature`='153', `ResistanceShadow`='153', `ResistanceArcane`='153' WHERE `entry`='8923'; -- Panzor the Invincible (0/30 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='8982'; -- Ironhand Guardian (58 wrong, immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9377'; -- Swirling Vortex (immune - https://www.wowhead.com/tbc/npc=9377/swirling-vortex#comments:id=207578, remaining resistances removed based on "Air Elementals")
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0', `SchoolImmuneMask`='8' WHERE `entry`='9397'; -- Living Storm (48 wrong, bestiary, immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9453'; -- Aquementas (54 wrong, bestiary -> immune)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9816'; -- Pyroguard Emberseer (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceShadow`='0' WHERE `entry`='9879'; -- Entropic Horror (300/30 wrong, based on Entropic Beast -> immune)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='10038'; -- Night Watch Guard (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='10157'; -- Moonkin Oracle (40 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='10264'; -- Solakar Flamewreath (177 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='150', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10371'; -- Rage Talon Captain (vmangos wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='150', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10366'; -- Rage Talon Dragon Guard (bestiary)
UPDATE `creature_template` SET `ResistanceFire`='150', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='9096'; -- Rage Talon Dragonspawn (bestiary)
UPDATE `creature_template` SET `ResistanceFire`='150', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10372'; -- Rage Talon Fire Tongue (bestiary)
UPDATE `creature_template` SET `ResistanceFire`='150', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10083'; -- Rage Talon Flamescale (bestiary)
UPDATE `creature_template` SET `ResistanceFire`='75', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10084'; -- Rage Talon Whelp (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='186', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10508'; -- Ras Frostwhisper (5 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10601'; -- Urok Enforcer (54 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10641'; -- Branch Snapper (250-375 wrong, bestiary, immunities?)
UPDATE `creature_template` SET `ResistanceFrost`='75' WHERE `entry`='10642'; -- Eck'alom (bestiary, also immune)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='10665'; -- Junior Apothecary Holland  (10 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='87', `ResistanceFrost`='29' WHERE `entry`='10756'; -- Scalding Elemental (also immune)
UPDATE `creature_template` SET `ResistanceFire`='84', `ResistanceFrost`='28' WHERE `entry`='10757'; -- Boiling Elemental (also immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='10955'; -- Summoned Water Elemental (60/120 wrong, classic immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceArcane`='0' WHERE `entry`='11034'; -- Lord Maxwell Tyrosus (30/70 wrong)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceArcane`='0' WHERE `entry`='11035'; -- Betina Bigglezink (30/70 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceArcane`='0' WHERE `entry`='11036'; -- Leonid Barthalomew the Revered (30/70 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceArcane`='0' WHERE `entry`='11039'; -- Duke Nicholas Zverenhoff (30/70 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceArcane`='0' WHERE `entry`='11063'; -- Carlin Redpath (30/70 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11440'; -- Gordok Enforcer (54 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11441'; -- Gordok Brute (58 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11442'; -- Gordok Mauler (58 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11443'; -- Gordok Ogre-Mage (58 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11444'; -- Gordok Mage-Lord (58 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='11447'; -- Mushgog (30 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='11461'; -- Warpwood Guardian (-58 frost wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='11462'; -- Warpwood Treant (-55 frost wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='11464'; -- Warpwood Tangler (-56 frost wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='11465'; -- Warpwood Stomper (-58 frost wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11480'; -- Arcane Aberration (60-300 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11483'; -- Mana Remnant (290 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0', `SchoolImmuneMask`='64' WHERE `entry`='11484'; -- Residual Monstrosity (120 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0' WHERE `entry`='11496'; -- Immol'thar (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11576'; -- Whirlwind Ripper (based on 11744,11745, immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11577'; -- Whirlwind Stormwalker (based on 11744,11745, immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11578'; -- Whirlwind Shredder (based on 11744,11745, immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11744'; -- Dust Stormer (bestiary, immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0', `SchoolImmuneMask`='8' WHERE `entry`='11745'; -- Cyclone Warrior (bestiary, immune)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='11746'; -- Desert Rumbler (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='11747'; -- Desert Rager (15 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='11777'; -- Shadowshard Rumbler (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='11778'; -- Shadowshard Smasher (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='11781'; -- Ambershard Crusher (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='11782'; -- Ambershard Destroyer (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11783'; -- Theradrim Shardling (92 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11784'; -- Theradrim Guardian (48-240 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='11862'; -- Tsunaman (25 wrong, immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='11871'; -- Grinning Dog (2 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='11876'; -- Demon Spirit (148 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceFire`='95', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12018'; -- Majordomo Executus (vmangos wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='93', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12098'; -- Sulfuron Harbinger (vmangos wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='12118'; -- Lucifron (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12119'; -- Flamewaker Protector (10 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='12129'; -- Onyxian Warder (90 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12143'; -- Son of Flame (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='12201'; -- Princess Theradras (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceArcane`='0' WHERE `entry`='12259'; -- Gehennas (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0' WHERE `entry`='12264'; -- Shazzrah (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12265'; -- Lava Spawn (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='93', `ResistanceArcane`='0' WHERE `entry`='12396'; -- Doomguard Commander (5 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12431'; -- Gorefang (70 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceArcane`='0' WHERE `entry`='12432'; -- Old Vicejaw (28 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='75' WHERE `entry`='12759'; -- Tideress (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='12800'; -- Chimaerok (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='12801'; -- Arcane Chimaerok (0 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12802'; -- Chimaerok Devourer (5/300 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='75', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='12876'; -- Baron Aquanis (immune as per research too)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='13278'; -- Duke Hydraxis (immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='13279'; -- Discordant Surge (immune)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='13285'; -- Death Lash (58/290 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='13322'; -- Hydraxian Honor Guard (immune)
UPDATE `creature_template` SET `ResistanceFire`='25', `ResistanceFrost`='25', `ResistanceNature`='25', `ResistanceShadow`='25' WHERE `entry`='13737'; -- Marandis' Sister (cmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0' WHERE `entry`='14020'; -- Chromaggus (15 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='300' WHERE `entry`='14022'; -- Corrupted Red Whelp (180 wrong, vmangos)
UPDATE `creature_template` SET `ResistanceShadow`='0', `ResistanceNature`='300' WHERE `entry`='14023'; -- Corrupted Green Whelp (180 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFrost`='300',`ResistanceArcane`='150' WHERE `entry`='14024'; -- Corrupted Blue Whelp (bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='300' WHERE `entry`='14025'; -- Corrupted Bronze Whelp (0 wrong, vmangos:Brood Power: Bronze = Arcane)
UPDATE `creature_template` SET `ResistanceShadow`='275' WHERE `entry`='14061'; -- Phase Lasher (Fire) - https://www.wowhead.com/classic/spell=22352/phase-lasher-fire (reduces shadow by 275 gives other)
UPDATE `creature_template` SET `ResistanceShadow`='275' WHERE `entry`='14062'; -- Phase Lasher (Nature) - https://www.wowhead.com/classic/spell=22353/phase-lasher-nature (reduces shadow by 275 gives other)
UPDATE `creature_template` SET `ResistanceShadow`='275' WHERE `entry`='14063'; -- Phase Lasher (Arcane) - https://www.wowhead.com/classic/spell=22354/phase-lasher-arcane (reduces shadow by 275 gives other)
UPDATE `creature_template` SET `ResistanceShadow`='275' WHERE `entry`='14184'; -- Phase Lasher (Frost) - https://www.wowhead.com/classic/spell=22520/phase-lasher-frost (reduces shadow by 275 gives other)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='14232'; -- Dart (60 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='14234'; -- Hayoc (2 wrong, vmangos petstats)
UPDATE `creature_template` SET `ResistanceFrost`='200', `ResistanceArcane`='200' WHERE `entry`='14261'; -- Blue Drakonid (400/100 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceNature`='500' WHERE `entry`='14262'; -- Green Drakonid (400 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceArcane`='500' WHERE `entry`='14263'; -- Bronze Drakonid (0 wrong, vmangos 400 - sadly not in bestiary but see green.)
UPDATE `creature_template` SET `ResistanceFire`='500' WHERE `entry`='14264'; -- Red Drakonid (400 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='200', `ResistanceShadow`='200' WHERE `entry`='14265'; -- Black Drakonid (400/400 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='14390'; -- Expeditionary Mountaineer (290 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='14393'; -- Expeditionary Priest (290 wrong, cmangos)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='14399'; -- Arcane Torrent (60-300 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='14400'; -- Arcane Feedback (60 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='93', `ResistanceArcane`='0' WHERE `entry`='14452'; -- Enslaved Doomguard Commander (244 Arcane wrong, bestiary "Doomguard Commander")
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='14454'; -- The Windreaver (immune)
UPDATE `creature_template` SET `ResistanceFrost`='0' WHERE `entry`='14458'; -- Watery Invader (immune)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='14460'; -- Blazing Invader (immune)
UPDATE `creature_template` SET `ResistanceFire`='0' WHERE `entry`='14461'; -- Baron Charr (immune)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='14462'; -- Thundering Invader (immune)
UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='14464'; -- Avalanchion (immune)
UPDATE `creature_template` SET `ResistanceArcane`='0' WHERE `entry`='14535'; -- Artorius the Doombringer (240 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='15083'; -- Hazza'rah (15/20 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='15146'; -- Mad Voidwalker (60 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='15340'; -- Moam (155 wrong, bestiary)
UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0', `ResistanceArcane`='0' WHERE `entry`='15344'; -- Swarmguard Needler (95 wrong, bestiary)

-- SPELL_SCHOOL_NORMAL 1, SPELL_SCHOOL_HOLY 2, SPELL_SCHOOL_FIRE 4, SPELL_SCHOOL_NATURE 8
-- SPELL_SCHOOL_FROST 16, SPELL_SCHOOL_SHADOW 32, SPELL_SCHOOL_ARCANE 64 - classic,wotlk & vmangos diff
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='510'; -- Water Elemental (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='2593'; -- Rough Stone Elemental
UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='2723'; -- Stone Golem (8 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='2749'; -- Siege Golem (8 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='2751'; -- War Golem (8 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='2759'; -- Hematus (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='2791'; -- Enraged Rock Elemental (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='3640'; -- Evolving Ectoplasm (24 wrong, not immune)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='3674'; -- Skum (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='3950'; -- Minor Water Guardian (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='4676'; -- Lesser Infernal (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='5314'; -- Phantim (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='5465'; -- Land Rager (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='5718'; -- Rothos (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='5894'; -- Corrupt Minor Manifestation of Water (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='7093'; -- Vile Ooze (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='7137'; -- Immolatus (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='7429'; -- Frostmaul Preserver (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='8196'; -- Occulus (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='8197'; -- Chronalis (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='8198'; -- Tick (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='8519'; -- Blighted Surge
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='8520'; -- Plague Ravager
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='8521'; -- Blighted Horror
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='8522'; -- Plague Monstrosity
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='8837'; -- Muck Splash (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='8909'; -- Fireguard (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='8910'; -- Blazing Fireguard (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='8978'; -- Thauris Balgarr (needs research)
UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='8979'; -- Gruklash (needs research)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='9016'; -- Bael'Gar (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='9017'; -- Lord Incendius (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='9156'; -- Ambassador Flamelash (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='9436'; -- Spawn of Bael'Gar (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='9453'; -- Aquementas (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='9816'; -- Pyroguard Emberseer (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='9938'; -- Magmus (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='10184'; -- Onyxia (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='10642'; -- Eck'alom (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='10955'; -- Summoned Water Elemental
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='11256'; -- Manifestation of Water
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='11502'; -- Ragnaros (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='11666'; -- Firewalker (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='11667'; -- Flameguard (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='11668'; -- Firelord (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='11744'; -- Dust Stormer (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='11781'; -- Ambershard Crusher (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='11782'; -- Ambershard Destroyer (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='11783'; -- Theradrim Shardling (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='11784'; -- Theradrim Guardian (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='12056'; -- Baron Geddon (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='12143'; -- Son of Flame (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='12237'; -- Meshlok the Harvester (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='12496'; -- Dreamtracker (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='12498'; -- Dreamstalker (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='12759'; -- Tideress
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='13020'; -- Vaelastrasz the Corrupt (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='13278'; -- Duke Hydraxis (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='13279'; -- Discordant Surge (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='13280'; -- Hydrospawn (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='13282'; -- Noxxion (16 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='13322'; -- Hydraxian Honor Guard
UPDATE `creature_template` SET `SchoolImmuneMask`='0', `ResistanceFrost`='144' WHERE `entry`='13456'; -- Noxxion's Spawn (because of Noxxion)
UPDATE `creature_template` SET `SchoolImmuneMask`='0', `ResistanceFrost`='144' WHERE `entry`='13736'; -- Noxxious Essence
UPDATE `creature_template` SET `ResistanceFrost`='144' WHERE `entry`='13696'; -- Noxxious Scion
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='14269'; -- Seeker Aqualon
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='14399'; -- Arcane Torrent (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='14400'; -- Arcane Feedback (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='15302'; -- Shade of Taerar (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='15352'; -- Greater Earth Elemental (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='15438'; -- Greater Fire Elemental (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='15691'; -- The Curator (0 wrong)
-- https://www.wowhead.com/wotlk/npc=16243/plague-slime#comments:id=650109 - and poison/diseases
UPDATE `creature_template` SET `SchoolImmuneMask`='32' WHERE `entry`='16243'; -- Plague Slime (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='16783'; -- Plague Slime (Blue) (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='16784'; -- Plague Slime (Red) (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='16785'; -- Plague Slime (Green) (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='16488'; -- Arcane Anomaly (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='17358'; -- Fouled Water Spirit (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='21223'; -- Corrupted Rager (UNUSED) (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='21253'; -- Tainted Water Elemental (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='21260'; -- Purified Water Elemental (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='22009'; -- Tainted Elemental (0 wrong)

-- vmangos
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='1925'; -- Heat Miser
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='1926'; -- Snow Miser
UPDATE `creature_template` SET `SchoolImmuneMask`='2' WHERE `entry`='1927'; -- Good Miser
UPDATE `creature_template` SET `SchoolImmuneMask`='32' WHERE `entry`='1928'; -- Bad Miser
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='1929'; -- Earth Miser
UPDATE `creature_template` SET `SchoolImmuneMask`='1' WHERE `entry`='1930'; -- Steel Miser
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='5897'; -- Corrupt Water Spirit
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='5898'; -- Air Spirit
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='5902'; -- Minor Manifestation of Air
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='6239'; -- Cyclonian
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='6550'; -- Mana Surge
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='6748'; -- Water Spirit
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='11862'; -- Tsunaman (classic/vmangos)
UPDATE `creature_template` SET `SchoolImmuneMask`='64' WHERE `entry`='14397'; -- Mana Burst (0 wrong)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='14478'; -- Huricanian
UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='14668'; -- Corrupted Infernal
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='14887'; -- Ysondre (need proof, but all green dragons seem to be nature immune)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='14888'; -- Lethon (need proof)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='14889'; -- Emeriss (need proof)
UPDATE `creature_template` SET `SchoolImmuneMask`='8' WHERE `entry`='14890'; -- Taerar (need proof)
UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='15211'; -- Azure Templar

-- unclear stuff - alot more diff with vmangos due to wrong nostalrius/lh values
-- UPDATE creature_template SET ResistanceHoly=0, ResistanceFire=0, ResistanceNature=0, ResistanceFrost=0, ResistanceShadow=-80, ResistanceArcane=0 WHERE Entry=16803; -- Death Knight Understudy - wotlk only seemingly, bestiary has no such data.
-- UPDATE `creature_template` SET `ResistanceShadow`='0' WHERE `entry`='16342'; -- Mummified Headhunter - can not deny multiple comments, leaving this diff - https://www.wowhead.com/tbc/npc=16342/mummified-headhunter#comments:id=316189 - how to confirm? dmg logs?
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='2551'; -- Brutus (immune?)
-- UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='2887'; -- Prismatic Exile (41/82, immune?)
-- UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='3797'; -- Cenarion Protector (75, Needs to be mced for resistance values)
-- UPDATE `creature_template` SET `ResistanceNature`='0' WHERE `entry`='3833'; -- Cenarion Vindicator (80, Needs to be mced for resistance values)
-- UPDATE `creature_template` SET `ResistanceFire`='0', `ResistanceFrost`='0', `ResistanceNature`='0', `ResistanceShadow`='0' WHERE `entry`='4054'; -- Laughing Sister (50, Needs to be mced for resistance values)
-- UPDATE `creature_template` SET `ResistanceFire`='126', `ResistanceFrost`='300', `ResistanceNature`='126', `ResistanceShadow`='126', `ResistanceArcane`='300' WHERE `entry`='6109'; -- Azuregos (0,295)
-- UPDATE `creature_template` SET `ResistanceNature`='15' WHERE `entry`='7032'; -- Greater Obsidian Elemental (168,112)
-- UPDATE `creature_template` SET `ResistanceShadow`='100' WHERE `entry`='8526'; -- Dark Caster (0, mc needed)
-- UPDATE `creature_template` SET `ResistanceFire`='161', `ResistanceFrost`='161', `ResistanceNature`='161', `ResistanceShadow`='161', `ResistanceArcane`='161' WHERE `entry`='10387'; -- Vengeful Phantom (0, mc needed)
-- UPDATE `creature_template` SET `ResistanceShadow`='80' WHERE `entry`='10398'; -- Thuzadin Shadowcaster (177, mc needed)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='7665'; -- Grol the Destroyer (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='7666'; -- Archmage Allistarj (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='7667'; -- Lady Sevine (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='4' WHERE `entry`='7846'; -- Teremus the Devourer (fire immune? Needs research, also dots idk)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='8317'; -- Atal'ai Deathwalker's Spirit (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='11777'; -- Shadowshard Rumbler (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='11778'; -- Shadowshard Smasher (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='11785'; -- Ambereye Basilisk (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='11786'; -- Ambereye Reaver (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='14122'; -- Massive Geyser (needs research)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='15989'; -- Sapphiron (wotlk different?)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='126' WHERE `entry`='16127'; -- Spectral Trainee (wotlk different?)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='126' WHERE `entry`='16148'; -- Spectral Deathknight (wotlk different?)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='126' WHERE `entry`='16149'; -- Spectral Horse (wotlk different?)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='126' WHERE `entry`='16150'; -- Spectral Rider (wotlk different?)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='0' WHERE `entry`='6488'; -- Fallen Champion (needs research - https://www.wowhead.com/tbc/npc=6488/fallen-champion#comments:id=2905117)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='116' WHERE `entry`='7734'; -- Ilifar (needs research, seemingly dots but not the damage from direct spells)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='124' WHERE `entry`='7735'; -- Felcular (needs research, seemingly dots but not the damage from direct spells)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='13456'; -- Noxxion's Spawn (waiting for confirmation)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='16' WHERE `entry`='13736'; -- Noxxious Essence (waiting for confirmation)
-- UPDATE `creature_template` SET `SchoolImmuneMask`='108' WHERE `entry`='15275'; -- Emperor Vek'nilash (Not immune to frost vmangos - waiting for confirmation)

